### ISSUE TITLE
Get-PASAccountPassword

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#100]
## Your Environment

* PowerShell Version: 5.1.15063.1292
* psPAS Branch & Version: 2.2.2 master
* CyberArk Version: 10.5

## Expected Behaviour
$tokenCA_username = Connect-CAVault -baseURI $baseURICA -credential oledmn -connectionNumber $connectionNumber
$accountsCA_username = $tokenCA_username | Get-PASAccount -search 'username' -filter "safename eq Safe-username"
$password_username = $accountsCA_username | Get-PASAccountPassword -UseV10API
should return password

## Current Behaviour
Returns error
Get-PASAccountPassword : The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  AccountID

## Possible Solution

Add -AccountID parrameter
$password_username = $accountsCA_username | Get-PASAccountPassword -UseV10API -AccountID $accountsCA_username.id

**Comment by pspete** [comment]
Thanks for another contribution @olegasdo.
I'll look into this as soon as I can - initial thought is that v10  Get Account method returns "id", but v9 returned AccountID - Get-PASPassword maybe needs an update to expect a parameter named id.

**Comment by olegasdo** [comment]
No problems :) your module saved me a lot of time, so it's the least I can do 👍

**Comment by pspete** [comment]
Now fixed in version 2.2.10 va the master branch or PowerShell Gallery
