### ISSUE TITLE
Get-PASAccount limit parameter

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#101]
Hi
Is there a reason that limit parameter returns error, when set larger than 999? :) 

Invoke-PASRestMethod : [400] There are some invalid parameters
At C:\Program Files\WindowsPowerShell\Modules\psPAS\2.2.2\Functions\Accounts\Get-PASAccount.ps1:278 char:13

**Comment by pspete** [comment]
The maximum is apparently 1000 - which can be enforced by some parameter validation (that not currently in place).

**Comment by pspete** [comment]
Included the additional parameter validation in  version 2.2.10. obtain via the master branch or PowerShell Gallery
