### ISSUE TITLE
(500) Internal Server Error when attempting to authenticate

### ISSUE THREAD

**Issue by 27560** [pspete/psPAS#106]
**## Your Environment**

* PowerShell Version: **5**
* psPAS Branch & Version: **2.2.0**
* CyberArk Version: **10.3**

**## Expected Behaviour**

Login to Cyberark Rest API successfully

**## Current Behaviour**

Getting 500 Internal Server Error

**## Possible Solution**

I've confirmed with our Admin that our web.config file is setup correctly, and I've also confirmed firewall is not an issue, and I can telnet to our cyberark server on port 443.

**## Steps to Reproduce (for bug reports)**

    $PVWA_URL = 'https://mycyberarkurl.domain'

    # Declaration
    $webServicesLogon = "$PVWA_URL/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon"

    # Authentication
    $bodyParams = @{username = "myusername"; password = "mypassword"} | ConvertTo-JSON

    # Execution
    try {
        $logonResult = Invoke-RestMethod -Uri $webServicesLogon -Method POST -ContentType "application/json" -Body $bodyParams -ErrorVariable logonResultErr
        Return $logonResult.CyberArkLogonResult
    }
    catch {
        Write-Host "StatusCode: " $_.Exception.Response.StatusCode.value__
        Write-Host "StatusDescription: " $_.Exception.Response.StatusDescription
        Write-Host "Response: " $_.Exception.Message
        Return $false
    }
**## Sample Output**

StatusCode:  500
StatusDescription:  System.ServiceModel.ServiceActivationException
Response:  The remote server returned an error: (500) Internal Server Error.
False

**Comment by 27560** [comment]
When I try the psPAS module I got this:
```
$token = New-PASSession -Credential $Credentials -BaseUri 'https://mycyberarkurl.domain'
Invoke-PASRestMethod : [403] Authentication failure for User [myusername].
At C:\Program Files\WindowsPowerShell\Modules\psPAS\2.2.0\Functions\Authentication\New-PASSession.ps1:234 char:18
+ ... ASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : PASWS013E,Invoke-PASRestMethod
```

**Comment by pspete** [comment]
PVWA is returning a 403/Forbidden response - are you able to manually login with the user?
you can also set `$DebugPreference = "Continue"` & `$VerbosePreference = "Continue"` to get a few more details from the process.

**Comment by 27560** [comment]
Yes, I am able to login to the UI with same credentials, here is debug output:
```
DEBUG: Function: Get-PASParameter
DEBUG: Removing Parameter: BaseURI
DEBUG: Removing Parameter: Credential
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Calling Function: New-PASSession
DEBUG: Security Protocol: Tls12
DEBUG: [URI, https://mycyberarkurl.domain/PasswordVault/api/Auth/CyberArk/Logon] [Method, POST] [Body, {
    "username":  "myusername",
    "password":  "mypassword"
}] [SessionVariable, PASSession] [ContentType, application/json]
VERBOSE: POST https://mycyberarkurl.domain/PasswordVault/api/Auth/CyberArk/Logon with -1-byte payload
DEBUG: {"ErrorCode":"PASWS013E","ErrorMessage":"Authentication failure for User [myusername]."}
DEBUG: Status code: 403
Invoke-PASRestMethod : [403] Authentication failure for User [myusername].
At C:\Program Files\WindowsPowerShell\Modules\psPAS\2.2.0\Functions\Authentication\New-PASSession.ps1:234 char:18
+ ... ASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : PASWS013E,Invoke-PASRestMethod
```

**Comment by 27560** [comment]
When logging into the UI, it appears I am using "Windows Authentication" should I be specifying that in my API call? Or should I have our Cyberark Admin create an internal cyberark account?

**Comment by pspete** [comment]
I'm not 100% sure Windows authentication is supported via the API in 10.3, you can try with CyberArk, LDAP or RADIUS.

**Comment by 27560** [comment]
I added -type Windows, and now I am getting 401 Unauthorized, -type LDAP gives 403 Authentication failure. In the UI, when I logout, I see this Windows Authentication, Internal Cyber-Ark, and Duo Radius. The only one that works for me is Windows Authentication (which I do not have to type in a password).

**Comment by pspete** [comment]
The Logon method of the API changed between versions 10.3 & 10.4. 10.4 provides Windows as an option - the help text and parameters on  New-PASSession could possibly be reworked to make this clearer.
Confusingly, in 10.3 i thnk the command you need to use is:
`$token = New-PASSession -Credential $Credentials -BaseUri 'https://mycyberarkurl.domain' -UseV9API`

the **_-UseV9API_** flag will force the request to use the legacy API endpoint (which will not accept Windows creds).
Your remaining option is to use a CyberArk local account.

**Comment by 27560** [comment]
Ok, so since we are on 10.3 Windows authentication is not possible, therefore I require a local cyberark account to perform API calls?

**Comment by pspete** [comment]
Yes, that's what the documentation tells me - your cyberark admin can possibly confirm this for you too.
There is an open Pull Request #105 which may be related - but again, will only be applicable on a supported version of the API (10.4+).

**Comment by 27560** [comment]
My cyberark admin reset my local password, and I am now able to acquire a token, however, when I attempt to use the token, I get a 500 Internal Server Error:
```
DEBUG: Function: Get-PASParameter
DEBUG: Removing Parameter: sessionToken
DEBUG: Removing Parameter: BaseURI
DEBUG: Removing Parameter: WebSession
DEBUG: Removing Parameter: PVWAAppName
DEBUG: Removing Parameter: ExternalVersion
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Calling Function: Get-PASSafe
DEBUG: Security Protocol: Tls12
DEBUG: [URI, https://mycyberarkserver.domain/PasswordVault/WebServices/PIMServices.svc/Safes?query=root] [Method, GET] [Headers, System.Collections.Hashtable] [WebS
ession, Microsoft.PowerShell.Commands.WebRequestSession] [ContentType, application/json]
VERBOSE: GET https://mycyberarkserver.domain/PasswordVault/WebServices/PIMServices.svc/Safes?query=root with 0-byte payload
DEBUG: The remote server returned an error: (500) Internal Server Error.
DEBUG: Status code: 500
Invoke-PASRestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Program Files\WindowsPowerShell\Modules\psPAS\2.2.0\Functions\Safes\Get-PASSafe.ps1:159 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method GET -Headers $sess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 500,Invoke-PASRestMethod
```

**Comment by pspete** [comment]
I cannot reproduce this - using your same module/powershell/cyberark versions i get successful results:
![image](https://user-images.githubusercontent.com/10600090/46431817-b1d48a80-c744-11e8-888c-60f055fc8007.png)
My focus would remain on understanding the `500 Internal Server Error` received from the web server.

**Comment by 27560** [comment]
We checked the debug logs, and got this message:
`This collection already contains an address with the scheme https. There can be at most one address per scheme in this collection. If your service is being hosted in IIS you can fix the problem by setting 'system.serviceModel/serviceHostingEnvironment/multipleSiteBindingsEnabled' to true or specifying 'system.serviceModel/serviceHostingEnvironemnt/baseAddressPrefixFilters'.`

**Comment by pspete** [comment]
@27560 did your configuration change resolve your issue?

**Comment by 27560** [comment]
@pspete I was out of office yesterday, yes the configuration change worked for us. Thank you for your help & expertise. I look forward to using your well-crafted PS module :+1:
