### ISSUE TITLE
Parameter "Logon to" Add-PASAccount

### ISSUE THREAD

**Issue by DhollanderJonas** [pspete/psPAS#113]
Hi,
Im writing a script to stage new servers and automatically add local admin account to cyberark.
This works perfect using the following command (hardcoded for now)

CA version: 10.3

New-PASSession -type LDAP -Credential $credentials -BaseURI "xxxx" -SkipVersionCheck | Add-PASAccount -accountname "xxxx" -address "v01w0612.root.int" -userName Administrator -password $cred -platformID "xxxx" -SafeName "xxxx" | Close-PASSession

But I can't find the parameter for the last essential info.

![image](https://user-images.githubusercontent.com/17251918/48355384-2e3b8100-e694-11e8-984e-850cb8e28ae5.png)

Any ideas what i'm looking for?

**Comment by pspete** [comment]
Hi Jonas,

What version are you on? Based on the screenshot I'm assuming V9....

Try This:

````powershell
Add-PASAccount -accountname "xxxx" -address "v01w0612.root.int" -userName Administrator -password $cred -platformID "xxxx" -SafeName "xxxx" -DynamicProperties @{"LogonDomain" = "Some-NETBIOS-Name"}
````

If you are on 10.4+ the command changes

**Comment by DhollanderJonas** [comment]
Hi,

Yea by CA version i meant cyberark version which is 10.3 (wasnt clear, apologies)

I will try this and let you know if it works.
Thank you!!

**Comment by DhollanderJonas** [comment]
Hi pspete,

> -DynamicProperties @{"LogonDomain" = "Some-NETBIOS-Name"}

 did the trick.
Thanks a lot for the quick respons!!

**Comment by venkateshCyberArk** [comment]
Hello,

I am facing the same issue, while trying to add the parameter "LogonTo". It works for single server onboarding. However i am facing issue while onboarding the account in bulk.
Working:
Add-PASAccount -address X.X.X.X -userName ABCD -platformID windowsServerLocalAccount -SafeName CyberArk-test -DynamicProperties @{"logondomain"="X.X.X.X"}

I am trying to add the parameter as below while performing bulk onboarding.
Non-working:
Add-PASAccount -name $Account.name`
    -secretType Password `
    -secret $Password `
    -SafeName $Account.SafeName `
    -PlatformID $Account.PlatformID `
    -Address $Account.Address `
    -Username $Account.Username `
-platformAccountProperties $platformAccountProperties `
DynamicProperties @{"logondomain"="$Account.logondomain"}

Could you please advise.
Regards,
Venkatesh

**Comment by venkateshCyberArk** [comment]
Hello,

I am facing the same issue while adding "Logon to" parameter in bulk onboarding. It works fine for single account.
Kindly advise how to use the parameter DynamicProperties @{"LogonDomain" = "Some-NETBIOS-Name"} in bulk onboarding.
