### ISSUE TITLE
How to update the ExtraPass1(Logon Account) using Set-PASAccount ? Facing error stating Invalid value for parameter -Properties when I try to pass the value as -Properties @{"ExtraPass1Name"="Name";}

### ISSUE THREAD

**Issue by GeethaSelvam** [pspete/psPAS#114]
Cyberark version used is 9.7
I am not able to update the linked logon account/add new logon account for an already existing account.
While creating a new account I am able to link the account by passing the pipeline parameters of ExtraPass1Name,ExtraPass1Safe and ExtraPass1Folder

**Comment by GeethaSelvam** [comment]
Invoke-PASRestMethod : [400] Failed to update account 7791_4. Reason: Invalid value for parameter - Properties
At C:\Program Files\WindowsPowerShell\Modules\psPAS\Functions\Accounts\Set-PASAccount.ps1:285 char:14

This is the error faced

**Comment by pspete** [comment]
Hi @GeethaSelvam - i believe the API only allows the EXTRAPASS* properties to be set when adding an account (using the "classic"/pre v10 method), not when updating an account. 
The response you are receiving is accurate.

**Comment by GeethaSelvam** [comment]
thank u @pspete ...Is there any other way to update this logon account easily for a bulk of accounts.

**Comment by pspete** [comment]
PACLI perhaps? Your query would best be asked on the cyberark support forum.....
