### ISSUE TITLE
Client Certificate Support

### ISSUE THREAD

**Issue by NathanielMaier** [pspete/psPAS#115]
Similar to what I've discussed with @pspete in the CredentialRetriever module/issue #2, I'd like psPAS to support sending a client certificate with all API calls. Even if the REST API doesn't support client certificates for authentication, IIS could be configured to require client certificates.

Thanks and let me know if you need more information!

Nathaniel Maier

**Comment by pspete** [comment]
@NathanielMaier - there are some changes coming in the next major release of the module which have simplified implementing Client Certificate Support.
The required changes are now present in the [Version_3 Branch](https://github.com/pspete/psPAS/tree/version_3), and will find their way into master once development of psPAS 3.0 is complete.

**Comment by NathanielMaier** [comment]
Thanks, @pspete! I'll plan to test this out in the next few weeks/certainly once that major release is merged to the matter branch.
