### ISSUE TITLE
Get-PASSafeMember output

### ISSUE THREAD

**Issue by permster** [pspete/psPAS#116]
I'm curious why the choice to output psPAS.CyberArk.Vault.Safe.Member object when calling Get-PASSafeMember instead of a safe object with a nested object/property for Members?  The reason I ask is because things like searching for a safe that doesn't have a member named "Administrator" becomes much more difficult.

$token | Get-PASSafe | Get-PASSafeMember | ? {$_.UserName -ne "Administrator" }

Will return every single member of every single safe that is not named "Administrator".  Not useful in the slightest.  Kind of makes the simplistic pipeline approach a no go for what should be a simple query.

My workaround:
$safes = $token | Get-PASSafe
foreach ($safe in $safes) {
    $members = $safe | Get-PASSafeMember | ? {$_.UserName -eq "Administrator" }
    if ($members.Count -eq 0) { write-host $safe.SafeName }
}

Unless anyone knows a better way to achieve this?

**Comment by pspete** [comment]
Hi @permster - its been a while with no update from you, so closing this now.
If the solution in my previous comment doesn't work for you let me know.
