### ISSUE TITLE
New-PASSession connectionNumber not working on 10.5

### ISSUE THREAD

**Issue by 27560** [pspete/psPAS#119]
* PowerShell Version: 5.0.10586.117
* psPAS Branch & Version: latest
* CyberArk Version: Version 10.5.0 (10.5.0.48)

## Expected Behaviour

Obtain a PASSession

## Current Behaviour

Not obtaining PASSession

## Possible Solution

Does connectionNumber work for version 10.5? Is there an alternative method for having multiple sessions?

## Steps to Reproduce (for bug reports)

New-PASSession -BaseUri $BaseURI -UseDefaultCredentials -connectionNumber 47

## Sample Output

New-PASSession : Parameter set cannot be resolved using the specified named parameters.

## Context

Obtain a PASSession and have multiple sessions

**Comment by pspete** [comment]
Hi,

`ConnectionNumber` is not a valid parameter for logon with the 10.x API.

You can confirm this on your system here: https://pvwa/PasswordVault/swagger/ui/index#!/Auth/Auth_Logon

**Comment by 27560** [comment]
How does one allow multiple sessions in 10.x API?

**Comment by pspete** [comment]
You can attempt to use the legacy version of the API by specifying the `-UseV9API` switch on the `New-PASSession` function

**Comment by 27560** [comment]
New-PASSession -UseV9API -BaseUri $BaseURI -UseDefaultCredentials -connectionNumber 47
New-PASSession : Parameter set cannot be resolved using the specified named parameters.

It yields same error message

**Comment by pspete** [comment]
The "legacy" API only supports CyberArk, LDAP or RADIUS (and SAML) auth; there is no support for Windows authentication (so `UseDefaultCredentials` is superfluous).
The v10 API does support Windows auth (`UseDefaultCredentials` is valid here), with the caveat that `ConnectionNumber` cannot be specified.

**Comment by pspete** [comment]
`get-help new-passession` clearly shows the valid parameter combinations.

**Comment by 27560** [comment]
I need to use windows / usedefaultcredentials, but I also need the ability to have multiple connections. Is there any solution I can use? Any clue if connectionNumber was replaced with an alternative method?

**Comment by pspete** [comment]
Not that I know of - I think shared logon authentication is the only alternative, but its not windows auth.

**Comment by pspete** [comment]
@27560  there is literally nothing I can incorporate into the module to support your requirement. The only possibility would be if connectionNumber gets introduced as a parameter on the part of the API which supports windows auth.
If you have not already, I would log an enhancement request with the vendor.
