### ISSUE TITLE
404 with Get-PASSafe

### ISSUE THREAD

**Issue by Qvakk** [pspete/psPAS#120]
Seems like the Get-PASSafe goes to PimServices.svc/Safes with 404-result.
As in Get-PASAccount , I get the results as espected.

Did i miss something on the connections?

![image](https://user-images.githubusercontent.com/6873953/49875766-1b96a200-fe22-11e8-83e2-48d8ce53f0bf.png)

![image](https://user-images.githubusercontent.com/6873953/49876152-05d5ac80-fe23-11e8-986a-11ed40112fad.png)

Version 10.5
@pspete , I got disturbed on my desk. sry

**Comment by pspete** [comment]
There is no issue with the address for the `Get-PASSafes` function, there is no (published) "V10" api endpoint for it.

What is the command you run to get the error?

**Comment by Qvakk** [comment]
> There is no issue with the address for the `Get-PASSafes` function, there is no (published) "V10" api endpoint for it.
> 
> What is the command you run to get the error?

`$credentials = Get-Credential
$token = New-PASSession -Credential $credentials -type LDAP -BaseURI $pvwa_url -SkipVersionCheck
$token | Get-PASSafe -Verbose
`
