### ISSUE TITLE
Get-PASSafe only returns Wintel Safes with a 30 day or higher retention

### ISSUE THREAD

**Issue by rlbck38** [pspete/psPAS#121]
When running Get-PasSafe it returns only wintel Safes with a 30 day retention or greater. Unix safes however, are all returned.
Our environment is separated between *NIX and Wintel, each with their own CPM.
Is this a bug or am I doing something wrong?

**Comment by pspete** [comment]
A safe is just a logical container - Get-PASSafe is not looking at what is in the safe or what platform is applied.
Have you confirmed that the account you are using has equivalent permissions on the safes being returned vs. those that are not?

**Comment by rlbck38** [comment]
PAS is 2.3.6
PS is 5.1
CyberArk is 10.6
The command run is $token | Get-PASSafe with no parameter returns all our safes, but only WINTEL safes with a 30 day retention or higher are returned.
The *NIX safes return all retentions from1 day to 365 (our longest).

**Comment by rlbck38** [comment]
I have checked the settings and permissions of the user and they match.
I'm doing this in our Test environment, so I gave the user full perms on all safes as well as in PrivateArk.
It is a local user, btw. Local to PrivateArk, not a domain account.

**Comment by pspete** [comment]
And the user you have authenticated with has equivalent permissions on all of the safes (including the ones not returned)?

**Comment by pspete** [comment]
And you can see these safes if you login to PVWA with this user?

**Comment by rlbck38** [comment]
Yes I can

**Comment by pspete** [comment]
This is not something I can reproduce - I have no issue querying any safe to which I have rights regardless of the content, assigned CPM or retention period.
You are getting results - so this cannot be an issue with the module.
Maybe ask on the Vendor's community forum or log a support ticket with them.

**Comment by pspete** [comment]
What happens if you use get-passafe to query for the expected safes, or search for one by name?

**Comment by rlbck38** [comment]
Thanks Pete, looks like the issue was PBKAC
Missed a critical permission when setting up the local user in PrivateArk.

**Comment by pspete** [comment]
Happens to us all @rlbck38 - glad you got it figured out.
