### ISSUE TITLE
Minimum version requirement

### ISSUE THREAD

**Issue by rallen967** [pspete/psPAS#122]
* PowerShell Version: 5.1.16299.820
* psPAS Branch & Version: 2.3.6
* CyberArk Version: 9.10

I am attempting to run basic get-pas commands, like get-PASAccount, but receiving an error on almost every command even though the version compatibility table states it should work.

PS C:> $session | Get-PASAccount -id <username>
CyberArk 9.10.0 does not meet the minimum version requirement of 10.4 for Get-PASAccount (using ParameterSet: v10ByID)
At \\<UNCPath>\WindowsPowerShell\Modules\psPAS\2.3.6\Private\Assert-VersionRequirement.ps1:58 char:4
+             Throw "CyberArk $ExternalVersion does not meet the minimu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (CyberArk 9.10.0...erSet: v10ByID):String) [], RuntimeException
    + FullyQualifiedErrorId : CyberArk 9.10.0 does not meet the minimum version requirement of 10.4 for Get-PASAccount (using ParameterSet: v10ByID)

**Comment by pspete** [comment]
The ParameterSet detailed in the error message can only be used against version 10.4 or above.
For CyberArk Version 9.10, you can use the `-Keywords` and the `-Safe` parameters only.

**Comment by rallen967** [comment]
That explains it, thank you.
