### ISSUE TITLE
Issue wu

### ISSUE THREAD

**Issue by cybrAlex** [pspete/psPAS#123]
## Your Environment
* PowerShell Version: 5.1.17134.407
* psPAS Branch & Version:  Module version 2.3.6
* CyberArk Version: v10.5

## Expected Behaviour
RDP can be opened after retrieval and session can get established.

## Current Behaviour
File cannot be opened. It appears as if the format is not correct.

## Possible Solution
Maybe it's an issue with the format definition in the psPAS.Format.ps1xml file.

## Steps to Reproduce (for bug reports)
1 . Get session token
$script:sessionToken = New-PASSession -BaseURI $script:baseURI -UseDefaultCredentials

2 . Get account, retrieve connection parameters and save those to a RDP file
$script:sessionToken | Get-PASPSMConnectionParameter -AccountID 27_6 -ConnectionComponent PSM-RDP | Out-File -filepath C:\tmp\testConnection.rdp

## Sample Output
Please see below file
[testConnection.txt](https://github.com/pspete/psPAS/files/2761187/testConnection.txt)

## Context
Establish a session over CyberArk PSM with RDP file parameters that were retrieved via REST API

**Comment by pspete** [comment]
@cybrAlex I think the issue is that `Get-PASPSMConnectionParameter` just outputs a powershell object, not the correctly formatted strings to be able to make an RDP file directly.
I'll look into adding a way to get the output in the RDP file format.
