### ISSUE TITLE
Get-PASAccount platformAccountProperties is blank

### ISSUE THREAD

**Issue by 27560** [pspete/psPAS#124]
## Your Environment

* PowerShell Version: 5
* psPAS Branch & Version: latest
* CyberArk Version: 10.5

## Expected Behaviour

Return platformAccountProperties

## Current Behaviour

platformAccountProperties properties appears, but is blank

## Possible Solution

unknown

## Steps to Reproduce (for bug reports)

$token | Get-PASAccount -search $ADDRESS

## Sample Output

AccountID                 : 277_77
Safe                      : SAFENAME1
address                   : 10.10.10.10
userName                  : username1
name                      : server1-username1
platformId                : platform1
secretType                : password
platformAccountProperties : 
secretManagement          : @{automaticManagementEnabled=True; status=success; lastModifiedTime=1541111111; lastReconciledTime=1532222222}
createdTime               : 1/29/2019 5:10:10 AM

AccountID                 : 888_844
Safe                      : SAFENAME2
address                   : 20.20.20.20
userName                  : username2
name                      : server1-username2
platformId                : platform2
secretType                : password
platformAccountProperties : 
secretManagement          : @{automaticManagementEnabled=True; status=success; lastModifiedTime=1541111112; lastReconciledTime=1532222223}
createdTime               : 1/29/2019 5:11:10 AM

## Context

I am integrating Cyberark with BMC Server Automation. I am using what is known as an "Extended Object" which basically allows me to run a command, and display the output within my application. I can then store that data into my data warehouse. I am trying to gather all information I can about each server. Currently, I have no way of reporting on logon account & reconcile account information.

When  I use the API directly it yields the results I want:
# GET DEVICE INFO
$params = @{
    body =  @{
        "Keywords" = "$ADDRESS"
        "Safe" = "$SAFE"
    }
    uri = "$baseurl/PasswordVault/WebServices/PIMServices.svc/Accounts"
    headers = @{
        "Authorization" = "$($token.sessionToken.Values)"
    }
    method = "Get"   
}
$DEVICEINFO = Invoke-WebRequest @params -UseBasicParsing

------RETURNS--------

($DEVICEINFO.Content | ConvertFrom-Json).accounts.internalproperties

Key                       Value                
---                       -----                
LastSuccessReconciliation 1535111111          
ExtraPass3Safe            PASS3SAFENAME
ExtraPass3Folder          Root                 
ExtraPass3Name            PASS3ACCOUNTNAME
CreationMethod            PVWA                 
LastSuccessChange         1548222222         
CPMStatus                 success              
LastTask                  ChangeTask           
RetriesCount              -1

**Comment by pspete** [comment]
You are right that the `InternalProperties` property is not returned - I'll get something worked into the module to address that.
The issue is that this property is only returned from the V9 API. 
`platformAccountProperties` is only returned from the V10 API, from which Internal properties are not returned.
To get `InternalProperties`, there will be a limit of only being able to return the details of the first matched result, and searching using only the Keywords & Safe parameters.

**Comment by pspete** [comment]
@27560 
With the latest version of the module, `internalproperties` is now returned

**Comment by 27560** [comment]
Thanks Pete!

**Comment by gitshanif** [comment]
Is this issue still open? I am using psPAS ver.3.0 and if the lastsuccessreconcililation file category is present, the Get-PASAccount cmdlet fails.

Error mapping types.\r\n\r\nMapping types:\r\nIEnumerable`1 -> List`1\r\nSystem.Collections.Generic.IEnumerable`1[[CyberArk.PasswordVault.API.Objects.PVPassword, CyberArk.PasswordVault.API, Version=8.0.0.0, Culture=neutral, PublicKeyToken=40be1dbc8718670f]] -> System.Collections.Generic.List`1[[CyberArk.PasswordVault.PASWebServices.Models.AccountModel, CyberArk.PasswordVault.PASWebServices, Version=8.0.0.0, Culture=neutral, PublicKeyToken=40be1dbc8718670f]]"

**Comment by pspete** [comment]
this issue is closed @gitshanif . see my update on #184
