### ISSUE TITLE
Feature Request - Merge Functions into PSM1 file

### ISSUE THREAD

**Issue by McAndersDK** [pspete/psPAS#130]
Import time are insane. possible due to scan or something on my machine.

## Your Environment

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

pspas version 2.4.0 from Gallery

## Expected Behaviour

Snappy import :)

## Current Behaviour

Way to long.

## Possible Solution

At build time, merge all the functions into the PSM1 file.
both Private and Public

## Sample Output
No changes import time:
![image](https://user-images.githubusercontent.com/14300946/52223103-4131ac00-28a5-11e9-97a8-930e51ffea1b.png)

and then merged into the psm1 file:
![image](https://user-images.githubusercontent.com/14300946/52223370-c4530200-28a5-11e9-9025-a9a623d32eec.png)

## Context

use case, is a single run PowerShell window to connect to remote server, but query API, and making the RDP file.
So each server connect will spawn it's own window, atm, this take 8-10 seconds to start up.

**Comment by pspete** [comment]
Hi @McAndersDK - I will look into making module import more Snappy.

**Comment by McAndersDK** [comment]
Sweet :) I use this in my modules
```
"########################" | Add-Content "$release\$ModuleName.psm1"
"### Public Functions ###" | Add-Content "$release\$ModuleName.psm1"
"########################" | Add-Content "$release\$ModuleName.psm1"
foreach($function in (get-childitem $ModulePath\Public\ -Recurse)) {
    $content = Get-Content $function.fullname | Add-Content "$release\$ModuleName.psm1"
}
"#########################" | Add-Content "$release\$ModuleName.psm1"
"### Private Functions ###" | Add-Content "$release\$ModuleName.psm1"
"#########################" | Add-Content "$release\$ModuleName.psm1"
foreach($function in (get-childitem $ModulePath\Private\ -Recurse)) {
    Get-Content $function.fullname | Add-Content "$release\$ModuleName.psm1"
}
```
I do believe that merging the view and type xml would also add to a speed up :)

**Comment by pspete** [comment]
@McAndersDK - not yet merged into a single file, but module load time has been significantly improved

PowerShell 5.1 Before
![image](https://user-images.githubusercontent.com/10600090/52902039-28a98600-3203-11e9-81f3-2436d8e6cc8e.png)

PowerShell Core Before
![image](https://user-images.githubusercontent.com/10600090/52902041-3b23bf80-3203-11e9-9d45-c7a67cb39729.png)

PowerShell 5.1 After
![image](https://user-images.githubusercontent.com/10600090/52902046-4676eb00-3203-11e9-914c-94d9a8ffb411.png)

PowerShell Core After
![image](https://user-images.githubusercontent.com/10600090/52902056-55f63400-3203-11e9-876f-8d731b04f7fb.png)
