### ISSUE TITLE
New-PASSession returns invalid sessionToken

### ISSUE THREAD

**Issue by begunrom** [pspete/psPAS#133]
## Your Environment

* PowerShell Version:5.1.16299.820
* psPAS Branch & Version: pulled today from master branch
* CyberArk Version:10.5

## Expected Behaviour

Should return a valid token or an error message

## Current Behaviour

Authentication succeeds (if I use other account (without CyberArk access), I get an error) Token is invalid; does not contain a sessionToken.
Close-PASSession returns "$token | Close-PASSession
Invoke-PASRestMethod :  Bad Request  Bad Request HTTP Error 400. The request is badly formed.  
At C:\Users\guro\Documents\WindowsPowerShell\Modules\psPAS\Functions\Authentication\Close-PASSession.ps1:74 char:9"

## Steps to Reproduce (for bug reports)

1 . $token = New-PASSession -BaseURI https://pam.test.org -UseDefaultCredentials -Verbose

2 .$token

3 .$token.sessionToken

## Sample Output
`PS C:\Users\guro\Documents> $token = New-PASSession -BaseURI https://pam.test.org -UseDefaultCredentials -Verbose
VERBOSE: Performing the operation "Logon with User 'TEST\guro'" on target "https://pam.test.org/PasswordVault".
VERBOSE: POST https://pam.test.org/PasswordVault/api/Auth/Windows/Logon with -1-byte payload
VERBOSE: received 48-byte response of content type application/json; charset=utf-8
VERBOSE: SessionVariable Passed; Processing WebSession
VERBOSE: GET https://pam.test.org/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
WARNING: Could Not Determine CyberArk Version

PS C:\Users\guro\Documents> $token

sessionToken    BaseURI                
------------    -------                
{Authorization} https://pam.test.org

PS C:\Users\guro\Documents> $token.sessionToken

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
Authorization                                                                                                                                                         

PS C:\Users\guro\Documents>`

**Comment by pspete** [comment]
Hi @begunrom - 
I don't have an environment in which I can test the integrated windows auth process - can you can share the debug output? (redact as required).

````powershell
$DebugPreference = "Continue"
$token = New-PASSession -BaseURI https://pam.test.org -UseDefaultCredentials -Verbose
````

**Comment by begunrom** [comment]
As requested.
1)
PS C:\WINDOWS\system32> $DebugPreference = "Continue"
New-PASSession -BaseURI https://pam.test.org -UseDefaultCredentials -Verbose

DEBUG: Function: Get-PASParameter
DEBUG: Removing Parameter: Verbose
DEBUG: Removing Parameter: BaseURI
VERBOSE: Performing the operation "Logon with User 'TEST\guro'" on target "https://pam.test.org/PasswordVault".
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Invocation Origin: New-PASSession
VERBOSE: Setting Security Protocol to TLS12
DEBUG: [URI, https://pam.test.org/PasswordVault/api/Auth/Windows/Logon] [Method, POST] [Body, {
    "UseDefaultCredentials":  {
                                  "IsPresent":  true
                              }
}] [SessionVariable, PASSession] [UseDefaultCredentials, True] [ContentType, application/json] [UseBasicParsing, True]
VERBOSE: POST https://pam.test.org/PasswordVault/api/Auth/Windows/Logon with -1-byte payload
VERBOSE: received 48-byte response of content type application/json; charset=utf-8
DEBUG: Status code: 200
VERBOSE: SessionVariable Passed; Processing WebSession
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Invocation Origin: Get-PASServer
DEBUG: Security Protocol: Tls12
DEBUG: [URI, https://pam.test.org/PasswordVault/WebServices/PIMServices.svc/Server] [Method, GET] [Headers, System.Collections.Hashtable] [WebS
ession, Microsoft.PowerShell.Commands.WebRequestSession] [ContentType, application/json] [UseBasicParsing, True]
VERBOSE: GET https://pam.test.org/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
DEBUG: 
Bad Request

Bad Request
HTTP Error 400. The request is badly formed.

DEBUG: Status code: 400
WARNING: Could Not Determine CyberArk Version

sessionToken    BaseURI                
------------    -------                
{Authorization} https://pam.test.org

2)

PS C:\WINDOWS\system32> Invoke-WebRequest -Uri https://pam.test.org/passwordVault/api/Auth/Windows/Logon -Method POST -UseDefaultCredentials -Verbose
VERBOSE: POST https://pam.test.org/passwordVault/api/Auth/Windows/Logon with 0-byte payload
VERBOSE: received 48-byte response of content type application/json; charset=utf-8


StatusCode        : 200
StatusDescription : OK
Content           : {"AdditionalInfo":"","UserName":"TEST\\guro"}
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Cache-Control: no-cache, no-store, must-revalidate
                    Content-Type: application/json; charset=utf-8
                    Expires: -1
                    Set-Cookie: CA22222=; path=/PasswordVault/; HttpOnly,...
Forms             : {}
Headers           : {[Pragma, no-cache], [Cache-Control, no-cache, no-store, must-revalidate], [Content-Type, application/json; 
                    charset=utf-8], [Expires, -1]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 48

**Comment by pspete** [comment]
While you do get a 200 response, I do not see a session token being returned at all; even when the native `Invoke-WebRequest` command is used. The token should be returned under the `Content` property.

I have made a very slight edit to `New-PASSession` as I can see a "request body" being sent when it should not be.....

Please download & try the [issue-133 branch](https://github.com/pspete/psPAS/tree/issue-133) and confirm if your issue persists?

any insight @steveredden ?

**Comment by begunrom** [comment]
No change to the result:
DEBUG: Function: Get-PASParameter
DEBUG: Removing Parameter: Verbose
DEBUG: Removing Parameter: BaseURI
DEBUG: Removing Parameter: UseDefaultCredentials
VERBOSE: Performing the operation "Logon with User 'RWGROUP\guro'" on target "https://pam.rwgroup.org/PasswordVault".
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Invocation Origin: New-PASSession
DEBUG: Security Protocol: Tls12
DEBUG: [URI, https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon] [Method, POST] [Body, {

}] [SessionVariable, PASSession] [UseDefaultCredentials, True] [ContentType, application/json] [UseBasicParsing, True]
VERBOSE: POST https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon with -1-byte payload
VERBOSE: received 48-byte response of content type application/json; charset=utf-8
DEBUG: Status code: 200
VERBOSE: SessionVariable Passed; Processing WebSession
DEBUG: Function: Invoke-PASRestMethod
DEBUG: Invocation Origin: Get-PASServer
DEBUG: Security Protocol: Tls12
DEBUG: [URI, https://pam.rwgroup.org/PasswordVault/WebServices/PIMServices.svc/Server] [Method, GET] [Headers, System.Collections.Hashtable] [WebSession, Microsoft.PowerShell.Commands.WebReques
tSession] [ContentType, application/json] [UseBasicParsing, True]
VERBOSE: GET https://pam.rwgroup.org/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
DEBUG: 
Bad Request

Bad Request
HTTP Error 400. The request is badly formed.


DEBUG: Status code: 400
WARNING: Could Not Determine CyberArk Version

sessionToken    BaseURI                
------------    -------                
{Authorization} https://pam.rwgroup.org

**Comment by pspete** [comment]
I don't have an environment in which I can troubleshoot the Windows Authentication method - If you can provide native powershell commands which successfully obtain a usable Authorisation token I can work toward getting the fix into the module, a Pull Request would be even better...

**Comment by begunrom** [comment]
Hi Pete,

Thanks for trying to help me.

Any idea where I can find the CyberArk docs for the REST API?
As I am not too familiar with CyberArk, can you point me to the location of the log files on PVWA and if I do have to enable or increase the logging level within CyberArk somewhere.

**Comment by pspete** [comment]
The online documentation can be found in the [customer portal](https://cyberark-customers.force.com/s/login/)

The process validation does not have to be anything more than logging on and obtaining a session token:

````powershell
#logon
$token = Invoke-RestMethod -Method POST -UseBasicParsing -Uri https://pam.test.org/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials
````

And then, using the session token to initiate a logoff:

````powershell
#logoff
Invoke-RestMethod -Headers @{"Authorization"=$token} -Method POST -UseBasicParsing -Uri https://pam.test.org/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logoff 
````

When I am able, I'll reconfigure my development environment to support Windows auth - it may be awhile before I can though.

**Comment by pspete** [comment]
Possibly partially related to logoff bug identified in #134

**Comment by steveredden** [comment]
@begunrom do you have the following in your IIS config, particularly the <windowsAuthentication enabled="true" />


C:\Windows\System32\inetsrv\config\applicationHost.config 


<location path="Default Web Site/PasswordVault/api/auth/windows/logon">
<system.webServer>
<security>
<authentication>
<windowsAuthentication enabled="true" />
</authentication>
</security>
</system.webServer>
</location>

**Comment by RockwoolMon** [comment]
@steveredden yes, I have this in the config.

I tested again with version 2.4.8, result is the same.
In the IIS logs I see these 2 lines.
2019-02-21 20:40:15 10.45.203.22 POST /PasswordVault/api/Auth/Windows/Logon - 443 - 10.45.207.230 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+nl-BE)+WindowsPowerShell/5.1.16299.820 - 401 0 0 46
2019-02-21 20:40:15 10.45.203.22 POST /PasswordVault/api/Auth/Windows/Logon - 443 TEST\guro 10.45.207.230 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+nl-BE)+WindowsPowerShell/5.1.16299.820 - 200 0 0 531

Are there any other logs I could inspect for indications what goes wrong?

**Comment by RockwoolMon** [comment]
I found this in the CyberARk.WebApplication.log
Not sure if the last line "PASWS002I Ending method Auth::Logon" is a success of failure message.
Also "Casos SessionFactory Request: DuplicateSession" might indicate a problem.
_[21/02/2019 | 22:01:27.089292] | {pid=10232} | {tid=     3732} |  ::  | CASW051D ------------ STARTING Pre Request Handler Execute --------------
[21/02/2019 | 22:01:27.089685] | {pid=10232} | {tid=     3732} |  ::  | PASWS001I Starting method Auth::Logon
[21/02/2019 | 22:01:27.089901] | {pid=10232} | {tid=     3732} |  ::  | CASW013I Create child session for User [guro]
[21/02/2019 | 22:01:27.090185] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request: CreateChildSession
[21/02/2019 | 22:01:27.090364] | {pid=10232} | {tid=     3732} |  ::  | New Session-Instance created. (Vault [CAMainVault] user [XXXXXXXXXX])
[21/02/2019 | 22:01:27.090546] | {pid=10232} | {tid=     3732} |  ::  | Synchronizing with session. (Vault [CAMainVault] user [XXXXXXXXXX])
[21/02/2019 | 22:01:27.090578] | {pid=10232} | {tid=     3732} |  ::  | New Session-Instance created. (Vault [CAMainVault] user [guro])
[21/02/2019 | 22:01:27.090766] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request[CreateChildSession] ended.
[21/02/2019 | 22:01:27.091032] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: GetSessionCharacters
[21/02/2019 | 22:01:27.091158] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[GetSessionCharacters] ended.
[21/02/2019 | 22:01:27.091259] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: SetSessionCharacters
[21/02/2019 | 22:01:27.091458] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[SetSessionCharacters] ended.
[21/02/2019 | 22:01:27.091558] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: SetSessionInstanceCharacters
[21/02/2019 | 22:01:27.091653] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[SetSessionInstanceCharacters] ended.
[21/02/2019 | 22:01:27.091878] | {pid=10232} | {tid=     3732} |  ::  | EPVSW041D Got web service client IP 10.XXX.XXX.XXX
[21/02/2019 | 22:01:27.091975] | {pid=10232} | {tid=     3732} |  ::  | CASW036D Log on from IP 10.XXX.XXX.XXX
[21/02/2019 | 22:01:27.092090] | {pid=10232} | {tid=     3732} |  ::  | EPVSW041D Got web service client IP 10.XXX.XXX.XXX
[21/02/2019 | 22:01:27.092290] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: GetLoggedOnUserName
[21/02/2019 | 22:01:27.092389] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[GetLoggedOnUserName] ended.
[21/02/2019 | 22:01:27.092480] | {pid=10232} | {tid=     3732} |  ::  | CASW014D Impersonate user []
[21/02/2019 | 22:01:27.092730] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: Impersonate
[21/02/2019 | 22:01:27.092780] | {pid=10232} | {tid=     3732} |  ::  | Running PASVC [PASVCFullImpersonateEx] (control socket [0]) data socket [0], IP [XXXXXXXXXX] (Vault [CAMainVault] user [guro])
[21/02/2019 | 22:01:27.586689] | {pid=10232} | {tid=     3732} |  ::  | Done PASVC [PASVCFullImpersonateEx]. Rc = 0 (Duration=493 ms). (Vault [CAMainVault] user [guro])
[21/02/2019 | 22:01:27.586832] | {pid=10232} | {tid=     3732} |  ::  | closing control socket [9196]
[21/02/2019 | 22:01:27.586895] | {pid=10232} | {tid=     3732} |  ::  | closing data socket [10208]
[21/02/2019 | 22:01:27.587310] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[Impersonate] ended.
[21/02/2019 | 22:01:27.587472] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request: GetSessionToken
[21/02/2019 | 22:01:27.587577] | {pid=10232} | {tid=     3732} |  ::  | Casos Session Request[GetSessionToken] ended.
[21/02/2019 | 22:01:27.587674] | {pid=10232} | {tid=     3732} |  ::  | CASW024D Create request session
[21/02/2019 | 22:01:27.587773] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request: DuplicateSession
[21/02/2019 | 22:01:27.587813] | {pid=10232} | {tid=     3732} |  ::  | New Session-Instance created. (Vault [CAMainVault] user [XXXXXXXXXX])
[21/02/2019 | 22:01:27.587854] | {pid=10232} | {tid=     3732} |  ::  | Synchronizing with session. (Vault [CAMainVault] user [XXXXXXXXXX])
[21/02/2019 | 22:01:27.587884] | {pid=10232} | {tid=     3732} |  ::  | New Session-Instance created. (Vault [CAMainVault] user [guro])
[21/02/2019 | 22:01:27.587914] | {pid=10232} | {tid=     3732} |  ::  | Synchronizing with session. (Vault [CAMainVault] user [guro])
[21/02/2019 | 22:01:27.588056] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request[DuplicateSession] ended.
[21/02/2019 | 22:01:27.588162] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request: DeleteSessionTemporary
[21/02/2019 | 22:01:27.588270] | {pid=10232} | {tid=     3732} |  ::  | Casos SessionFactory Request[DeleteSessionTemporary] ended.
[21/02/2019 | 22:01:27.588379] | {pid=10232} | {tid=     3732} |  ::  | Casos LogonInfo Request: GetLogonInfo
[21/02/2019 | 22:01:27.588492] | {pid=10232} | {tid=     3732} |  ::  | Casos LogonInfo Request[GetLogonInfo] ended.
[21/02/2019 | 22:01:27.588930] | {pid=10232} | {tid=     3732} |  ::  | PASWS002I Ending method Auth::Logon_

**Comment by steveredden** [comment]
Do Pete's referenced raw api calls produce the same issues?  Trying to verify this is actually psPAS related.

```powershell
#logon
$token = Invoke-RestMethod -Method POST -Uri https://your.site/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials

**Comment by pspete** [comment]
@begunrom 
Any update from you on what you experience when you run the following:

````powershell
#logon
$token = Invoke-RestMethod -Method POST -Uri https://your.site/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials
````
Do you get a succesfull authentication/token?

**Comment by RockwoolMon** [comment]
this is what I get:
Invoke-RestMethod -Method POST -Uri https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials

AdditionalInfo UserName    
-------------- --------    
                      XXX\guro

**Comment by RockwoolMon** [comment]
Hi This is what I get:
Invoke-RestMethod -Method POST -Uri https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials

AdditionalInfo UserName    
                        XXX\guro

**Comment by RockwoolMon** [comment]
This is what I get:
Invoke-RestMethod -Method POST -Uri https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials

AdditionalInfo | UserName    
-------------- | --------    
               | XXX\guro

**Comment by begunrom** [comment]
This is what I get:
PS P:\> Invoke-RestMethod -Method POST -Uri https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials

AdditionalInfo|UserName
--------------|--------
 .             |XXXXX\guro

AdditionalInfo is empty. (Dot is only for formatting the table.)

**Comment by steveredden** [comment]
Something seems off, as that is supposed to return a session token:

https://cyberarkdocu.azurewebsites.net/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/CyberArk%20Authentication%20-%20Logon_v10.htm

**Comment by pspete** [comment]
@begunrom - you should be able to confirm that what you get back is not a valid session token by running this:

````powershell
#logon
$token = Invoke-RestMethod -Method POST -Uri https://your.site/PasswordVault/api/Auth/Windows/Logon -UseDefaultCredentials -UseBasicParsing
#logoff
Invoke-RestMethod -Headers @{"Authorization"=$token} -Method POST -UseBasicParsing -Uri https://pam.test.org/PasswordVault/API/Auth/Logoff
````
I'd expect the logoff part to error for you; as per the previous comment, the session token should be a 100+ character string returned from the API.

**Comment by begunrom** [comment]
Yes Logoff returns an error:
Invoke-RestMethod : {"ErrorCode":"PASWS006E","ErrorMessage":"The session token is missing, invalid or expired."}
At line:5 char:1
+ Invoke-RestMethod -Headers @{"Authorization"=$token} -Method POST -Us ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by begunrom** [comment]
I talked to one of the guys today, that was involved with the CyberArk implementation. He told me that we first do Windows authentication to be able to connect to the PVWA website. Then we do radius based authentication that links to multi factor authentication.
I was wondering if that could explain what we are seeing.
After the initial windows authentication, I tried to authenticate via Radius, but that did not work out better. IF MFA would have been a problem, I would have expected to receive a token on my mobile, but I received no token at all.

**Comment by begunrom** [comment]
I could get CyberArk authentication to work.
_$token = New-PASSession -BaseURI https://pam.rwgroup.org -type CyberArk -Credential $credential_ returns a token.

when I run the following script, windows authentication followed by Radius, I get the following error, but not MFA token on mobile.
PS P:\> _$password = ConvertTo-SecureString 'GCFE2late' -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ('RWGROUP\guro', $password)
$token1 = New-PASSession -BaseURI https://pam.rwgroup.org -UseDefaultCredentials
$token1
$token1.sessionToken
$token = New-PASSession -BaseURI https://pam.rwgroup.org -type RADIUS -Credential $credential
$token_
VERBOSE: POST https://pam.rwgroup.org/PasswordVault/api/Auth/Windows/Logon with -1-byte payload
VERBOSE: received 48-byte response of content type application/json; charset=utf-8
VERBOSE: SessionVariable Passed; Processing WebSession
VERBOSE: GET https://pam.rwgroup.org/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
WARNING: Could Not Determine CyberArk Version

VERBOSE: POST https://pam.rwgroup.org/PasswordVault/api/Auth/RADIUS/Logon with -1-byte payload
sessionToken    BaseURI                
------------    -------                
{Authorization} https://pam.rwgroup.org
                                       
Invoke-PASRestMethod : [403] Authentication failure.
At line:276 char:18
+ ... ASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : PASWS035E,Invoke-PASRestMethod

**Comment by pspete** [comment]
Good to know you can use CyberArk auth, but not much more i can offer on Windows/Radius auth unfortunately.

There is 1 "HowTo" video which may help you: https://www.youtube.com/watch?v=zxzUfEUN5dA&t

**Comment by pspete** [comment]
@begunrom - Closing this issue as there has not been any recent activity.
Happy to consider any required update to the module if there is a known logon method which works for you.
