### ISSUE TITLE
10.7 Upgrade Errors Authentication and Add-PASAccount

### ISSUE THREAD

**Issue by dokki767** [pspete/psPAS#134]
## Your Environment

* PowerShell Version: 5.1.16299.820
* psPAS Branch & Version: 2.4 master branch
* CyberArk Version: 10.7

## Expected Behaviour

Trying to authenticate to Vault API & upload a new account via Add-PASAccount.  Process previously working under CyberArk 10.3.

First output below is just depicting a token generation and immediately closing the session.  Which generates errors.  Second output is a snippet of error output from our automation testing against a 10.7 endpoint.

## Current Behaviour

Previous behavior was successful token generation and success adding a new account to the vault via Add-PASAccount

Since our 10.7 upgrade this process fails with errors included below.

## Possible Solution

Unknown at this point

## Steps to Reproduce (for bug reports)

First error is easy to reproduce against a 10.7 endpoint.

$credentials = get-credential
$token = new-passession -credential $credentials -baseuri https://pwa.contoso.com -type ldap -verbose
$token | close-passession

## Sample Output

PS C:\Users\user\Documents\Utilities> $token = new-passession -credential $credentials -baseuri https://pwa.contoso.com -type ldap -verbose
VERBOSE: Performing the operation "Logon with User 'APIuser'" on target "https://pwa.contoso.com/PasswordVault".
VERBOSE: POST https://pwa.contoso.com/PasswordVault/api/Auth/ldap/Logon with -1-byte payload
VERBOSE: received 182-byte response of content type application/json; charset=utf-8
VERBOSE: Assigning token to CyberArkLogonResult
VERBOSE: SessionVariable Passed; Processing WebSession
VERBOSE: GET https://pwa.contoso.com/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
WARNING: Could Not Determine CyberArk Version
PS C:\Users\user\Documents\Utilities> $token | close-passession
Invoke-PASRestMethod : The remote server returned an error: (404) Not Found.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\pspas\Functions\Authentication\Close-PASSession.ps1:74 char:9
+         Invoke-PASRestMethod -Uri $URI -Method POST -Headers $session ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 404,Invoke-PASRestMethod

PS C:\Users\user\Documents\Utilities> $token

sessionToken    BaseURI
------------    -------
{Authorization} https://pwa.contoso.com

PS C:\Users\user\Documents\Utilities> $token | close-passession
Invoke-PASRestMethod : The remote server returned an error: (404) Not Found.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\pspas\Functions\Authentication\Close-PASSession.ps1:74 char:9
+         Invoke-PASRestMethod -Uri $URI -Method POST -Headers $session ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 404,Invoke-PASRestMethod

SECOND SET OF OUTPUT FROM TRYING TO ADD-PASACCOUNT
ConvertFrom-Json : Invalid JSON primitive: The.
At \\contoso.com\dfs\share\AccountAutomation\psPas\Private\Invoke-PASRestMethod.ps1:169 char:30
+                     $response = $response | ConvertFrom-Json
+                                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJ 
   sonCommand
 
 
Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At \\contoso.com\dfs\share\AccountAutomation\psPas\Private\Invoke-PASRestMethod.ps1:133 char:19
+ ... $webResponse = Invoke-WebRequest @PSBoundParameters -ErrorAction Stop
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invok 
   e-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeW 
   ebRequestCommand

**Comment by pspete** [comment]
Hi @dokki767 - appreciate the information, but the module has not yet been updated to work with the 10.7 API yet.

**Comment by dokki767** [comment]
yep I noticed that, wanted to report the issue regardless for your awareness.

**Comment by pspete** [comment]
When adding an account, have you updated your code to account for the new ParameterSet introduced for working with version 10.4 onward?

**Comment by dokki767** [comment]
I have not, but I was focusing on the Close-PASSession issue first.

**Comment by pspete** [comment]
Looks like I missed a change to logoff URL some versions back.

**Comment by dokki767** [comment]
https://<IIS_Server_Ip>/PasswordVault/API/Auth/Logoff is the new logoff endpoint from the API guide.  I'll dig into the missing parameter on the add-pasaccount.

**Comment by dokki767** [comment]
Digging through my IIS logs, I have confirmed my Add-PASAccount call is using v9 API's which could be related to the logon process not detecting what version the vault API is running as.  With the -skipversioncheck on new-passession, will the default parameterset on cmdlets use v10 or can I force inject that version # somewhere along the way?  In 10.3 land I was not using the -UseV9API switch.

2019-02-15 13:30:51 192.168.0.242 POST /PasswordVault/api/Auth/LDAP/Logon - 443 - 192.168.0.98 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+en-US)+WindowsPowerShell/5.1.14393.2636 - 200 0 0 2295
2019-02-15 13:30:52 192.168.0.242 GET /PasswordVault/WebServices/PIMServices.svc/Server - 443 - 192.168.0.98 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+en-US)+WindowsPowerShell/5.1.14393.2636 - 500 0 0 810
2019-02-15 13:30:52 192.168.0.242 POST /PasswordVault/WebServices/PIMServices.svc/Account - 443 - 192.168.0.98 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+en-US)+WindowsPowerShell/5.1.14393.2636 - 404 0 0 25
2019-02-15 13:30:52 192.168.0.242 POST /PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logoff - 443 - 192.168.0.98 Mozilla/5.0+(Windows+NT;+Windows+NT+10.0;+en-US)+WindowsPowerShell/5.1.14393.2636 - 404 0 0 31

**Comment by pspete** [comment]
If you use these parameters, the request will go to the V10 URL:

````powershell
SYNTAX
    Add-PASAccount [-name <String>] [-address <String>] [-userName <String>] -platformID <String> -SafeName <String>
    [-secretType <String>] [-secret <SecureString>] [-platformAccountProperties <Hashtable>]
    [-automaticManagementEnabled <Boolean>] [-manualManagementReason <String>] [-remoteMachines <String>]
    [-accessRestrictedToRemoteMachines <Boolean>] -sessionToken <Hashtable> [-WebSession <WebRequestSession>] -BaseURI
    <String> [-PVWAAppName <String>] [-ExternalVersion <Version>] [<CommonParameters>]
````

The logoff issue is now fixed in the [issue-133 Branch](https://github.com/pspete/psPAS/tree/issue-133) too..... will get it merged into master and on the gallery soon.

**Comment by dokki767** [comment]
I was just looking at what the differences were, good call.  I do need to update a few parameter names.  Thanks for the quick responses and fix.

**Comment by pspete** [comment]
@dokki767 - fix for `Close-PASSession` now published.
Do you still need the issue open for the usage of `Add-PASAccount`?

**Comment by dokki767** [comment]
No, I think with modifying my code base to be 10.4 parameter set compliant should do the trick.  I'll open another issue if necessary but I should be fine.
