### ISSUE TITLE
Create function for automating the move account process

### ISSUE THREAD

**Issue by infamousjoeg** [pspete/psPAS#14]
Basically, it'd be a function to do the following:

Get-PASAccount - Store metadata in PSObject
Add-PASAccount - Using metadata in PSObject; add to new safe
Get-PASAccount - To ensure the account was moved properly
Remove-PASAccount - Remove account from old safe

Parameters:  $originalSafe, $destinationSafe, whatever else you need

That way, you get the account's metadata, add the account to the new safe, verify move, remove old account in old safe.

**_DISCLAIMER:  You'll lose all the account's audit data once it is removed.  Be aware of your enterprise's audit requirements!_**

**Comment by pspete** [comment]
I've been testing this out, and just published a related update to Add-PASAccount....

The following command:
`$token | Get-PASAccount -Keywords "<SourceAccount>" -Safe <source_safe> | Add-PASAccount -safe <Dest_Safe> -password $(ConvertTo-SecureString -AsPlainText -Force $($token | Get-PASAccountCredentials -AccountID <Source Account ID> |  Select -ExpandProperty Password))`

Adds a new account to an arbitrary "destination safe", using the properties & password of a "Source Account".

However, adding accounts via the REST API requires any "additional" properties (timeout/DSN/etc) to be provided as a list/hashtable assigned to the "dynamicProperties" parameter - so anything other than the base parameters do not get set on the account.

A second stage execution of:
`$token | Get-PASAccount -Keywords "<SourceAccount>" -Safe <source_safe> | Set-PASAccount -AccountID <Destination Account ID>`

_should_ copy over all properties of the source account to the destination account.....

Another thing to note: as well as losing any audit data, the Extrapass_X_ (Logon/Reconcile account) details are not present in the Get-PASAccount output, so do not get set on the new account - I assume not an issue if set via platform/policy.

**Comment by infamousjoeg** [comment]
I'm not closing this issue because I'm referring customers to here anytime I'm asked about a "Move Accounts" method in our REST API.

**Comment by pspete** [comment]
no problem @infamousjoeg - I've left it also; the procedure above isn't a true "move", but, copy/clone config (or properties) from one account to another,  which could, I think,  be included as a method on account objects - so looking into how that might work....

**Comment by pspete** [comment]
I have implemented a ScriptMethod which is now present on all results returned from Get-PASAccount; *CopyToSafe()*.

In the below scenario

    $account = $token | Get-PASAccount SourceAcct -Safe Src_Safe

The *CopyToSafe()* method will be available on `$account`.

The following command:

    $account.CopyToSafe("DestinationSafe")
Will complete the process [outlined above](https://github.com/pspete/psPAS/issues/14#issuecomment-320960870):

 - Using the basic properties & password value of "*SourceAcct*"
	 - Create a new account in "*DestinationSafe*"
	 - Perform a subsequent setting/copy of additional properties from "SourceAcct" onto the new account.

The caveat of this approach is that, until the API is not limited to returning a single account on Get operations, if multiple accounts with the same username exist in the destination safe, an incorrect account may be targeted.

**Comment by jbalcorn** [comment]
Is there any equivalent to this for the v10 interface?

**Comment by pspete** [comment]
@jbalcorn - you mean to copy a the details of an account using the v10 API?

**Comment by jbalcorn** [comment]
Yes!  Actually move, but I can copy and delete.  Been trying to solve it,
the code in Issue #14 doesn't work, and I keep running into odd problems.
-- 
Justin B. Alcorn
The views expressed are not necessarily my own, much less anyone else's
PGP Fingerprint CCEB F776 C3FD 1050 C8DB  532E B8B9 BED7 7764 406C

**Comment by pspete** [comment]
Copy/delete is the only option.
A basic copy example:

```powershell
#Get properties of Source Account
$Account = Get-PASAccount -id $ID
#Get the current password
$AccountPassword = (Get-PASAccountPassword -id $ID).ToSecureString()
#Get Account properties into the right format 
$Properties = @{}
$Account.platformAccountProperties.psobject.properties | Foreach { 
    $Properties[$_.Name] = $_.Value 
}
#Copy Account to a destination
$Account | Add-PASAccount -platformAccountProperties $Properties -SafeName TargetSafe -secret $AccountPassword
```
