### ISSUE TITLE
Import-PASConnectionComponent uploads Dispatcher file?

### ISSUE THREAD

**Issue by chyuen94** [pspete/psPAS#140]
Hi,

I was wondering if the following function actually uploads the PSM dispatcher file.

I see the connection component created in PVWA but I don't see the actual dispatcher file uploaded. Do you have to manually upload it to the PSM component directory?

Thanks,
Cliff

**Comment by pspete** [comment]
To deploy a PSM Connector i believe the options are manual copy to the server, or create a universal connector package and deploy it to the server via the PSMUniversalConnectors safe.

**Comment by chyuen94** [comment]
Thanks Pete! I was hoping for an automatic way to import everything required for the connection component. Hopefully CyberArk in the future will create a way to import a PSM connector through PVWA the same way you would import a platform
