### ISSUE TITLE
Expose -TimeoutSec to functions

### ISSUE THREAD

**Issue by steveredden** [pspete/psPAS#142]
## Your Environment

* PowerShell Version: 5
* psPAS Branch & Version: latest
* CyberArk Version: 10.5

## Expected Behaviour

Allow Invoke-PASRestMethod to accept Invoke-WebRequest's -TimeoutSec parameter

## Current Behaviour

Can't pass through a -TimeoutSec so [some] default (says 0/indefinite but not observing that), is being chosen and my Safe queries time out.

## Possible Solution

Expose -TimeoutSec to public+private functions that eventually hit Invoke-WebRequest in Invoke-PASRestMethod

## Steps to Reproduce (for bug reports)

1 .  Have thousands of safes

2 . Try to Get-PASSafe

3 . Observe timeout

4 .  Run the same manual query using Invoke-WebRequest and a high -TimeoutSec

5 . Profit!

## Sample Output

N/A

## Context

N/A

**Comment by pspete** [comment]
Thanks for another contribution @steveredden .
Will look into implementing.

**Comment by steveredden** [comment]
Should be quite simple with your use of PSBoundParams.  I'd imagine Get-PASSafe and Get-PASAccount would have the biggest bang.

**Comment by pspete** [comment]
Would a global timeout setting work? Or would the timeout need to be "tunable" for different queries/requests/functions?
