### ISSUE TITLE
Add-PASSafeMembers Failing with 403 when using Domain Security Group

### ISSUE THREAD

**Issue by allenrg967** [pspete/psPAS#143]
* PowerShell Version: 5.1
* psPAS Branch & Version: 2.3.6
* CyberArk Version: 10.7

$session is already established and Get-PASSafeMember to the same safe works.
$safeName is 'TestSafe'
$domain is 'corp.domain.com'
Domain Security Group is available in Domain

Command Run:
PS C:\> $session | Add-PASSafeMember -SafeName $safeName -MemberName "CArk_$safeName-Managers" -SearchIn $domain -ListAccounts $true -ViewAuditLog $true -ViewSafeMembers $true -RequestsAuthorizationLevel 1

## Expected Behaviour

No screen output and the AD group CArk_TestSafe-Managers is added as a Safe Member with ListAccounts, ViewAuditLog, ViewSafeMembers and AuthorizationLevel of 1.

## Current Behaviour

The following error appears
Invoke-PASRestMethod : [403] 
At \\<module location> \WindowsPowerShell\Modules\psPAS\2.3.6\Functions\SafeMembers\Add-PASSafeMember.ps1:396 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod

I am attempting to assign Domain AD Security Groups with specific permissions to new safes so that we can automate the creation of Safes.

**Comment by pspete** [comment]
The 403 likely relates to the group. 
Can you add the same group to a safe manually?
Can you get the group details with `Get-PASGroup`?

**Comment by allenrg967** [comment]
Can you add the same group to a safe manually? Yes, adding manually works.
Can you get the group details with Get-PASGroup? Yes.
PS C:\> $session | Get-PASGroup -search "Cark_TestRob-Managers"
id   groupName             groupType location
--   ---------             --------- --------
2008 CArk_TestSafe-Managers Directory \ABC

**Comment by allenrg967** [comment]
I found that this error occurred in Visual Studio Code, but not while running the script in a native PS window.  Not sure why the difference, but this can be considered closed.
