### ISSUE TITLE
Account Level Permission

### ISSUE THREAD

**Issue by greatshuffle** [pspete/psPAS#147]
Terribly sorry if I'm missing something. We have a safe setup where users are added to the safe with no safe-wide permissions, then the "use" and "retrieve" are set on the privileged accounts individually  via the 'permissions' tab on the priv-user in cyberark (not all members of the safe have access to the same privileged creds inside the safe) 

Is there a way to do this with this module? Seems like the permissions are all managed safe level in these functions

**Comment by pspete** [comment]
Apologies @greatshuffle - I am not aware of any way to automate that configuration.

**Comment by greatshuffle** [comment]
no worries, just appreciate the response :)
