### ISSUE TITLE
Set-PASSafe - Does not seem to support safe renaming

### ISSUE THREAD

**Issue by kevinelwell** [pspete/psPAS#148]
## Your Environment

* PowerShell Version: 5.1.14409.1005
* psPAS Branch & Version: 2.4.8
* CyberArk Version: 10.5

## Expected Behaviour

Expecting Set-PASSafe to be able to rename the safe

## Current Behaviour

During user de-provisioning, we rename the safe to DELETE-<Partial Safe Name>
Rather than have to login to the PVWA to perform this step, i'd like this to be available within the Set-PASSafe function.

The REST API supports renaming a safe using the Update Safe method.

## Steps to Reproduce (for bug reports)

1 . Functionality does not seem to currently exist

2 .

3 .

4 .

## Context

My goal is fully automate the user de-provisioning process.

**Comment by pspete** [comment]
@kevinelwell - you are right, I did originally miss this.
The good news is I updated the module and included this feature in version 2.5.0.
If you update to the latest version of the module you should be good to go.

**Comment by kevinelwell** [comment]
Thank you very much!

**Comment by kevinelwell** [comment]
Fatanstic Sir! I see the new functionality.
