### ISSUE TITLE
Add-PASApplication throws ParameterBingingValidationException

### ISSUE THREAD

**Issue by tsherwin** [pspete/psPAS#149]
## Your Environment

* PowerShell Version: 4.0
* psPAS Branch & Version: 2.2.2 Main
* CyberArk Version: 9.10

## Expected Behaviour

Create AIM application via Add-PasApplication, with all attributes, including BusinessOwnerPhone

## Current Behaviour

Successfully added in all cases, except where BusinessOwnerPhone is specified as part of the command (below)

$appOwnerPhone = Read-Host "Enter Application Owner Phone"

 ..... -BusinessOwnerFName $appOwnerFirst -BusinessOwnerLName $appOwnerLast -BusinessOwnerEmail $appOwnerEmail -BusinessOwnerPhone $appOwnerPhone .....

Add-PASApplication : Cannot validate argument on parameter 'BusinessOwnerPhone'. The ValidateLength attribute cannot be applied to a parameter that is not a string or string[] parameter. Make the parameter a string 
or string[] parameter.
At line:1 char:224
+ ... nessOwnerPhone $appOwnerPhone -ErrorAction Stop
+                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PASApplication], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Add-PASApplication
 

## Possible Solution

BusinessOwnerPhone is noted as INT32, however error indicates it is expecting a string.
Given that a manual update of the phone entry in UI accepts any character, is this actually INT?

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
The error reads like you just have to cast the variable add the expected type. The number may be being assumed to be an integer? Can you try the following: 

````powershell

[String]$appOwnerPhone = Read-Host "Enter Application Owner Phone"

````

**Comment by pspete** [comment]
@tsherwin will look into this

**Comment by tsherwin** [comment]
Fis is confirmed.  Thank you very much!!

**Comment by pspete** [comment]
no problem - I re checked the documentation and confirmed the the correct parameter type.... you are the first person to notice the mistake :-)
