### ISSUE TITLE
Account Comment Property Missing

### ISSUE THREAD

**Issue by jdkang** [pspete/psPAS#151]
## Your Environment

* PowerShell Version: 5.1
* psPAS Branch & Version: 2.5.6
* CyberArk Version: 10.6.0 (10.6.0.23)

## Expected Behaviour
`Get-PASAccount` would contain a 'comments' property.

## Current Behaviour
`Get-PASAccount` does not contain a 'comments' property

## Possible Solution
Unclear

## Steps to Reproduce (for bug reports)
1. Use `Get-PASAccount` on an account object with a comment.
2. Inspect object

## Sample Output
n/a

## Context
Get an account's comment field.

**Comment by pspete** [comment]
Hi @jdkang 

I cannot reproduce the described issue.
After configuring a property called `comment` on a platform, the value is returned when querying the account:

````powershell

C:\Users\petem> $token | Get-PASAccount -search flmbhywo | 
Select-Object -ExpandProperty platformAccountProperties | Select-Object comment

Comment    
-------    
SomeComment



C:\Users\petem> $token | Get-PASAccount -search flmbhywo


AccountID                 : 284_4
Safe                      : 1_XYZ_001_NZL
address                   : SOMEDOMAIN.COM
userName                  : flmbhywo
name                      : Z_WINDOMAIN_OFF1-SOMEDOMAIN.COM-flmbhywo
platformId                : Z_WINDOMAIN_OFF1
secretType                : password
platformAccountProperties : @{LogonDomain=SOMEDOMAIN; Comment=SomeComment}
secretManagement          : @{automaticManagementEnabled=True; lastModifiedTime=1556548796}
createdTime               : 29/04/2019 14:39:56

````

**Comment by pspete** [comment]
@jdkang - as the issue cannot be reproduced, the issue will be closed.
Feel free to add additional information.
