### ISSUE TITLE
Guru Meditation - HTML Response Received

### ISSUE THREAD

**Issue by 27560** [pspete/psPAS#155]
What would cause a Guru Meditation - HTML Response Received error?

**Comment by pspete** [comment]
When retrieving a password (`Get-PASAccountPassword`), the response can be a string, returned as type `text/html`.
An exception needed to be handled where a response of content type `text/html` is received, but is actually HTML (i.e. has `<html>` tags, and is intended to be rendered in a browser), and not a simple text string. It is in this scenario you would see this exception.
