### ISSUE TITLE
Get-PASSafemember fails for user PVWAGWAccounts

### ISSUE THREAD

**Issue by kruhmann** [pspete/psPAS#156]
Hi @pspete,

when I run Get-PASSafeMembers on a safe with the owner PVWAGWAccounts
```powershell
$token | Get-PASSafeMembers -SafeName "Notification Engine" -MemberName PVWAGWAccounts
```
the request fails with:

```powershell
Invoke-PASRestMethod : [404] Failed to update User or Group PVWAGWAccounts. Reason: User or Group was not found.
At line:151 char:13
+         $result = Invoke-PASRestMethod @Request
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod
```

For other users (Master, Batch..) the command works. I am using:
* PowerShell Version: 5
* psPAS Branch & Version: last
* CyberArk Version: 10.5 and 10.8

Have you seen this error before?

Kind regards
Konstantin

**Comment by pspete** [comment]
Hi Konstantin,

I am fairly sure it is not possible to add PVWAGWAccounts as a safe member due to the user type.
What are you trying to achieve? Any safe not shared with PVWAGWAccounts will not be accessible via PVWA or REST API.

**Comment by kruhmann** [comment]
Hi Pete,

the error message is kind of curious. Get member information for the owner PVWAGWAccounts should not raise an update error. 

I stumbled over this comment in Get-PASSafeMember.ps1:
> If a Safe Member Name is provided, the full permissions of the member on the Safe will be returned.
Includes AccessWithoutConfirmation, InitiateCPMAccountManagementOperations, RequestsAuthorizationLevel & SpecifyNextAccountContent which are not included when querying by safe only.

Therefore I tried to iterate over all owners for a safe to get the full permissions. If works except for PVWAGWAccounts. It is a unexpected error and that's why I would like know if this error is by design and maybe other have the same behavior. It works even when the switch MemberName is not provided.

Kind regards
Konstantin

**Comment by pspete** [comment]
So,

> If a Safe Member Name is provided, the full permissions of the member on the Safe will be returned........

This is a relatively new update to psPAS. A normal `GET` request for safe members will not show the `AccessWithoutConfirmation, InitiateCPMAccountManagementOperations, RequestsAuthorizationLevel & SpecifyNextAccountContent` permissions.
To show the missing permissions, an empty `PUT` (update) request has to be sent for the individual member.
Because adding/updating/removing PVWAGWAccounts is not be possible via PVWA or REST, this is likely the reason for the error as it is not a supported operation for PVWAGWAccounts.
