### ISSUE TITLE
Cannot find type [psPAS.CyberArk.Vault.Account] after load-module

### ISSUE THREAD

**Issue by tstaddon** [pspete/psPAS#159]
## Your Environment

Tried on two different machines, Windows Server 2016 Standard, and Windows 10.

* PowerShell Version: 5.1.14393.2969 (desktop edition on Server 2016), 5.1.17134.590 (Win10)
* psPAS Branch & Version: 2.6.15
* CyberArk Version:

## Expected Behaviour

Should be able to reference psPAS custom objects after loading the module.

## Current Behaviour

Import-Module  with verbose confirms Loading 'typestoProcess' from path '........\ps1xml'.

All subsequent references to psPAS.CyberArk.Vault.Account objects fail, e.g. with New-Object the error is

"Cannot find type [psPAS.CyberArk.Vault.Account]: verify that the assembly containing this type is loaded.

And with [psPAS.CyberArk.Vault.Account].$var =  .... commands the error is

"Unable to find type [psPAS.CyberArk.Vault.Account].

## Steps to Reproduce (for bug reports)

Unit test script would take too long to sanitise but it contains:

` Import-Module -name "psPAS" -force -verbose

` $token = New-PASSession -Credential $testcred -type RADIUS  -BaseURI $global:constBaseURI  -verbose -erroraction stop

` [psPAS.CyberArk.Vault.Account]$objServiceAccount = $token | Get-PASUser -Keywords $strServiceAccount -Safe $constSafeName  -limit 1

The last line fails because the object type cannot be resolved.

**Comment by pspete** [comment]
Am not clear on why you have the need to strongly type `[psPAS.CyberArk.Vault.Account]`?

`Get-PASUser` (from your last line), should result in an object of type `psPAS.CyberArk.Vault.User.Extended` (not `psPAS.CyberArk.Vault.Account`).

````powershell
> $token | Get-PASUser | Get-Member | select TypeName | select -Unique

TypeName
--------
psPAS.CyberArk.Vault.User.Extended
````

When creating a custom object in PowerShell, you can give it any type name you like:

````powershell
$example = [pscustomobject]@{
     PSTypeName = 'Example'  
 }

$example | Get-Member


   TypeName: Example

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
````

But attempting to cast a variable to a made up type will raise an error:

````powershell
[example]$example
Unable to find type [example].
At line:1 char:2
+ [example]$example
+  ~~~~~~~
    + CategoryInfo          : InvalidOperation: (example:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
````

`psPAS` does return objects of custom types; the _FormatsToProcess_ & _TypesToProcess_ just contain formatting rules and custom methods for the objects which are returned.

````powershell
$token | Get-PASAccount | Get-Member | select TypeName | select -Unique

TypeName
--------
psPAS.CyberArk.Vault.Account.V10
````

**Comment by tstaddon** [comment]
Hi Pete,

I only tried strong typing because even this threw the error:

$objServiceAccount = $token | get-PASAccount -keywords xxx -safe xxx

Still throws the error. However, I think I have a smoking gun of sorts...

The machines that are throwing this error are grinding to a halt, with Windows Installer modules going into overtime. So I think some background update is messing with my unit tests!

On another machine with the exact same code (i.e. without the explicit types) the CPU utilisation has just dropped, and the account and credential requests are both working - but it's throwing errors at the -expandProperty step.

Go figure...

**Comment by pspete** [comment]
Unfortunately, not something I can reproduce
![image](https://user-images.githubusercontent.com/10600090/58711752-ffc68e80-83b6-11e9-86da-fd08ce23c61f.png)

**Comment by tstaddon** [comment]
Hi

I think this can be closed - after testing it again today (rebooting machines after software installation) it's working consistently so the issue must've been related to Windows Installer actions in the background.
