### ISSUE TITLE
ExtraPass properties

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#168]
Hello
I have a question. Is there a way to get ExtraPass properties values? 
I do not see them when using Get-PASAccount
I know that these can be updated with Set command,

I need to update these values on the accounts where ExtraPass3Safe is specific safe.

**Comment by pspete** [comment]
Hi @olegasdo - i do see the ExtraPass properties using `Get-PASAccount`.
You might need to define them as optional properties on your platform to be able to query them with the api.

**Comment by olegasdo** [comment]
I probably doing something wrong then :)

![get-pasaccount](https://user-images.githubusercontent.com/28575457/59819811-2763a380-9332-11e9-94c0-81c038a7aa5f.PNG)

![get-pasaccount-by-id](https://user-images.githubusercontent.com/28575457/59819831-35192900-9332-11e9-9614-bd1876bc7aaa.PNG)

However in account settings I can see them

![account_details](https://user-images.githubusercontent.com/28575457/59819842-3f3b2780-9332-11e9-910d-a7453deb0385.PNG)


> You might need to define them as optional properties on your platform to be able to query them with the api.

You mean I need to specify them explicitly as Optional in Platform properties even if they already exist?

**Comment by olegasdo** [comment]
I've added these settings as optional in platform settings and I was able to retrieve them, 
Thank you, @pspete
