### ISSUE TITLE
Q's for author

### ISSUE THREAD

**Issue by AaronG1234** [pspete/psPAS#171]
Get-PASAccount -filter
    what are the possibilities here... "SafeName eq XXXX" works, but what about platformID, or other column (like status) ... I tried a few ideas.. no hits.  Also what operators are available.. for instance is "LIKE" available or anything that can wild card (Safename like ZZZZ*) or Not Equal...etc.

GET-PASAccount (general)
   when Get-PASAccount -keyword returns "WARNING: 9 matching accounts found. Only the first result will be returned"  what options do i have to see the rest of them... (for instance what if i want those exact 9, maybe to do something like Remove-PASAccount)

**Comment by pspete** [comment]
For the `filter` parameter, `"SafeName eq XXXX"`is the only available option (at least according to the API documentation).
If you are using CyberArk 10.4+ - avoid using the `keywords` & `safe` parameters as these relate to the classic api which has the limit of only returning the first account found.
If you are using 10.3 or earlier, there is no option to return all accounts.

**Comment by pspete** [comment]
Let me know if you need this reopening @AaronG1234
