### ISSUE TITLE
Get-PASAccount does not return PlatformAccountProperties

### ISSUE THREAD

**Issue by gitshanif** [pspete/psPAS#184]
**Describe the issue**
**Get-PASAccount -search** does not return PlatformAccountProperties while using V10API
V9API returns internal properties with -keywords parameter but result just shown only the first result.

**To Reproduce**
1. Search an account using v10API, Get-PASAccount -search <accountname> where the account has **lastsuccessreconciliation** filecategory present
2. 
3. 

**Expected behavior**
The result has to show all the result where query matches. This would help us to perform bulk operation.

**Screenshots & Console Output**

Console Output Code Block:
```powershell


```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version: 3.0
* CyberArk Version: 10.4

**Additional context**

**Comment by pspete** [comment]
@gitshanif - from the information provided, could be related to #124 : https://github.com/pspete/psPAS/issues/90#issuecomment-474556624

**Comment by pspete** [comment]
@gitshanif - closing as this is external to psPAS and not something to be fixed in the module.
