### ISSUE TITLE
Safe Members - No RestrictedRetrieve and ListContent permissions?

### ISSUE THREAD

**Issue by Aurakal** [pspete/psPAS#185]
Disclaimer: GitHub refreshed the page and I lost the whole issue I had been working on for the last 15 mins. I'm currently typing with a broken finger and it isn't easy so sorry if this time I'm not going to follow the template.

Basically, there seems to be an issue with the SafeMembers commands.

If you add a member to a safe via the PVWA, and set the "Use accounts" and "List accounts" permissions, when you list that safe's members using Get-PASSafeMembers, these permissions are returned as "ListContent" and "RestrictedRetrieve". According to the API documentation, "UseAccounts" and "ListAccounts" should be returned instead, as these 2 other permissions don't exist.

Now, if you try to add a member to a safe using Add-PASSafeMember, and want the same permissions as the ones above, one would think that you have to use the "UseAccounts" and "ListAccounts" permissions. However, when you do so, it seems like the "RetrieveAccounts" permission is also applied out of nowhere.

Here's a screenshot of the Get-PASSafeMember output from a safe where the member was added via the PVWA with the "Use accounts" and "List accounts" permissions.
![image](https://user-images.githubusercontent.com/20073832/60905823-d7e30a00-a243-11e9-94ca-8d9ce46c01dd.png)

And here's a screenshot of the Add-PASSafeMember output from a safe where the member was added via the Add-PASSafeMember command with the "UseAccounts" and "ListAccounts" permissions.
![image](https://user-images.githubusercontent.com/20073832/60905813-d1549280-a243-11e9-9d94-2083ff1ea66a.png)

And if you use the Get-PASSafeMember command on that safe, you get this.
![image](https://user-images.githubusercontent.com/20073832/60905999-33ad9300-a244-11e9-96e6-ffa2da88c525.png)

PowerShell version: 5
psPAS version: 3.1.5
CyberArk version: 10.8

**Comment by pspete** [comment]
Hi @Aurakal - Thanks for all of the information.
For `Get-PASSafeMember`, the permission names are straight from the return data - it's just how they are reported from the API, there is information on the CyberArk support site regarding the names of the safe permissions when queried through different interfaces; `RestrictedRetrieve` is equal to `UseAccounts`. and `ListContent` is equal to `ListAccounts`.

For `Add-PASSafeMember`:
- would aliases on the parameters with different names help? 
  - So specifying `RestrictedRetrieve` would equate `UseAccounts` etc
- if the `-Debug` switch is added, the body of the request can be confirmed as being correct
  - when specifying `UseAccounts` and `ListAccounts` alone, `RetrieveAccounts` is not included:
![image](https://user-images.githubusercontent.com/10600090/60915366-92463180-a283-11e9-959d-7f3a778aff13.png)

  - if `-RetrieveAccounts $false` is specified the permission is not granted.
![image](https://user-images.githubusercontent.com/10600090/60915451-c9b4de00-a283-11e9-9da5-c4be9093193e.png)

I do not think that this is something any code change in the module will affect.

**Comment by Aurakal** [comment]
Hi Pete,

Aliases would definitely help to help reduce the confusion, because right now, since these permissions don't exist in psPAS (not defined), one may think that they can't be set/used.

Also, it might be worth documenting the fact that using "ListAccounts" with "UseAccounts" will results in the "RestrictedRetrieve" and "Retrieve" permissions being applied automatically as well. Unless this is documented on the API's docs, because this looks like an uncommon behavior (setting 2 permissions and ending up with 4 of them).

Thank you,

Aura

**Comment by pspete** [comment]
I'll consider the options for a future update, feel free to submit a PR.
Requiring a `$true`\\`$false` for each permission, rather than leaving it optional, would work also.

**Comment by Aurakal** [comment]
I think that requiring a $True/$False would just annoy users, as there's a lot of permissions and doing them everytime would probably take more time than necessary. I think that just adding some kind of disclaimer or note in the documentation for this behavior would be enough, so then people will be aware of it. Needless to say, it could be an issue on CyberArk's side too, I don't know if that permission combo should results in that output.
