### ISSUE TITLE
Set-pasaccount for dynamicproperties

### ISSUE THREAD

**Issue by fl0riandre** [pspete/psPAS#191]
**Is your feature request related to a problem? Please describe.**
Hello,
indeed i have a problem :)
i did a bulk creation for approximatively 4500 accounts with the dynamicproperties parameter.
We are using a custom platform, that's why i need to use this parameter.
Now i have to enforce some of these properties following an internal strategy / naming convention but i'm not able to find the right way to do it with the set-pasaccount cmdlet.

**Describe the solution you'd like**
i would like to pass a custom path parameter (e.g. /dynamicproperties/xxx) in order to replace these fields on specific accounts (finded by accountID)

**Describe alternatives you've considered**
Unfortunately i don't have any alternative.

**Comment by pspete** [comment]
Do the examples in the readme not work for you?
https://github.com/pspete/psPAS#update-accounts
https://github.com/pspete/psPAS#updating-multiple-properties-of-an-account

**Comment by fl0riandre** [comment]
Thank you for your quick reply!
No unfortunately, do you mean by defining a custom array in platformproperties path? No, this path is empty, and I create accounts with the dynamicproperties option of add-pas account (only way to make it work) hoping that I simply miss something. Have a nice day!!!

**Comment by pspete** [comment]
what CyberArk version is this for?

**Comment by fl0riandre** [comment]
10.5

**Comment by pspete** [comment]
for 10.5, the way documented in the readme is the way to do it.

````powershell
Set-PASAccount -AccountID $ID -op replace -path /platformAccountProperties/<DynamicPropertyName> -value <Value>
````

**Comment by fl0riandre** [comment]
Hello, yes thank you, that's exactly what I tried but unfortunately seems not to work for me, path not found... Indeed when I try to get-pasaccount, the platformaccountproperties hashtable is empty... Let me investigate further tomorrow and I will give you more details. Thank you again for your help and have a nice evening! Best regards.

**Comment by pspete** [comment]
OK - it would help if you can share more details, like an example of the command you used to add the accounts, what gets returned from get-pasaccount, as well as the optional/mandatory parameters configured on the platform.

**Comment by fl0riandre** [comment]
Hello pete,

finally find a solution (or maybe a workaround but functional)

in my case, it seems that the replace operation would not work as expected : (Reason: The target location specified by path segment 'Customer' was not found.)

PS U:\> Set-PASAccount -AccountID 184_180 -op replace -path /platformAccountProperties/Customer -value "CustomerName"
Invoke-PASRestMethod : [400] Invalid Input Request. Reason: The target location specified by path segment 'Customer' was not found.
At line:359 char:14
+ ...   $Result = Invoke-PASRestMethod -Uri $URI -Method $Method -Body $Bod ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"P...as not found."}:ErrorRecord) [Invoke-PASRestMethod], Exception
    + FullyQualifiedErrorId : PASWS164E,Invoke-PASRestMethod
 

But if i try the add operation, it return me a success and indeed the account is updated in the web interface with the right custom attribute :

PS U:\> Set-PASAccount -AccountID 184_180 -op add -path /platformAccountProperties/Customer -value "CustomerName"


AccountID        : 184_180
Safe             : Safename
address          : servername
userName         : admin
name             : Application-GenericPasswordonPHI-safename-2-servername-admin-test-machine
platformId       : GenericPasswordonPHI
secretType       : password
secretManagement : @{automaticManagementEnabled=True; lastModifiedTime=1563966832}
createdTime      : 24.07.2019 11:13:52

So, i don't know if my creation method was wrong but the issue can be fixed using this Set method.

BUT, i still have another "problem", i'm not able to get these platformacccountproperties...

PS U:\> Get-PASAccount -filter "safename eq safename" -search servername

AccountID                 : 184_180
Safe                      : safename
address                   : servername
userName                  : admin
name                      : Application-GenericPasswordonPHI-safename-2-servername-admin-test-machine
platformId                : GenericPasswordonPHI
secretType                : password
platformAccountProperties : 
secretManagement          : @{automaticManagementEnabled=True; lastModifiedTime=1563966832}
createdTime               : 24.07.2019 11:13:52

platformaccountproperties seems empty...

i see this issue : https://github.com/pspete/psPAS/issues/124
seems to be corrected but maybe i have a different problem (note that i use the last release of you module)

Thank you so much for your precious help.
Have a nice dayand best regards.

**Comment by pspete** [comment]
Can you try:

```powershell
Get-PASAccount -id 184_180 | Select-Object *
```
Curious to see if the details are included in the full output. 
You can see the expected `CustomerName` on the account in PVWA?

In regards to `Set-PASAccount`, if `add` works, but `replace` does not, it suggests that the `Customer` property is not set on the target account.

**Comment by fl0riandre** [comment]
Hello,

the command supplied return nothing more :
PS U:\> Get-PASAccount -id 184_180 | select-object *


id               : 184_180
name             : Application-safename-2-servername-admin-test-machine
address          : servername
userName         : admin
platformId       : GenericPasswordonPHI
safeName         : safename
secretType       : password
secretManagement : @{automaticManagementEnabled=True; lastModifiedTime=1563966832}
createdTime      : 1563966832

but indeed if i force to use the old API using keyword option for example, i can see the details :

PS U:\> Get-PASAccount -keywords servername | select-object *
WARNING: 5 matching accounts found. Only the first result will be returned


AccountID          : 184_180
InternalProperties : 
Safe               : safename
Folder             : Root
Name               : Application-GenericPasswordonPHI-safename-2-servername-admin-test-machine
Comment            : comment
Note               : test machine
UserName           : admin
PolicyID           : GenericPasswordonPHI
Category           : Machine : Server
Customer           : CustomerName
DeviceType         : Application
Address            : servername
Title              : servername

but there are some limitation using this option, indeed the most problematic is that it return only the first result...
Do you confirm that only "keyword" and "safe" parameter force usage of the classic api ?
is it possible to get an accountid option for this classic API ?

Thank you so much for your precious help.
Have a nice day.

**Comment by pspete** [comment]
The Classic API has a limitation of only returning 1 account - there is no way around it.

If I create a `Customer` filecategory, and add this to a platform, I am able to query/update the value through the V10 or Classic API:
![image](https://user-images.githubusercontent.com/10600090/61791337-9ccf0200-ae11-11e9-8675-062ef5416a5a.png)

**Comment by fl0riandre** [comment]
Thank you for your quick reply,
indeed as i said, on my side tha platformaccountProperties are shown by are empty :

```
PS U:\> Get-PASAccount -search servername

AccountID                 : 184_180
Safe                      : safename
address                   : servername
userName                  : admin
name                      : Application-GenericPasswordonPHI-safename-2-servername-admin-test-machine
platformId                : GenericPasswordonPHI
secretType                : password
platformAccountProperties : 
secretManagement          : @{automaticManagementEnabled=True; lastModifiedTime=1563966832}
createdTime               : 24.07.2019 11:13:52
```

That's why i ask if it's possible to get-pasacount through Classic API filtering on AccountID (which will return always a single account as a normal behavior)

Note that (in the previous comments) when i did successfully the "set-pasaccount add", there is no platformaccountProperties in the command return (different than you screenshot)
Probably i miss something but i don't understand what...

Thank you so much again and have a nice day!

**Comment by pspete** [comment]
You can test outside of psPAS to see if the properties get returned:
```powershell
$Session = Get-PASSession
Invoke-RestMethod -Method GET -UseBasicParsing -Uri "https://<PVWA>/PasswordVault/api/Accounts/184_180" -WebSession $Session.WebSession
```
If you do not see `platformAccountProperties` in the output, then there nothing which can be changed to fix this in the module :-\

**Comment by fl0riandre** [comment]
Hello,
Yes you are right, the result is the same, i will have to escalate this to the cyberark support...
Thank you so much for your precious help, you can definitively close this issue.
Have a nice day!! Best regards.

**Comment by pspete** [comment]
OK @fl0riandre - I hope you find a solution, bon chance!
