### ISSUE TITLE
README.md - Verification section - Add-PASUser is not a cmdlet in the module

### ISSUE THREAD

**Issue by wjhudson** [pspete/psPAS#192]
## Your Environment

* PowerShell Version: 
* psPAS Branch & Version:
* CyberArk Version:

## Current Behaviour

On your project page in your README.md under the Installation->Verification section, there is this example:
"Get detailed information on specific commands:
Get-Help Add-PASUser -Full
"

It seems that Add-PASUser is not a cmdlet in the module

## Possible Solution

Change the example to be:
"Get detailed information on specific commands:
Get-Help New-PASUser -Full
"

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
Good Spot @wjhudson - will get that updated & fixed, many thanks for letting me know.
