### ISSUE TITLE
Issue with New-PASSession

### ISSUE THREAD

**Issue by kdrumz23** [pspete/psPAS#194]
**Describe the issue**
We can not get a token from New-PASSession when on version 10.9

**To Reproduce**
1.  See the attached screenshots. I tried with variations with -PVWAAppName pv -UseClassicAPI -type CyberArk, with and without each.
2. 
3. 

**Expected behavior**
A token is acquired by a New-PASSession

**Screenshots & Console Output**
![error](https://user-images.githubusercontent.com/52937374/61900254-3d452500-aeeb-11e9-922a-4e4464f39775.png)
![error 2](https://user-images.githubusercontent.com/52937374/61900255-3d452500-aeeb-11e9-9e9a-eaf56916c600.png)

Console Output Code Block:
```powershell


```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.14393.2969  
* psPAS Version: 3.1.13
* CyberArk Version: 10.9.0.15

**Additional context**
We are using a local cyberark account to authenticate, therefore I tried with "-type CyberArk" and without. Thanks!

**Comment by infamousjoeg** [comment]
If you're blocking out the value of `-Credential`, I'm going to assume it was given plain-text.  This will be rejected.

You should create a PSCredential object and pass that via `-Credential` instead.

```powershell
$cred = Get-Credential
```

Alternative, you can use the `Get-Credential` command in-line:

```powershell
New-PASSession -Credential $(Get-Credential) -BaseURI https://pvwa.whatever.com -PVWAAppName pv
```

I'm assuming that your logon URL for the PVWA is something along the lines of `https://pvwa.whatever.com/pv` instead of `/PasswordVault` since you provide the `-PVWAAppName` as `pv` in both attempts in your screenshot.  If you do logon from `/PasswordVault`, you'll want to remove the `-PVWAAppName` argument.

**Comment by pspete** [comment]
@kdrumz23 - this is not normal, suspect an underlying configuration issue maybe causing issues.

You can check and see if you can authenticate from the swagger interface: `/PasswordVault/swagger/ui/index#!/Auth/Auth_Logon`

Double check IIS to see if any request verbs are blocked (GET, POST, DELETE, PUT & PATCH should be allowed) .
Try and determine if there is any issue with the PVWA SSL certificate or configuration or the ability to use TLS 1.2.

**Comment by kdrumz23** [comment]
@infamousjoeg the password was actually given as a pscredential object.

@pspete we were unable to find any verbs blocked in IIS. Also our load balancer address and individual web server both support TLS 1.2.

Additionally I tried using the swagger interface and I was able to authenticate. Any other thoughts on what I can try? Thanks!

**Comment by pspete** [comment]
Any update @kdrumz23 ?

**Comment by pspete** [comment]
Can you share `debug` & `verbose` output?
![image](https://user-images.githubusercontent.com/10600090/62056900-77c5ff00-b216-11e9-96e1-dde2586d1df5.png)

**Comment by pspete** [comment]
and also the result of authenticating outside of the module:

![image](https://user-images.githubusercontent.com/10600090/62057583-d344bc80-b217-11e9-9f1b-410ce57c8661.png)

**Comment by kdrumz23** [comment]
@pspete Here they are
![New-PASSession error](https://user-images.githubusercontent.com/52937374/62058938-44707980-b1f0-11e9-884a-b3bf691fe5e9.png)
![apiAuth](https://user-images.githubusercontent.com/52937374/62058939-44707980-b1f0-11e9-89f5-0088695478dd.png)

**Comment by pspete** [comment]
The 'text/html' response from invoke-restmethod is the issue, but it isn't something to be rectified in the module; it's likely specific to your environment.

**Comment by kdrumz23** [comment]
So how is module version 2.6.16 able to work to create the safes but when I upgrade the module to 3.1.13 it does not.. Because of that response?

**Comment by pspete** [comment]
> So how is module version 2.6.16 able to work to create the safes but when I upgrade the module to 3.1.13 it does not

This is the first time you mention a difference in behaviour between module versions. Mind Reading is not something I do....
Version 3.x of the module did introduce breaking changes, and the the authentication functions were all consolidated into `New-PASSession`.

But.... `invoke-restmethod` is returning a html response (not psPAS) - has your environment changed at all?

**Comment by kdrumz23** [comment]
I somehow forgot to mention that the module upgrade is when we started noticing this problem - sorry for any confusion.  We did recently upgrade our cyber ark version from 9.x to 10.9. I'll take a look at New-PASSession in the meantime to continue troubleshooting. Thanks!

**Comment by pspete** [comment]
@kdrumz23 - for reference, this is what i see between the psPAS versions you mentioned, and the native Powershell command:

### psPAS 2.6.15
After authentication, the logon token details are returned to the session
![image](https://user-images.githubusercontent.com/10600090/62073879-8245c000-b239-11e9-8721-75098bd63662.png)

### psPAS 3.1.13
After authentication logon token details are saved to the module scope
![image](https://user-images.githubusercontent.com/10600090/62073984-b9b46c80-b239-11e9-8367-18c7b5c6faa3.png)

### Invoke-RestMethod
Authentication token output to the console
![image](https://user-images.githubusercontent.com/10600090/62074164-08fa9d00-b23a-11e9-8103-9571ed4cb81b.png)

**Comment by pspete** [comment]
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Troubleshooting.htm

**Comment by kdrumz23** [comment]
@pspete I think that's our issue. How can I get the session token back in the powershell session so I don't have to refactor some code? What should be in the $body parameter?

**Comment by kdrumz23** [comment]
We figured this out - thanks for the help!
