### ISSUE TITLE
RADIUS auth doesn't work for challenge/response

### ISSUE THREAD

**Issue by permster** [pspete/psPAS#195]
**Describe the issue**
When using RADIUS auth with a challenge/response the New-PASSession cmdlet doesn't work.  The -OTP switch doesn't work or apply for this type of RADIUS auth.  In this situation if you give New-PASSession the RADIUS token it returns an error "[500] Enter Windows Password:".  Which isn't really an error at all.  It just wants you to do another invoke-webrequest with the original session but this time passing the LDAP password.

**To Reproduce**
1. RADIUS auth configured for token and then LDAP auth.
2. $Credentials = Get-Credential
3. For the password use the RADIUS token.
4. $session = New-PASSession -Credential $Credentials -BaseURI $pvwa_url -type RADIUS

**Expected behavior**
I've done some testing with manual Invoke-WebRequest and what needs to happen here is New-PASSession needs to catch the error code for "Enter Windows Password".  Save the session as a variable which it already does.  Then allow to pass the session variable back for a second New-PASSession call with the LDAP password. (see example code below)

**Screenshots & Console Output**

Console Output Code Block:
```powershell


```

**Your Environment**
Include relevant details about your environment

* PowerShell Version:  5.1
* psPAS Version:  3.1.13
* CyberArk Version: 10.8

**Additional context**
Some example code which shows a working auth workflow for this type of RADIUS auth with challenge/response.

````powershell
#Hashtable to hold Logon Request
$LogonRequest = @{}

#Define Logon Request Parameters
$LogonRequest["Method"] = "POST"
$LogonRequest["Uri"] = "https://cyberarkpvwa/PasswordVault/api/Auth/RADIUS/Logon"
$LogonRequest["Body"] = @{
    username = "<user_name>"
    password = "<radius_token>"
}

#Send Logon Request
$PASSession = Invoke-WebRequest @LogonRequest -SessionVariable "PASSession" -EA SilentlyContinue

#If Logon Result
If ($PASSession) {
    $LogonRequest["Body"].password = "<LDAP_password>"
    $PASSession = Invoke-WebRequest @LogonRequest -WebSession $PASSession
    write-host $PASSession.Content
} else {
    write-host $Error
}
````

**Comment by permster** [comment]
I should note that in our situation it's RADIUS token first and then LDAP password but it could be flipped for others.  Where it asks for LDAP password first and then RADIUS token.

**Comment by pspete** [comment]
psPAS implements support for the appending of a OTP as described in the Duo documentation for CyberArk configuration: https://duo.com/docs/cyberark#test-your-setup
The OTP will be sent with the password in a single request; while the the [existing documentation](https://github.com/pspete/psPAS#radius-authentication-with-otp-if-supported) states the feature may not be supported, additional details to clarify that Duo must be configured with `radius_server_auto` and not `radius_server_challenge` are required to be added: https://duo.com/docs/authproxy-reference#radius-auto

Confirm if your RADIUS configuration supports "append mode": https://guide.duo.com/append-mode, and reconfigure as necessary.

If you are considering developing code & submitting a PR for the feature you have described,  ensure existing authentication flows for RADIUS (no OTP/Append OTP) will still function as expected.

**Comment by permster** [comment]
I'm having a hard time finding "append mode" when looking at other RADIUS providers.  Also, is the "<password>,<token>" format a standard?  Do other RADIUS solutions support the things you listed?

I think your note about changing to auto from challenge actually explains why this isn't working the same.  In our case the RADIUS is configured for challenge/response.  The example code I provided allows for compatibility with that configuration using Invoke-WebRequest.

I'll take a look at your code as I'm not sure how easy it will be to integrate this.  I may also be in the minority here and I'm not sure how many people would benefit from it.  I may just wrap up my example code into a function.

**Comment by pspete** [comment]
It may well be specific to Duo, but I had a few requests to implement support for it and was able to do so without breaking other authentication flows.

**Comment by infamousjoeg** [comment]
> I'm having a hard time finding "append mode" when looking at other RADIUS providers. Also, is the "<pass_word>,<RADIUS_token>" format a standard? Do other RADIUS solutions support the things you listed?
> 
> I think your note about changing to auto from challenge actually explains why this isn't working the same. In our case the RADIUS is configured for challenge/response. The example code I provided allows for compatibility with that configuration using Invoke-WebRequest.
> 
> I'll take a look at your code as I'm not sure how easy it will be to integrate this. I may also be in the minority here and I'm not sure how many people would benefit from it. I may just wrap up my example code into a function.

I've received a request for this more time than I can count.  You would be doing the community a service by contributing.

**Comment by permster** [comment]
I'm still working on this but it's taking a bit longer than I thought because the reply-message sent back during a RADIUS challenge differs.  I believe it will always be a 500 error but the reply-message isn't the same.  For me the message is "Enter Windows Password:" but it can and likely will be different for others RADIUS solutions.

**Comment by pspete** [comment]
@permster - I got a RADIUS server configured for challenge/response, and am so far unable to authenticate using the code in PR #200 

The error code returned on authentication failure (due to requirement for OTP reponse) is ITATS542I - current thinking is it would be a simpler/cleaner approach to catch this specific error. Can you confirm that this is the error code you see returned from the API too?

**Comment by pspete** [comment]
@permster - can you try the functionality now present in the [feature_radius_challenge](https://github.com/pspete/psPAS/tree/feature_radius_challenge) branch?

The command syntax for your scenario (OTP first, password as challenge response) would be:

```powershell
New-PASSession -Credential $cred -type RADIUS -BaseURI $url -OTPMode Challenge -OTP 123456 -RadiusChallenge Password
```

With `Verbose` on, you should see 2 authentication requests being sent:
![image](https://user-images.githubusercontent.com/10600090/63937091-8e4fb800-ca59-11e9-863b-c8ec22885f74.png)

**Comment by infamousjoeg** [comment]
@pspete We're testing this internally now.  Will update you here shortly...

**Comment by permster** [comment]
Appears to be working in my scenario with OTP first then password challenge.  I'll keep testing a bit but looks good so far.  Awesome job! 👍

**Comment by infamousjoeg** [comment]
Tested using DUO Challenge/Response (LDAP Password then OTP) and it worked successfully!  Thanks @pspete!!!
