### ISSUE TITLE
Documentation - Readme Update Required

### ISSUE THREAD

**Issue by shewards** [pspete/psPAS#197]
Readme lists PAS 9.7 required for user functions, like Get-PASUser, but module requires 10.9.

**Comment by pspete** [comment]
Thanks for the report. 
Get-PASUser was initially written to support the api functionality of 9.7 (classic api)
Additional api functionality was introduced in 10.9, and the function was updated to support this. 
Either the v10 or classic api can be targeted,  depending on the version in use.

**Comment by pspete** [comment]
Closing this as the readme already states that "The CyberArk Version listed is the minimum required to use the function."
`Get-PASUser` has been in the module for over 2 years already, long before 10.9 was released.
