### ISSUE TITLE
TicketingSystem instead of TicketingSystemName for GetPassword API request

### ISSUE THREAD

**Issue by aglerj** [pspete/psPAS#199]
**Describe the issue**
Using GetPassword API, I think it's a typo or needs updated... it should be "TicketingSystem" instead of "TicketingSystemName".

**To Reproduce**
1. Utilize the GetPassword API with a ticket integration
2. Use "TicketingSystemName", fails saying no ticketing integrations or such are configured (not the case.. I'm using the correct name and it's configured.
3. Change your api request to utilize "TicketingSystem". You're now able to use your ticket information and pull the password.

**Expected behavior**
Should work as is, however doesn't until you change "TicketingSystemName" to "TicketingSystem" when performing the requests.

**Screenshots & Console Output**
n/a

Console Output Code Block:
n/a

**Comment by pspete** [comment]
Thanks for the report @aglerj - will get this corrected.
