### ISSUE TITLE
Add-PASSafeMember do not add AD group with a &-sign in the name

### ISSUE THREAD

**Issue by KimChr** [pspete/psPAS#210]
**Describe the issue**
If an AD groups has a &-sign (AmbersAnd) in the name, it fails to add the Group to safe.
The group can be added via PVWA without any problems.

**To Reproduce**
1. Add-PASSafeMember -SafeName "MySafe" -SearchIn "MyAD" -MemberName "This & That" @Rights

**Expected behavior**
AD group "This & That" added as member of the Safe.

**Screenshots & Console Output**
[404] Failed to add User or Group This & That. Reason: Input parameter for [MemberName] value is invalid.

DEBUG: [Body] {
    "member":  {
                   "MemberName":  "This \u0026 That",
                   "Permissions":  [
                                       {
                                           "Key":  "BackupSafe",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "DeleteAccounts",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "ViewAuditLog",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "DeleteFolders",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "SpecifyNextAccountContent",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "UseAccounts",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "CreateFolders",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "ViewSafeMembers",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "UpdateAccountContent",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "AccessWithoutConfirmation",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "MoveAccountsAndFolders",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "UnlockAccounts",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "ListAccounts",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "ManageSafe",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "InitiateCPMAccountManagementOperations",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "RetrieveAccounts",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "ManageSafeMembers",
                                           "Value":  false
                                       },
                                       {
                                           "Key":  "RenameAccounts",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "RequestsAuthorizationLevel",
                                           "Value":  0
                                       },
                                       {
                                           "Key":  "UpdateAccountProperties",
                                           "Value":  true
                                       },
                                       {
                                           "Key":  "AddAccounts",
                                           "Value":  true
                                       }
                                   ],
                   "SearchIn":  "MyAD"
               }
}

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.0
* psPAS Version: 3.2.30
* CyberArk Version: 10.8

**Additional context**

**Comment by pspete** [comment]
Thanks for the report.

Ampersand is a forbidden character for MemberName [according to the API documentation](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Add%20Safe%20Member.htm).

Will update the parameter validation for `MemberName` in `Add-PASSafeMember`

**Comment by KimChr** [comment]
Hi Pete,

Thank you for looking at this problem.
It is correct that the API documentation states that Amperand is forbidden, but it is only in the URL.
The MemberName is in the Body... shouldn't  it then be possible?

Regards,
Kim

**Comment by pspete** [comment]
I don't think so... the wording is quite clear: 
Vault or Domain user or group to add as a Safe member.
Note: The MemberName must not contain '&' (ampersand).

**Comment by KimChr** [comment]
Hi Pete

Didn't see that one, sorry.
Thank you very much :-)

Regards,
Kim
