### ISSUE TITLE
403 error after creating connection

### ISSUE THREAD

**Issue by deanhinson** [pspete/psPAS#212]
Hello Pete,

Thank you for all the help on the previous issues I was having. I got everything figured out with my PVWA and upgraded my PowerShell to 5.1. I can confirm that the module does not work with PowerShell 4. I am not getting a different error that doesn't make much sense to me.

CyberArk Version: 9.9.5
Poweshell Version 5.1
Server: Windows 2012 R2

I can now create a session and receive a token.
<img width="824" alt="new 403 error once connected" src="https://user-images.githubusercontent.com/39169912/64367465-0c760680-cfe6-11e9-83ef-d2880cbb3481.PNG">
<img width="821" alt="API token connection" src="https://user-images.githubusercontent.com/39169912/64367467-0f70f700-cfe6-11e9-9e80-48514dbb5979.PNG">

Attached are two ways to confirm that I am getting a response and a token from the API. As you can see in the 1st screenshot I received a 403 error. It is weird though because as you can see the "Find-PASSafe" command works. I tried the "Get-PASLoggedOnUser" and got this 403 error saying their is an error with the token. This is just on example command and it is happening with other commands as well.

**Comment by pspete** [comment]
What version of the module?
What happens if you run `Get-PASSession`?

**Comment by deanhinson** [comment]
I am sorry for not including it. I have version 3.1.13. When I do the command you asked it comes up with the same 403 error. The credentials I am using are admin credentials and work when logging into the web interface.

**Comment by pspete** [comment]
Try the latest version (3.2)

**Comment by deanhinson** [comment]
Just upgraded to the current version 3.2.32 and still get the same 403 token error.

**Comment by pspete** [comment]
The error being returned suggests there is still an issue with the web server configuration.

**Comment by deanhinson** [comment]
After more testing it I can confirm there is more wrong with my configuration. Attached is another error confirming that my environment is the problem again. Thank you for all the patience.
<img width="921" alt="404erroriis" src="https://user-images.githubusercontent.com/39169912/64439430-ee68de80-d097-11e9-9ec1-107b9263d23e.PNG">

**Comment by pspete** [comment]
Reconcile is not supported by the API in 9.95 (at least 9.10 is required).
With a properly configured PVWA, `psPAS` should pickup the PAS version and give a meaningful error message detailing that the command is not supported for your version.

**Comment by deanhinson** [comment]
In the documentation for the module it says that Verify,Change, and Reconcile are all compatible with 9.7. Is that incorrect?

**Comment by pspete** [comment]
9.7 is the minimum version required; the Classic API only supports Change & Verify.
`Invoke-PASCPMOperation` rolls all CPM related API methods into a single function.
9.10 is when support for the additional Verify, Change (immediately, specify next value, change only in vault), & Reconcile API methods were introduced.

**Comment by deanhinson** [comment]
Thank you for all the help Pete it is much appreciated. This ticket will be closed now as the error I am getting is not related to PSPAS again. I appreciate your patience and understanding. It would be helpful is you also made the documentation more clear on the CPM operation cmdlet.
