### ISSUE TITLE
pspete powershell scripting how to show the correct error message

### ISSUE THREAD

**Issue by jesaldosa** [pspete/psPAS#215]
10.9

* PowerShell Version: 5
* psPAS Branch & Version:  3.1.13     psPAS                               PSGallery            Module for CyberArk Privileged Access Security Web Service REST API
* CyberArk Version: 10.9

Hope you guys can help.

 

we have the following bit of code to add accounts from a CSV file using pspete powershell module

 
```

try{
	Add-PASAccount -secretType Password -secret $Password -SafeName $Account.SafeName -PlatformID $Account.PlatformID -Address $Account.Address -Username $Account.Username -platformAccountProperties $PlatArray 
 
}
 
catch{
 
	Write-Host "Unable to added group " $SafeName "Error Message:" $_
 
	Write-Host "Error Message:" $_.Exception.Message
	Write-Host "Error Message:" $_
 
}
```
If the safe or platform does not exit it throws the following exception.

 

 

 

Error Message

 

If you run the same through the web api

 

Error Message via API

 

You get the full error message i.e platform not found. How can i get the correct error message from the Powershell script?

 

what changes are needed to the catch statement to make this work. Any help will be greatly appreciated.

 

Regards Jesal

**Comment by jesaldosa** [comment]
![Error Message via API](https://user-images.githubusercontent.com/56271097/66333921-d81c9f80-e92f-11e9-8ae0-3f3959c47e48.jpg)
![Error Message](https://user-images.githubusercontent.com/56271097/66333926-da7ef980-e92f-11e9-948d-f465a3e3eb8d.jpg)

**Comment by jesaldosa** [comment]
Added in the error messaged from the script and calling it directly from the webapi

**Comment by pspete** [comment]
Hi @jesaldosa 

I reproduced your scenario, and the message string you want can be obtained in the catch block like this:

````powershell

$_.TargetObject.ErrorDetails.Message | ConvertFrom-Json | Select-Object -ExpandProperty Details

````

**Comment by jesaldosa** [comment]
Thanks Pete. Ill give this a try tomorrow and let you know.

Cheers

**Comment by jesaldosa** [comment]
Thanks Pete you are a super star

![image](https://user-images.githubusercontent.com/56271097/66391683-abb36280-e9c5-11e9-8567-e13d35ef5817.png)

That worked! thank you
