### ISSUE TITLE
Running New-PASRequest with MultipleAccess $true doesn't work as expected.

### ISSUE THREAD

**Issue by jaapvstr** [pspete/psPAS#216]
**Describe the issue**
Running New-PASRequest with MultipleAccess $true doesn't work as expected. I have a gut feeling boolean values are not working as expected.

**To Reproduce**
1. Run New-PASRequest -AccountId $AccountID -Reason "Please Approve" -MultipleAccess $true -FromDate $FromDate -ToDate $ToDate
2. Check the request
3. It shows up as a OneTime access request

**Expected behavior**
It should show up as a multiple time access request

**Screenshots & Console Output**
When I catch the request I get:
-URI: https://pwv.intranet/PasswordVault/API/MyRequests -Method: POST -Body: {
    "ToDate":  "1571932440",
    "AccountId":  "4664_4",
    "FromDate":  "1571846040",
    "Reason":  "Please Approve",
    "MultipleAccess":  true
} -WebSession: Microsoft.PowerShell.Commands.WebRequestSession -ContentType: application/json -UseBasicParsing: True

**Your Environment**
* PowerShell Version: 5.1.17134.858
* psPAS Version: commit 71a201d master branch
* CyberArk Version: ExternalVersion: 9.10.4 InternalVersion: 9.99.4.1

**Additional context**
I tried to change the request to manually send $true quoted, e.g.:  "MultipleAccess":  "true", but it still ends up being an OneTime access request.

**Comment by jaapvstr** [comment]
I just found the solution for this in the Arcsite documentation. It's a bit ambigious on this parameter, but changing the -MultipleAccess $true parameter to -MultipleAccessRequired $true solved the issue.

**Comment by pspete** [comment]
Thanks for the report @jaapvstr - I'll get this worked into the next psPAS update

**Comment by pspete** [comment]
Fixed in version `3.3.88` on the master branch & published to the PowerShell Gallery.
