### ISSUE TITLE
"AddAccounts" permission includes "Update Account Properties"

### ISSUE THREAD

**Issue by zshehri** [pspete/psPAS#22]
While testing `Set_PASSafeMembers` & `Add_PASSafeMembers`

I found this token ``` -AddAccounts $false ``` overwriting ``` -UpdateAccountProperties $ture ``` and it seems it was already mentioned in the GUI (Update Safe Member window):

![image](https://user-images.githubusercontent.com/24983719/29714261-6113f17a-8970-11e7-82ba-9567f894a281.png)

but couldn't find it documented anywhere in the RestAPI page. May be it's worth to mention here.

**Comment by pspete** [comment]
Thanks for highlighting this @zshehri .

You are right - adding "AddAccounts" always adds "UpdateAccountProperties".
Removing "AddAccounts" always removes "UpdateAccountProperties".

In the absence of a way to be able to resolve via code, I shall update the comment based help text for the AddAccounts parameter on the Add-PASSafeMember & Set-PASSafeMember functions to reflect the behaviour.
