### ISSUE TITLE
NON-ISSUE QUESTION (or feature request)

### ISSUE THREAD

**Issue by AaronG1234** [pspete/psPAS#223]
is there a way to server side filter for Get-PASAccountActivity

current commandlet has a param of:

param(
		[parameter(
			Mandatory = $true,
			ValueFromPipelinebyPropertyName = $true
		)]
		[Alias("id")]
		[string]$AccountID

	)

But I would like to get say just Store passwords from the last 7 days....
etc.

The reason it is useful to me (provided the API even supports it) is i have to check the history of about 9000 Accounts for a Read or Unlock without a more recent store every couple of hours, in a particular environment where CPM cannot update the password (the actual one in the utility, not the one in CyberArk)

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version: 3.2.37
* CyberArk Version: 11.1

**Additional context**

**Comment by pspete** [comment]
As per the published [API documentation](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/Files%20-%20Get%20File%20Activity%20by%20ID.htm), this is not currently supported.
