### ISSUE TITLE
Empty Response Always

### ISSUE THREAD

**Issue by cico971** [pspete/psPAS#232]
**Describe the issue**
When i try to connect with CyberArk or LDAP authentication i always have no token, the password is correct, when i tried with postman i got a token.

**To Reproduce**

[string]$baseURI = "https://cyberark.security.local"
[string]$authenticationMethod = "LDAP"
$session = New-PASSession -Credential $credentials -BaseURI $baseURI -type $authenticationMethod -Verbose -Debug -SkipCertificateCheck
Write-host $session

**Expected behavior**
token printed

**Screenshots & Console Output**

Console Output Code Block:
![image](https://user-images.githubusercontent.com/11680207/70744927-1022d300-1d23-11ea-86fe-89caba56de8d.png)

**Your Environment**

* PowerShell Version: 5.1.14409.1005
* psPAS Version: 3.2.37
* CyberArk Version: 11.1.0

**Comment by pspete** [comment]
Please share your command, output and error message (or complete the details in the issue template).

How are you determining that you no token is returned?

**Comment by pspete** [comment]
@cico971 - Thanks for the additional info, it helps.
This is expected - `New-PASSession` returns no output to the console on success.
After authenticating to the api using psPAS, the module saves the Authorization token in the module scope, and takes care of providing this value in all subsequent requests.
If you want the actual value returned from the api, the `Get-PASSession` can return the details from the module scope:

```powershell
(Get-PASSession).WebSession.Headers["Authorization"]
```

**Comment by pspete** [comment]
As there has been no update, am assuming the previous answer has helped. Closing this now.

Feel free to comment if you feel it should be reopened.
