### ISSUE TITLE
Using New-PASSession doesn't return a token

### ISSUE THREAD

**Issue by gregmarnie** [pspete/psPAS#237]
**Describe the issue**
Using the New-PASSession function does not return a token.  However, when I run Get-PASSession, it provides details as if the session was created properly.  In addition, $token (for example) is passed to the Add-PASSafe with the verbose switch, it shows now errors but the safe is never created.  

The New-PASSession with the verbose switch does not indicate any issues and there are no errors thrown using a try/catch.  Everything seems fine but there is no token and obviously the safe never gets created.  

I have used direct "Get-Credentials" and also used the Get-CCPCredential.  The Get-CCPCredential does pull the credentials from the vault properly. 

Currently running version 11.1 and the most recent version of psPAS.

**To Reproduce**
As mentioned, the $getCreds does provide the CCP creds so the issues is with no token in results when running New-PASSession

$getCreds = Get-CCPCredential -AppID TestCCPApplications -Safe "CyberArk Administrators" -Object "xxxxxxxxx" -WebServiceName AimWebService -URL $baseURL
$secureCreds = ConvertTo-SecureString $getCreds.Content -AsPlainText -Force
$apiCreds = New-Object System.Management.Automation.PSCredential ($getCreds.UserName, $secureCreds)

try {
    $token = New-PASSession -Credential $getCreds -BaseURI $baseURL -type CyberArk -Verbose -Debug
}
 
catch {
    Write-Host "[ERROR] There was an error logging into the Vault." -ForegroundColor "Red"; break 

**Expected behavior**
Expect to receive a token that can be passed for subsequent functions.

**Screenshots & Console Output**
Console output with URLs masked

PS C:\CyberArk-Powershell-RESTfulAPI\PUU-PS> $token = New-PASSession -Credential $getCreds -BaseURI $baseURL -type CyberArk -Verbose -Debug
DEBUG: [Body] {
    "username":  "administrator",
    "password":  "******",
}
VERBOSE: POST https://cyberark.local/PasswordVault/api/Auth/CyberArk/Logon with -1-byte payload
VERBOSE: received 182-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://cyberark.local/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
VERBOSE: received 79-byte response of content type application/json; charset=utf-8

PS C:\CyberArk-Powershell-RESTfulAPI\PUU-PS> $token

PS C:\CyberArk-Powershell-RESTfulAPI\PUU-PS> 

Console Output Code Block:
```powershell


```

**Your Environment**

* PowerShell Version: 5.1.16299.1146
* psPAS Version: latest, I believe...not sure how to check
* CyberArk Version:  11.1

**Additional context**
Using swagger or writing my own code with Invoke-RestMethod, I'm able to retrieve a token with no problems using the same cred variable.

**Comment by dokki767** [comment]
I believe this is the expected behavior today.  All session management is handled internally now.  Run the new-passession without saving to variable, then just call the next function like you normally would just omitting the token pipe in.  So like this...

New-Passession -baseuri https://vault.evilcorp.com -verbose -usedefaultcredentials
Get-PasAccount -search 'Web_Evilcorp_Prod'

You'll get responses as you normally would.  It's a bit of a change but streamlines the process a bit.

**Comment by dokki767** [comment]
Further your safe isn't getting created because you are now passing an empty variable but also that the new functions don't accept pipe in anymore.  Just drop the $token | and should create your safe.

**Comment by gregmarnie** [comment]
dokki767, thank you for the quick reply and that worked.  Greatly appreciated!  
You mentioned it is the expected behavior today, is it expected with the current psPAS or with the newer versions of CyberArk?  I just upgraded from 10.3 to 11.1 but the restful/ccp stuff is new to me regardless.  Thanks again.

**Comment by dokki767** [comment]
Default within PsPAS now.  I ran into the same issue last week and almost opened an issue as well until i started digging deeper into it on my own and noticed it was screaming on the trying to force a token that didn't exist and wasn't needed anymore.  To check your PsPAS version just for the future, load the module in  PS and then just do a "get-module | Where-Object {$_.name -eq "psPAS"} and should spit out the version number of the module you are running.

**Comment by gregmarnie** [comment]
Ok, great, thanks again dokki767.  This is great information...

**Comment by pspete** [comment]
Thanks @dokki767 🌟 !
Glad you all is working now @gregmarnie
