### ISSUE TITLE
Unable to remove Pas Account

### ISSUE THREAD

**Issue by ghost** [pspete/psPAS#242]
This most likely is an internal issue but wanted to see if you have any ideas. I am able to use `Get-PASAccount -search $item` and retrieve back the accounts added, including the `AccountID` attribute. I would now like to remove this account using `Remove-PASAccount -accountID $AccountID`. I run the command but the account does not get deleted (no error's either) and I am still about to get the account again with `Get-PASAccount` . Any idea what could be causing this or where I could look to fix the issue?

Thanks!

**Comment by pspete** [comment]
Related to #230 perhaps?

**Comment by kdrumz23** [comment]
I tried unlocking the account and running `Remove-PASAccount` again but no luck. Running `Get-PASAccountActivity` however I can see the last activity was a `CPM Verify Password Failed`. Think that could be the cause?

**Comment by pspete** [comment]
After `Remove-PASAccount -accountID $AccountID`:
- If `Get-PASAccount -search username` still finds the account, and the the object is not marked for deletion in it's safe, you likely have some investigation to do to find out exactly why you face a challenge.
I can't reproduce unfortunately.

**Comment by pspete** [comment]
ghosted

**Comment by jis-augustine** [comment]
@ghost Was this resolved, I am also experiencing same issue
