### ISSUE TITLE
Issue in listing Platforms using comand get-PASplatform 

### ISSUE THREAD

**Issue by deepthick4** [pspete/psPAS#246]
**Describe the issue**
When trying to pull all the list of platform using get-pasplatform command  , i am getting the below issue 
Invoke-PASRestMethod : [500] The given key was not present in the dictionary.
At line:130 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method GET -WebSession $S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"C...e dictionary."}:ErrorRecord) [Invoke-PASRestMethod
   ], Exception
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod
**To Reproduce**
1. I believe you can reproduce the issue if have more than 400 + Platform  

**Expected behavior**
Just to list all active and inactive platform , even filtering to specific platform is not working and returning the same error 

**Screenshots & Console Output**

Console Output Code Block:

**Your Environment**
Include relevant details about your environment
Windows 2012 Vault 11.2 HA enabled 
* PowerShell Version:5.1
* psPAS Vers: 3.4.100
* CyberArk Version:PVWA 11.2 and vault 11.1 

**Additional context**
We have two vaults and in one vault this command works fine which got only less platforms . The issue happens on the vault which got more than 400 active platforms

**Comment by UhtredTheBold** [comment]
Just to add to my colleague's issue, if we run with the platformid switch it will return results fine, but trying to return all platforms or running a search fails with the above error.

**Comment by pspete** [comment]
See if it works outside of the module:

```powershell
#after authenticating with New-PASSession
$s = Get-PASSession

$Request = @{
    "Method"      = "GET"
    "Uri"         = "$($s.BaseUri)/API/Platforms"
    "WebSession"  = $s.WebSession
    "ContentType" = "application/json"
}

Invoke-RestMethod @Request
```

If it works for you when not using the module, I can see what may be the issue in the module's code.

**Comment by deepthick4** [comment]
Its not working out the module as well :(

PS C:\Scripts\PAS_Powershell> $Request

Name                           Value
----                           -----
ContentType                    application/json
Method                         GET
WebSession                     Microsoft.PowerShell.Commands.WebRequestSession
Uri                            https://pvwa.xxxxxx.xx/PasswordVault/API/Platforms


PS C:\Scripts\PAS_Powershell> Invoke-RestMethod @Request
Invoke-RestMethod : {"ErrorCode":"CAWS00001E","ErrorMessage":"The given key was not present in the dictionary."}
At line:1 char:1
+ Invoke-RestMethod @Request
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], W
   ebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by pspete** [comment]
Unfortunately nothing to update in the module to resolve this.
You will need to use your usual support channels.
