### ISSUE TITLE
Set-PASUser requires bot id and Username for 11.1

### ISSUE THREAD

**Issue by jbalcorn** [pspete/psPAS#247]
When using Set-PASUser to change AuthenticationMethod (requiring the 11.1 Parameter Set), both id and UserName are set to Mandatory=$true.

**To Reproduce**

Since ID is required, it should be the only requirement

```powershell
PS > set-pasuser -id (get-pasuser -UserType EPVUser -Search "user1").id -authenticationMethod "AuthTypeLDAP" 
cmdlet Set-PASUser at command pipeline position 1
Supply values for the following parameters:
username: 
PS > set-pasuser -UserName User1 -authenticationMethod "AuthTypeLDAP" 
cmdlet Set-PASUser at command pipeline position 1
Supply values for the following parameters:
id: 


```

**Your Environment**

* PowerShell Version: 5
* psPAS Version: 3.3.88
* CyberArk Version: 11.1

**Comment by pspete** [comment]
The [API documentation](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.1/en/Content/WebServices/Users%20Web%20Services%20-%20Update%20User.htm) states Username is mandatory, hence the setting for the parameter in the module.

**Comment by pspete** [comment]
It is definitely required - you can confirm by setting `Mandatory = $false` for the username parameter in Set-PASUser

```powershell
PS C:\> Set-PASUser -id 652 -workStreet "Some Street"
Invoke-PASRestMethod : [400] There are some invalid parameters: Missing mandatory parameter [username].
At line:741 char:14
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method PUT -Body $Body -W ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"Details":[{"P...id parameters"}:ErrorRecord) [Invoke-PASRestMethod], Exception
    + FullyQualifiedErrorId : PASWS167E,PASWS011E,Invoke-PASRestMethod
```
