### ISSUE TITLE
new-passession : Unable to find type [X509Certificate]

### ISSUE THREAD

**Issue by dokki767** [pspete/psPAS#253]
## Your Environment
* PowerShell Version:  5.0.10586.117 (on Server 2012 R2)
* psPAS Branch & Version: 3.3.88 (master)
* CyberArk Version: 10.7

## Expected Behaviour

New Vault session is established.

## Current Behaviour

new-passession -baseuri $baseuri -usedefaultcredentials

new-passession : Unable to find type [X509Certificate].
At line:1 char:1
+ new-passession -baseuri $baseuri -usedefaultcredentials
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (X509Certificate:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

## Possible Solution

Unsure if this is particular issue is tied to behavior differences in the OS or PS.  The exact same module and commands on a Server 2016 host running PS 5.1.14393.3471 I don't experience this issue.  Trying to find a test 2012 R2 host to see about updating PS to the same version as the 2016 box.

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
Can the X509Certificate type be found nativity outside the module?

```
"X509Certificate" -as [type]
```

**Comment by dokki767** [comment]
No, that cmd actual comes back blank vs. my local PS instance which is 5.1 i get a System.Object return.

**Comment by pspete** [comment]
I don't have PowerShell 5.0 available to validate.

`Invoke-WebRequest` does expect a type of `X509Certificate`.

```powershell
PS>Invoke-WebRequest -Certificate "string"
Invoke-WebRequest : Cannot bind parameter 'Certificate'. Cannot convert value "string" to type
"System.Security.Cryptography.X509Certificates.X509Certificate"......
```

Simplest fix at the moment would be to increase the minimum PowerShell version of the module to 5.1, but that does not help you with your issue.

**Comment by dokki767** [comment]
Working with my server admins we tested and were able to upgrade the PS Version to 5.1 as seemed the simplest fix.  So guess this is still an outstanding issue/bug with the but no longer a blocker for my efforts.  I can assist with testing as needed but feel free to handle the bug report as you see fit.
