### ISSUE TITLE
Error Return

### ISSUE THREAD

**Issue by wildunknown** [pspete/psPAS#26]
Would there be a way we can have the CyberArk error returned if there is an error in one of the module functions?

ie:
StatusCode: 500
StatusDescription: Cannot add account; reason: ITATS955E You are unauthorized to create object in Safe TESTSAFE01.
Response: The remote server returned an error: (500) Internal Server Error.

**Comment by pspete** [comment]
Hi @wildunknown - I will investigate - if it is possible, I will implement.
