### ISSUE TITLE
Reqest that module be signed for secure environments

### ISSUE THREAD

**Issue by JefeDavis** [pspete/psPAS#261]
**Is your feature request related to a problem? Please describe.**
we use psPas in our environment extensively for interactions with cyberark however due to the module not being signed we must manually approve each of the 141 files before we can use each version

**Describe the solution you'd like**
I would like to request that the module be digitally signed when published to the powershell gallery as recommended by Powershell Gallery Best Practices https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/publishing-guidelines?view=powershell-7

**Comment by dokki767** [comment]
We have the same problem but we have an enterprise code signing certificate that we bulk sign everything with whenever we download updates.  Trusted code signing certs cost a little bit, since this is an open-source/community driven effort it's not really feasible for everyone that is doing commits to have a publicly trusted code signing cert.  Even if Pete is the main contributor, whenever someone else would do a commit to the main branch there's a dependency of him going back in and re-signing everything.

**Comment by pspete** [comment]
Code signing is on the project roadmap, but incurs a financial cost to procure & maintain the certificate which the open source project simply does not currently have available; the feature request is accepted, but it is not something which will be able to delivered until a code signing certificate is purchased.

The module’s [build script already has the ability to sign any releases](https://github.com/pspete/psPAS/blob/master/build/build.ps1#L59) before being published to the PowerShell Gallery & GitHub; once a code signing certificate is available to the project there will be minimal development work required to sign the next release.

Contributions or donations towards the purchase price of a certificate will be gratefully accepted through [GitHub sponsors](https://github.com/sponsors/pspete).

**Comment by AaronG1234** [comment]
At least in the interim, you could do a quick
`$SigningCert = @(Get-ChildItem Cert:\CurrentUser\My\ -CodeSigningCert)[0]
$timeStamper = 'http://timestamp.verisign.com/scripts/timstamp.dll'
$ModulePath = 'put something here'

Get-Childitem -path $ModulePath -include *.ps1,*.psm1,*.psd1 -recurse | Get-AuthenticodeSignature | where-object {$_.status -eq 'NotSigned'} | Set-AuthenticodeSignature $_.path -Certificate $signingcert -IncludeChain notroot -TimestampServer $timestamper -HashAlgorithm SHA256`
