### ISSUE TITLE
[500] error when initiating psPAS session

### ISSUE THREAD

**Issue by miardman009** [pspete/psPAS#269]
Invoke-PASRestMethod : [500] Could not load type 'adsc' from assembly 'CyberArk.Services.Web, Version=8.0.0.0, Culture=neutral, 
PublicKeyToken=40be1dbc8718670f'.
At line:580 char:19
+                 $PASSession = Invoke-PASRestMethod @LogonRequest
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"C...dbc8718670f'."}:ErrorRecord) [Invoke-PASRestMethod], Exception
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod

**Comment by pspete** [comment]
Based on the detail you have provided, the issue does not appear to relate to psPAS.

- Confirm that authentication works outside of psPAS:

```powershell
$Request = @{
    "Uri" = "https://<Your-PVWA>/PasswordVault/api/Auth/Cyberark/Logon"
    "Body" = New-Object -Property @{"username" = "SomeUser"; "password" = "SomePassword" } -TypeName psobject | ConvertTo-Json
    "Method" = "POST"
    "ContentType" = "application/json"
}

Invoke-RestMethod @Request
```

- If authentication outside of psPAS is unsuccessful, there is no fix to apply to the modules code; your infrastructure/configuration/log files should be reviewed to determine the cause of the issue. 
- If authentication outside of psPAS is successful, please log a new issue, completing the details in the issue template (including relevant version information and steps to reproduce)
