### ISSUE TITLE
AD Group Safe Member Modification Issue

### ISSUE THREAD

**Issue by DannyIV** [pspete/psPAS#270]
**Describe the issue**
When dealing with AD groups added to safes as members, the "DOMAIN/" prefix causes an issue. Due to the "/" being recognized as pathway syntax in the Invoke-RestMethod request, targetting that group doesn't seem possible. We have tried using %f2 to escape this, but without luck. 

**To Reproduce**
1.  Create a group in AD
2.  Add that group as a memebr of a safe
3.  Attempt to "get" or "remove" that group

**Expected behavior**
The group should be removed from the safe

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5
* psPAS Version: 10
* CyberArk Version:10.9

**Comment by pspete** [comment]
Have you tried simply omitting the `DOMAIN\` prefix?

**Comment by DannyIV** [comment]
I have yes but as opposed to a syntactical error returned; I simply get a typical "group cannot be found". When I list all safe members, the "UserName" (MemberName) is listed fully as DOMAIN/XXXX. So the suspicion is that the domain is included in the value

**Comment by pspete** [comment]
By any chance is "DOMAIN/" configured as the VaultObjectNamesPrefix on your directory mapping?

**Comment by gavwellis** [comment]
Hi,

I'm picking this up from Dan.

I tried this again, and we're still recieving the following:

![image](https://user-images.githubusercontent.com/33420437/84598672-5db00200-ae64-11ea-92ad-3c39b323061c.png)

**Comment by pspete** [comment]
@gavwellis & @DannyIV - as the issue also occurs in native powershell calls against the API, and is not introduced by psPAS, suggest the above method can be used for you to determine how you can send a problematic character in your vault object names for the requests.

Alternatively, investigate & resolve the reason for problematic characters appearing in vault objects from your directory mapping.

If you find a solution, let us know.

**Comment by gavwellis** [comment]
Hi again,

We seem to have found a solution. In CyberArk, you can alter how the domain prefix appears using 'AddDomainToUserName'.

Instead it now appears like this:

![image](https://user-images.githubusercontent.com/33420437/84660588-f7cd8400-af10-11ea-88fe-9672c4e8edef.png)

Instead of 'PRODUCTION/***'

**Comment by pspete** [comment]
ok - so your config issue is now solved? psPAS now can help with your task?

**Comment by gavwellis** [comment]
Yep - all good! 

By the way, the prefix 'DOMAIN/' was being added by CyberArk not us. It defines it like this to show the difference between.

**Comment by pspete** [comment]
Presumably, VaultObjectNamesPrefix configured with 'DOMAIN/' on a directory mapping.
In any case, good to know your issue is fixed.
