### ISSUE TITLE
API Bug confirmed by CyberArk

### ISSUE THREAD

**Issue by jhnlambert** [pspete/psPAS#272]
**Describe the issue**
Some API calls expect the body of the call to be ordered in the same order as displayed in the PVWA. CyberArk has confirmed this as a bug and opened bug CB-04660 in response to a case we opened and worked through with them. 

This effects "raw" post calls, postman if you re-order the body, and psPAS (Tested in versions 3.4.1 and 3.5.8)  

The API method we have confirmed this being an issue for so far is just the Set-PASSafeMember and equivalent "Update Safe Member" API call. However we have not dug into the other body based calls to fully test this either. 

Note: Due to company policy I can open an issue for this but providing any scripts developed on company time/hardware/etc requires approval. If the issue isn't sufficient I can get started on that to better help get this resolved.  

This is not an issue with the psPAS code, it's an issue with the cyberark API logic. I don't know when they will be getting a fix released however. 

**To Reproduce**
Steps to reproduce the behavior - Postman:
1. Get token/authenticate
2.  Using "Update Safe Member" in Postman set a safe owner to have all permissions 
3. Verify the owner has expected permissions
4. Move the 'AddAccounts' permission to the bottom of the body and set it to false.
`{
	"member":
	{
		"MembershipExpirationDate":"",
		"Permissions":
		[
			{"Key":"UseAccounts", "Value":true}, 
			{"Key":"RetrieveAccounts", "Value":true}, 
			{"Key":"ListAccounts", "Value":true}, 
			{"Key":"UpdateAccountContent", "Value":true}, 
			{"Key":"UpdateAccountProperties", "Value":true}, 
			{"Key":"InitiateCPMAccountManagementOperations", "Value":true}, 
			{"Key":"SpecifyNextAccountContent", "Value":true}, 
			{"Key":"RenameAccounts", "Value":true}, 
			{"Key":"DeleteAccounts", "Value":true}, 
			{"Key":"UnlockAccounts", "Value":true}, 
			{"Key":"ManageSafe", "Value":true}, 
			{"Key":"ManageSafeMembers", "Value":true}, 
			{"Key":"BackupSafe", "Value":true}, 
			{"Key":"ViewAuditLog", "Value":true}, 
			{"Key":"ViewSafeMembers", "Value":true}, 
			{"Key":"RequestsAuthorizationLevel", "Value":0}, 
			{"Key":"AccessWithoutConfirmation", "Value":true}, 
			{"Key":"CreateFolders", "Value":true}, 
			{"Key":"DeleteFolders", "Value":true}, 
			{"Key":"MoveAccountsAndFolders", "Value":true},
			{"Key":"AddAccounts", "Value":false}
		]
	}
}`
5. After running this command, Both 'AddAccounts' and 'UpdateAccountProperties' will be false.
6. This is due to the API endpoint expecting the body in a specific order. 

Steps to reproduce the behavior - psPas:
1. Get login token - New-PASSession
2. Run Set-PASSafeMember with all permissions set to true, safe response as $resp1 
3. Run Set-PASSafeMember against the same owner and safe, all permissions set to true excpet "addAccounts", safe response as $resp2
4. compare permission outputs $resp1.Permissions vs $resp2.Permissions will show that $resp2 is 2 permissions less - AddAccounts(expected) and UpdateAccountProperties (issue)

**Expected behavior**
The flags set reflect permissions applied. 

**Screenshots & Console Output**
I can get screenshots if needed, just wanted to err on the side of caution as far as providing "company" code/screenshots/etc. Please let me know if you need more info or anything!

Console Output Code Block:
I can get screenshots if needed, just wanted to err on the side of caution as far as providing "company" code/screenshots/etc. Please let me know if you need more info or anything!

**Your Environment**
Also confirmed by CyberArk in a 10.7 env, they were using postman however. 

* PowerShell Version: 5.1.16299.1146
* psPAS Version: 3.4.1 and 3.5.8
* CyberArk Version: PVWA-11.1.1.4, Vault-11.1

**Comment by pspete** [comment]
Thanks for reporting this @jhnlambert 

Both [Add-PASSafeMember](https://github.com/pspete/psPAS/blob/master/psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1#L46) & [Set-PASSafeMember](https://github.com/pspete/psPAS/blob/master/psPAS/Functions/SafeMembers/Set-PASSafeMember.ps1#L34) have contained a note about this behaviour since 2017....

**Comment by jhnlambert** [comment]
Hey @pspete !

My apologies for not seeing that note in the documentation previously. 

Reading the CyberArk documentation the relationship is one way (IE: addAccounts adds UpdateAccountProperties but not vice versa: https://cyberarkdocu.azurewebsites.net/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Update%20Safe%20Member.htm ) 

This is reflected in assigning permissions via PVWA (UpdateAccountProperties  can be added without addAccounts, but not vice versa), postman (without modify the body out of order described in my steps), and within psPAS (setting UpdateAccountProperties  can be set to true without add account being true if that is the only permission set in the Set-PASSafeMember call)

I don't think I effectively communicated that in the original post, my apologies. 



If the end call is that this is just a known limitation of the psPas module, that's fair. We have a few known work-arounds implemented in our automation currently.


Hopefully that makes sense! 

Thanks for the quick response, I appreciate it!

**Comment by pspete** [comment]
No worries at all - I really appreciate all contributions 👍

Refreshing my memory on this, I can see the note was added after a similar report from an early adopter of the module way back in issue #22 !

Let me know if you think any further action is needed - it has been effectively parked for the last 3 years as a limitation with no workaround.

**Comment by jhnlambert** [comment]
Yeah, I'm late to the party it seems! 

I was able to get it to function by having the body constructed as an ordered hashtable, opposed to a default hashtable which is "unordered" (it's just ordered in the background in PS). Also formatting the bodies in a specific way also makes powershell keep the order intact. 

It's easier if it's just a body you are making in script as a static variable essentially, but it _should_ be doable the way you are constructing the bodies with some massaging of the data. 

I am going to start the process to be able to submit a MR for this, hopefully I can get that all pushed through and be able to take a swing at this. 
If nothing else I'll bang my head on the wall for a bit and come to the same conclusion that it's a limitation. 


Otherwise, keeping this as a parked issue and a known limitation is plan B.  


I can mark the issue as closed and just spin up the branch and work through it there if that all gets approved. Would you prefer I leave this open or close out the issue for now?

**Comment by pspete** [comment]
@jhnlambert the dev branch now contains an update to maintain the static order of the permission parameters in the json body.

**Comment by jhnlambert** [comment]
Thanks so much Pete!

Sorry I was taking a bit with the approval process on my end. 


I tested out the fix in the dev branch, confirmed working! 

Thanks again for such a quick fix for this! 


Closing out the issue.
