### ISSUE TITLE
New-PASUser is not working.

### ISSUE THREAD

**Issue by riturkkumar** [pspete/psPAS#273]
**New-PASUser is not working.**
I am trying to create a script for safe and epv user creation and safe ownership. 
Safe creation and owner ship is working fine but new epv user creation is not working. 
Please help.
Please find attached script.

Regards
Ritesh Kumar
[createsafeuser-api.zip](https://github.com/pspete/psPAS/files/4814647/createsafeuser-api.zip)

**Comment by pspete** [comment]
@riturkkumar - please complete the issue template and include the details, code and steps to reproduce.
