### ISSUE TITLE
New-PASUser is not working.

### ISSUE THREAD

**Issue by riturkkumar** [pspete/psPAS#274]
**New-PASUser is not working.**
I created a scrip for safe and epv user creation and safe ownership. safe creation and ownership is working fine but new pasuser creation is not working. I am using PAS V 11.4.

**To Reproduce**
1.  $token = New-PASSession -Credential $apiCredentials -BaseURI $baseURI -Verbose -ErrorAction Stop
2. $token | Add-PASSafe -SafeName $safeName -Description "Automatically Created by CyberArk Safe Factory" -ManagingCPM PasswordManager -NumberOfVersionsRetention 7 -Verbose -ErrorAction Stop
3. $token | Add-PASSafeMember -SafeName $safeName -MemberName $username -SearchIn $domainName -UseAccounts $true -RetrieveAccounts $true

**Expected behavior**
New Safe and EPV user should be created and new user should get permission on new safe.

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.18362.752
* psPAS Version: 3.5
* CyberArk Version: 11.4

[createsafeuser-api.zip](https://github.com/pspete/psPAS/files/4817444/createsafeuser-api.zip)

**Comment by aaearon** [comment]
Please provide the error message you are recieving when you perform the above.

Also, you do not need to pass the authentication token generated with New-PASSession down the pipeline to other psPAS cmdlets.

**Comment by pspete** [comment]
@riturkkumar , there is no invocation of `New-PASUser` in the detail provided by you. 

```powershell
New-PASSession -Credential $apiCredentials -BaseURI $baseURI -Verbose -ErrorAction Stop
Add-PASSafe -SafeName $safeName -Description "Automatically Created by CyberArk Safe Factory" -ManagingCPM PasswordManager -NumberOfVersionsRetention 7 -Verbose -ErrorAction Stop
Add-PASSafeMember -SafeName $safeName -MemberName $username -SearchIn $domainName -UseAccounts $true -RetrieveAccounts $true
```

As it stands, the code provided should authenticate, create a safe, and add a safe member (which appears an AD user).
Can you clarify the "New-PASUser is not working" statement? Ideally, the code you use as well as the output or error you recieve should be included to enable anyone reading to understand the issue.

**Comment by riturkkumar** [comment]
Sorry my mistake, require details are below.

### LOGIN
try {
    $token = New-PASSession -Credential $apiCredentials -BaseURI $baseURI -Verbose -ErrorAction Stop

    Write-Host "Securely logged into CyberArk Web Services"
} catch {
    Write-Host "[ ERROR ] Could not login to CyberArk Web Services" -ForegroundColor Red
    Exit
}

### CREATE SAFE
try {
    $token | Add-PASSafe -SafeName $safeName -Description "Automatically Created by CyberArk Safe Factory" -ManagingCPM PasswordManager -NumberOfVersionsRetention 7 -Verbose -ErrorAction Stop

    Write-Host "Created ${safeName} safe"
} catch {
    Write-Host "Safe already exists... continuing to Add Safe Members" -ForegroundColor Red
}

### CREATE USER
try {
	$token | New-PASUser -UserName $username -InitialPassword CyberArk1 -Verbose -ErrorAction Stop
	
	Write-Host "Created ${username} User"
} catch {
    Write-Host "User already exists... continuing to Add Safe Members" -ForegroundColor Red
}

### PERMISSION USER ROLE
try {
    $token | Add-PASSafeMember -SafeName $safeName -MemberName $username -SearchIn $domainName -UseAccounts $true -RetrieveAccounts $true -ListAccounts $true `
        -AddAccounts $false -UpdateAccountContent $false -UpdateAccountProperties $false -InitiateCPMAccountManagementOperations $false -SpecifyNextAccountContent $false -RenameAccounts $false `
        -DeleteAccounts $false -UnlockAccounts $false -ManageSafe $false -ManageSafeMembers $false -BackupSafe $false -ViewAuditLog $true -ViewSafeMembers $true -RequestsAuthorizationLevel 0 `
        -AccessWithoutConfirmation $false -CreateFolders $false -DeleteFolders $false -MoveAccountsAndFolders $false -Verbose -ErrorAction Stop

    Write-Host "Added the User to $safeName"
} catch {
    Write-Host "[ ERROR ] Could not add User role member to safe" -ForegroundColor Red
    Exit
}

**Comment by riturkkumar** [comment]
Hi aaearon,
Please find below result.


PS F:\Plugins-API\API\My-API-Script\Create-safe-withOwner-Get-Password> .\createsafeuser-api.ps1
===============================
CyberArk Safe Factory
===============================

Enter Safe Name to Create: api009
Enter Safe Member ID: api008
VERBOSE: Performing the operation "Logon with User 'apiadmin'" on target "https://192.168.1.201/PasswordVault".
VERBOSE: POST https://192.168.1.201/PasswordVault/api/Auth/CyberArk/Logon with -1-byte payload
VERBOSE: received 182-byte response of content type application/json; charset=utf-8
VERBOSE: Assigning token to CyberArkLogonResult
VERBOSE: SessionVariable Passed; Processing WebSession
VERBOSE: GET https://192.168.1.201/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload
VERBOSE: received 79-byte response of content type application/json; charset=utf-8
Securely logged into CyberArk Web Services
VERBOSE: POST https://192.168.1.201/PasswordVault/WebServices/PIMServices.svc/Safes with -1-byte payload
VERBOSE: received 212-byte response of content type application/json; charset=utf-8

Created api009 safe
User already exists... continuing to Add Safe Members
VERBOSE: POST https://192.168.1.201/PasswordVault/WebServices/PIMServices.svc/Safes/api009/Members with -1-byte payload
[ ERROR ] Could not add User role member to safe
SafeName ManagingCPM     NumberOfDaysRetention NumberOfVersionsRetention Description
-------- -----------     --------------------- ------------------------- -----------
api009   PasswordManager                       7                         Automatically Created by CyberArk Safe Factory

**Comment by pspete** [comment]
Looking at the output provided: 
- `New-PASUser` is not being called; parameter validation will fail before trying to issue a create user request to the api:
  - This is due to not using a securestring for the value provided against the `InitialPassword` parameter.
    - The error being raised inside the `try` block is being caught and reported as "User already exists... continuing to Add Safe Members" as per the code in the catch block.


Also, you do not appear to be using one of the latest version of psPAS.
Some of the verbose output you provided was [removed from the module over 1 year ago](https://github.com/pspete/psPAS/commit/58cec61a7be402083e3cc453e81575c13a646db5#diff-7b6fb72682470910bb42d9183aabe5c0L265)...

Consider updating the module; there have been fixes to some code and psPAS version 3 brought with it some changes in the way the module works (i.e. the need to pass the authorization token with `$token | ` for every function invocation was removed).

Check the documentation for New-PASUser (for psPAS version 3+) here: https://pspas.pspete.dev/commands/New-PASUser

**Comment by pspete** [comment]
@riturkkumar - making the password value a secure string as per the below example should get you past the issue:

```powershell
$password = "CyberArk1" | ConvertTo-SecureString -AsPlainText -Force 
New-PASUser -UserName $username -InitialPassword $password
```

**Comment by riturkkumar** [comment]
@pspete  - Thanks for your kind support. Now my script is working fine.
