### ISSUE TITLE
Function to associate a Reconcile Account

### ISSUE THREAD

**Issue by wmcmiller** [pspete/psPAS#295]
Please add function to associate a Reconcile Account with searchin parameter

**Comment by pspete** [comment]
Can you elaborate at all?
Refer to the template for logging feature requests here: https://github.com/pspete/psPAS/issues/new?assignees=&labels=&template=feature_request.md&title=

**Comment by pspete** [comment]
@wmcmiller - there is no response to the request for more information, so will close the issue now.

Please use the link above to log any future feature request and provide the details in the template.
