### ISSUE TITLE
Need to pull Account ID passing Name and SafeName

### ISSUE THREAD

**Issue by jpruitt1** [pspete/psPAS#309]
**Describe the issue**
Many accounts with the same name were 'automatically' named generically with "Misc (9) Platform XYZ' (as an example) and we want to pull the Account ID for these so we can rename them to a meaningful name.  We cannot pull by account user name because it is the same account user name in the same safe on many different machines, so we need to pull by the account unique name ("Name") and Safe to get the Account ID. However, when passing the Keyword, Search, or Filter variables, psPAS returns an error indicating ambiguous parameter:

 + CategoryInfo          : InvalidArgument: (:) [Get-PASAccount], ParameterBindingException
 + FullyQualifiedErrorId : AmbiguousParameterSet,Get-PASAccount
**To Reproduce**
1. Get-PASAccount -filter "Name eq 'Misc-Storage-Only-RR-tuldssdb03-MLLD'" -Safe LiveLink_App
2.  Alternatively, this command doesn't error but also doesn't work:    Get-PASAccount -Keywords Misc-Storage-Only-RR-tuldssdb03-MLLD -Safe LiveLink_App
3. 

**Expected behavior**

**Screenshots & Console Output**

Console Output Code Block:
```powershell


```

**Your Environment**
Include relevant details about your environment

* PowerShell Version:
* psPAS Version:
* CyberArk Version:

**Additional context**

**Comment by pspete** [comment]
The command syntax in the first example is not valid `filter` & `safe` \ `Keyword` do not belong to the same parameterset.
Refer to the `Get-PASAccount` documentation here: https://pspas.pspete.dev/commands/Get-PASAccount
Only `SafeName`  is valid for the `filter` parameter: `Get-PASAccount -filter "SafeName eq TargetSafe"`

Unless using a CyberArk version earlier than 10.4, the parameterset containing `Keywords ` & `Safe` should not be used (only 1 result will be returned if a match is found).

Valid syntax for the values included in your issue would be:
```
Get-PASAccount -safeName LiveLink_App -search Misc-Storage-Only-RR-tuldssdb03-MLLD
```

**Comment by pspete** [comment]
Additional note: if no results are returned when searching by name, there is usually a setting which is disabled in the CyberArk options.

**Comment by pspete** [comment]
Hi @jpruitt1 - were you able to solve the ParameterBindingException?
Let us know if you still need this issue open or not.

**Comment by pspete** [comment]
Closing - no response
