### ISSUE TITLE
Not able add remote Machines list while creating account with Add-PASAccount

### ISSUE THREAD

**Issue by kentLee170** [pspete/psPAS#310]
**Describe the issue**
Hi Team,
i need create new more than 1000 accounts that with different remote Machines list.
Can you assist me on the command Add-PASAccount as i Not able add remote Machines list while creating account with Add-PASAccount.

below are my accounts.csv file
UserName,Password,Address,LogonDomain,RemoteMachines,SafeName,PlatformID
Pntb_pam_adea1,NoUpdateNeeded,T.com,T,server01;server02,PAM-Win-ADEA,PAMWindowDomain
Pntb_pam_adea2,NoUpdateNeeded,T.com,T,server01;server02;DC01,PAM-Win-ADEA,PAMWindowDomain

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/70575532/91836856-f09b5400-ec7d-11ea-9692-e61cd900ca54.png)

![image](https://user-images.githubusercontent.com/70575532/91836282-24c24500-ec7d-11ea-9c86-c7562ab9b31f.png)

Console Output Code Block:
$Accounts = Import-Csv -Path .\Accounts.csv

New-PASSession -Credential $creds -BaseURI https://server02.t.com

foreach($Account in $Accounts){

    $Password = ConvertTo-SecureString -String $Account.Password -AsPlainText -Force

    Add-PASAccount -secretType Password `
    -secret $Password `
    -platformAccountProperties @{"LOGONDOMAIN"=$Account.LogonDomain} `
    -SafeName $Account.SafeName `
    -PlatformID $Account.PlatformID `
    -Address $Account.Address `
    -Username $Account.Username`
    -remoteMachines @{"remoteMachines"="$Account.remoteMachines"} `
    -accessRestrictedToRemoteMachines $true

}

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version:
* psPAS Version:4.4.71
* CyberArk Version:11.3

**Additional context**
Add any other context about the problem here.

**Comment by pspete** [comment]
Try:
```powershell
-remoteMachines $Account.remoteMachines
```

**Comment by kentLee170** [comment]
Hi pspete,
thanks for the update, it work with -remoteMachines $Account.remoteMachines
btw can we have -remoteMachines on Set-PASAccount, or how i bulky change -remoteMachines value on exiting accounts via Set-PASAccount

**Comment by pspete** [comment]
[As per the examples](https://pspas.pspete.dev/commands/Set-PASAccount#examples):

```powershell
Set-PASAccount -AccountID $someID -op replace -path "/remoteMachinesAccess/remotemachines" -value "Some;Machines;Here"
```

**Comment by kentLee170** [comment]
thanks pspete

**Comment by pspete** [comment]
no problem @kentLee170
