### ISSUE TITLE
New-PASSession being quanrined by Windows Defender

### ISSUE THREAD

**Issue by jbalcorn** [pspete/psPAS#315]
**Describe the issue**
Defender identifying New-PASSession as Trojan:Powershell/Mountsi.A!ml as of 10/2/2020

**To Reproduce**
Attempt to run on Windows 10 with updated Windows Defender Anti-Virus

**Expected behavior**
Not eb identified as a virus

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/7225956/94978599-1d948e00-04ec-11eb-9caa-8bc2b9337afd.png)

**Your Environment**
Windows 10 1809

* PowerShell Version:
* psPAS Version: 4.4.71

**Comment by pspete** [comment]
Hi @jbalcorn - It is not possible to reproduce what you report; Windows Defender reports no findings.

- The psPAS code is fully transparent: 
  - Complete update history for `New-PASSession`:
    - https://github.com/pspete/psPAS/blame/master/psPAS/Functions/Authentication/New-PASSession.ps1
    - https://github.com/pspete/psPAS/commits/master/psPAS/Functions/Authentication/New-PASSession.ps1
  - Virus Total analysis of `New-PASSession` from `psPAS 4.4.71`:
     - https://www.virustotal.com/gui/file/6d89e2a8a4f9879fd71d2a6e5647fd61722736b77657846f4eec6b52fd648b10/detection
 
Confirmation of file hash of file analysed by VirusTotal against the hash of `New-PASSession` from `psPAS 4.4.71`.
```powershell
Get-FileHash "C:\Temp\psPAS-v4.4.71\4.4.71\Functions\Authentication\New-PASSession.ps1" | fl

Algorithm : SHA256
Hash      : 6D89E2A8A4F9879FD71D2A6E5647FD61722736B77657846F4EEC6B52FD648B10
Path      : C:\Temp\psPAS-v4.4.71\4.4.71\Functions\Authentication\New-PASSession.ps1
```

**Comment by jbalcorn** [comment]
We got a Signature update and it was no longer being quarantined.
-- 
Justin B. Alcorn
The views expressed are not necessarily my own, much less anyone else's
PGP Fingerprint CCEB F776 C3FD 1050 C8DB  532E B8B9 BED7 7764 406C

**Comment by pspete** [comment]
Good to know 👍
