### ISSUE TITLE
Concurrent Session Not Working

### ISSUE THREAD

**Issue by dokki767** [pspete/psPAS#318]
Trying to use the concurrentSession flag to have multiple connections to the vault open at a time but doesn't seem to be working.  Easily reproduceable.  I've tried from the same machine and from different machines and behavior is the same.  The second session continues to terminate the initial open session.  I'm barking up the CyberArk Support tree on this issue as well but they are giving me the typical run around of needing to enable debug, change DBParam.ini and restart the entire stack which is really only doable off-hours.  So not sure if this is a bug in the psPAS module or vault itself.

To reproduce, open new vault session (session A, i'm using windows integrated creds in my scenario), pull back an account details.  Don't close session.
Open new PS window, repeat steps (Session B)
Go back to Session A, attempt to pull back same account, will see failure.

* PowerShell Version: 5.1
* psPAS Version: 4.4.71
* CyberArk Version: 11.4

**Comment by pspete** [comment]
HI @dokki767 - is this the same as #316 ?
If so - there is a fix specific to concurrent sessions & windows integrated auth in the dev branch currently.

**Comment by dokki767** [comment]
That sounds similar actually yea.  Want me to download the dev code and test?

**Comment by pspete** [comment]
You can try the dev branch or the latest build artefact: https://ci.appveyor.com/api/buildjobs/af5k2utri8augk9o/artifacts/psPAS-v4.4.80.zip
The next release is still being worked on, no ETA yet on when it will be ready, but this fix will be part of it.

**Comment by dokki767** [comment]
The dev code does appear to solve the issue.  Tested having multiple sessions on the same machine and sessions on multiple machines and both scenarios work with the new code.

**Comment by pspete** [comment]
Thanks for confirming - and for the report, appreciated as always 😄
