### ISSUE TITLE
Downloading module Problem

### ISSUE THREAD

**Issue by nawazsarwar124** [pspete/psPAS#319]
Hello Expert,

i am trying to download the module from the site
https://www.powershellgallery.com/packages/psPAS/ but the page does'nt load properly. 

Is it possible you can tell me from where to download the package.

Thanks,

**Comment by nawazsarwar124** [comment]
Oops!

Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug!

Get me out of here! Go home

**Comment by pspete** [comment]
See: https://aka.ms/PSGalleryStatus

> The PowerShell Gallery is currently: Experiencing an outage as of 10/30 at 06:03AM UTC
> __Status: Under investigation
> 
> Summary of Impact: PowerShellGallery.com is experiencing an outage. Users will be unable to access the gallery or download packages.
> 
> Root Cause: Under investigation

You can use the manual install option detailed in the readme: https://github.com/pspete/psPAS#pspas-release

**Comment by pspete** [comment]
Copied the module to where? 
confirm module is installed and imported. 

```powershell 
Get-Module -ListAvailable psPAS

Import-Module psPAS
```

**Comment by nawazsarwar124** [comment]
Now it's OK, i think i missed the import-Module psPas, now i am able to logon...Now i will start few test of import the platfrom which i need..Thanks for the help m8
