### ISSUE TITLE
Get-PASAccount "Warning: x matching accounts found.  Only the first result will be returned"

### ISSUE THREAD

**Issue by gregmarnie** [pspete/psPAS#320]
**Describe the issue**
When running Get-PASAccount, it gives a warning as indicated in the title.  get-passession indicates the external version is 11.1.0.  Based on documentation, any CyberArk instance over 10.4 should not give that as a result and list all the accounts.  I'm not using the classic API switch.  Is is possible to force my connection to 10.4 and above and not run into that limitation.  

**To Reproduce**
1. User                  BaseURI                                   ExternalVersion WebSession                                     
----                  -------                                   --------------- ----------                                     
userinfo          https://mycompany.com/PasswordVault 11.1.0          Microsoft.PowerShell.Commands.WebRequestSession
2.PS H:\cyberark\audit\output> Get-PASAccount -safe mysafe
WARNING: 10 matching accounts found. Only the first result will be returned

**Expected behavior**
Based on documentation, any cyberark instance over 10.4 and not using the classic API switch should return all accounts in a safe but is acting like the old versions.  

**Screenshots & Console Output**

Console Output Code Block:
```No special code being ran, just manually running GET-PASAccount gives the error```

**Your Environment**
Running version 11.1.0

* PowerShell Version:5.1.18362.752
* psPAS Version: 4.4.71
* CyberArk Version: 11.1.0

**Additional context**
Any assistance is appreciated.

**Comment by pspete** [comment]
This is covered in the documentation: https://pspas.pspete.dev/docs/search/#classic-api

If you use the `safe` or `keyword` parameters, then the request will go to the legacy/classic API endpoint and only a single result will be returned.

Consider using the parameters specific to the updated gen2\v10 API:

```powershell
Get-PASAccount -SafeName mysafe
```

**Comment by gregmarnie** [comment]
When I use the command, Get-PASAccount -SafeName mysafe, I get the error...

PS H:\cyberark\audit\output> get-pasaccount -SafeName mysafe
Get-PASAccount : A parameter cannot be found that matches parameter name 'SafeName'.
At line:1 char:16
+ get-pasaccount -SafeName mysafe
+                ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PASAccount], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-PASAccount

**Comment by gregmarnie** [comment]
Error didn't go through

Get-PASAccount : A parameter cannot be found that matches parameter name 'SafeName'.
At line:1 char:16

**Comment by pspete** [comment]
Unable to reproduce.
It is a valid parameter: https://pspas.pspete.dev/commands/Get-PASAccount#parameters

https://github.com/pspete/psPAS/blob/7432e6470944c5431016f8c703b34dc14fd93793/psPAS/Functions/Accounts/Get-PASAccount.ps1#L198-L203

**Comment by gregmarnie** [comment]
Yeah, I think this one is on me.  I upgrade to the latest PSPAS but had an older version in my path.  Once I cleaned that up, I'm able to utilize the -SafeName parameter.  My apologies, this may be closed.  Thanks for the very quick turn around on information.
