### ISSUE TITLE
How to usr psPAS work with Okta

### ISSUE THREAD

**Issue by aitayi1982** [pspete/psPAS#321]
I wrote an scripts to auto checkout password from customer's CyberArk system, it works before our customer apply Okta an 2FA system.
Could you please advice how to use New-PASSession login with Okta (which need phone app : Okta verify) integrated CyberArk system?

**Comment by pspete** [comment]
Not enough details have been to give an answer.
You can find examples on RADIUS auth here: https://pspas.pspete.dev/docs/authentication/#radius-authentication
Also check the closed issues to see if any of them may help.

**Comment by pspete** [comment]
No update, so closing.
If you still face an issue, please log a new issue including the relevant details (code sample, version, error message etc).
