### ISSUE TITLE
PSMConnect Capabilities?

### ISSUE THREAD

**Issue by noahbliss** [pspete/psPAS#322]
Hey pspete,

Love your project, but was curious if there was any intention of implementing psmconnect capabilities in there? I wasn't able to find API documentation on it, but it looks like the request to fetch the generated RDP files is actually quite simple. I was able to implement this capability in Julia but the sysadmins in my org who aren't on Linux workstations are getting jealous. :P

The code I wrote for this is here: 

Basic usage from the readme: https://github.com/noahbliss/CyberArkPVWAClient.jl

Source code for the actual function:
https://github.com/noahbliss/CyberArkPVWAClient.jl/blob/eb7d90c699fb058dec68bb8e71f08f2b55a74575/src/CyberArkPVWAClient.jl#L60

I'd be happy to discuss details and provide better insight into the method used when I'm not typing this on a phone keyboard. 

Thanks!
Noah

**Comment by pspete** [comment]
Hi Noah

See: https://pspas.pspete.dev/commands/New-PASPSMSession

**Comment by noahbliss** [comment]
Right on! Sorry for the wayward feature request. Thanks again.
