### ISSUE TITLE
Unable to establish PASSession

### ISSUE THREAD

**Issue by hlj013** [pspete/psPAS#323]
**Describe the issue**
When I run the PASSession command I get no result, but no error either and get error 500 when I try to run other commands that require the session.  I confrimed that I can logon to the URL with the creds supplied.

**To Reproduce**
1. $t = New-PASSession -Credential $cred -BaseURI https://pvwa.domain -type LDAP
2. 
3. 

**Expected behavior**
I expect $t to have the PAS Session information and be able to utilize it to run commands against our CyberArk 
**Screenshots & Console Output**
DEBUG: [Body] {
    "password":  "******",
    "username":  "Username"
}
VERBOSE: POST https://pvwa.domain/PasswordVault/api/Auth/LDAP/Logon with -1-byte payload
VERBOSE: received 182-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://pvwa.domain/PasswordVault/WebServices/PIMServices.svc/Server with 0-byte payload

Console Output Code Block:
```powershell


```

**Your Environment**

* PowerShell Version: 5.1.14393.3866
* psPAS Version: 4.4.71
* CyberArk Version: 10.9.0.15

**Additional context**

**Comment by pspete** [comment]
Hi @hlj013 , that is expected behaviour.

This command will return the session data if it is needed: 
https://pspas.pspete.dev/commands/Get-PASSession

**Comment by hlj013** [comment]
Thank you for your response.  I had already tried the Get_PASSession command.  Here is my result:
get-PASSession
VERBOSE: GET https://pvwa.domain/PasswordVault/WebServices/PIMServices.svc/User with 0-byte payload
Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At line:209 char:19
+ ... $APIResponse = Invoke-WebRequest @PSBoundParameters -ErrorAction Stop
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by pspete** [comment]
Check closed issues for previous reports of 500 errors to see the ways in which they have been resolved for others:

#106 
#201 
#246 
#267

**Comment by pspete** [comment]
Any update? do you still need the issue open?

**Comment by pspete** [comment]
Closing, no updates.
