### ISSUE TITLE
2FA Authentication

### ISSUE THREAD

**Issue by jonnadulasudhakar** [pspete/psPAS#328]
The current authentication is not covered all 2FA.

Some of the 2FA is configured to issue secret code by SMS or mobile application after LDAP authentication.

Please help to include the logic to cover the above 2FA.

**Comment by pspete** [comment]
Hi.
Please include all the relevant details in the issue report.
What error do you receive when attempting 2FA currently?
psPAS already had logic to deal with OTP sent via SMS or mobile application after initial authentication.

**Comment by pspete** [comment]
Any further details you can provide @jonnadulasudhakar ?

**Comment by jonnadulasudhakar** [comment]
I am still not able to use the Radius authentication.

Here is the sequence:
Login to PVWA
Enter credentials
After LDAP authentication, we prompted with OTP screen
The sms will be sent to user mobile after authentication 

How do we get OTP and get authenticate.

Thanks,
Sudhakar

**Comment by jonnadulasudhakar** [comment]
Please ignore my comments.
I am able to login 
New-PASSession -Credentials $ced -BaseURI HTTPS://pvwa -type RADIUS

System prompted with OTP and after entering the OTP, I got success authentication.

Thanks for providing useful information 🙏🏻🙏🏻

**Comment by pspete** [comment]
Thanks for the update - will close the issue
