### ISSUE TITLE
CyberArk SAML Authentication with Microsoft MFA

### ISSUE THREAD

**Issue by derrickberg-dev** [pspete/psPAS#329]
**Describe the issue**
When attempting to perform SAML authentication using Microsoft MFA, I am unable to authenticate.

**To Reproduce**
1. Setup CyberArk with SAML authentication using Microsoft's MFA with mobile device prompt method
2. Attempt to authenticate using the SAML method
3. Error is thrown "Failed to get SAMLResponse"

**Expected behavior**
The SAML authentication to work with Microsoft's MFA but I can tell by looking at the code that it wouldn't. I tried to do it manually with powershell, but i couldn't get powershell to hold more than 1 cookie from the session. 

It seems that when authenticating with Microsoft's MFA, using the option for an authentication prompt to popup on your mobile device, there is an embedded form being refreshed in the browser until you have accepted the prompt. I also have the option to use a OTP token which I think I would much rather do then try to figure out how to get powershell to work with Microsoft's MFA unless there is a powershell module that microsoft has for this, but I couldn't find it. I can't figure out how I would cause Microsoft's MFA to go to OTP mode from CyberArk when its defaulting to the prompt on a mobile device.

**Environment**

* PowerShell Version: 7
* psPAS Version: 4.5.9
* CyberArk Version: 11.5

**Additional context**
I've been using radius authentication but the cyberark admin wants to switch to SAML.

**Comment by pspete** [comment]
Thanks for the report @derrickberg-dev – I’ll need to create a new dev environment to look at this (so any fix may take some time).

If you want to/are able to assist/contribute to development/testing it would be most welcome. The [issue-329 branch](https://github.com/pspete/psPAS/tree/issue-329)  has been created for this purpose.

The current SAML auth code included in the module is based on [this gist](https://gist.github.com/infamousjoeg/b44faa299ec3de65bdd1d3b8474b0649).

**Comment by pspete** [comment]
An issue in the module which raised an error when attempting SAML authentication has been resolved.
SAML auth under conditions where SSO using the default credentials to the IdP is possible now functions.
Tested against ADFS on Server 2019.

A new "`SAMLResponse`" parameter has been added, this allows a user to provide their own saml response to the module for use in the authentication flow; if needed, your own custom code can now be used to authenticate to Saml provider where additional logic or credentials & 2FA are required to achieve this.

Changes currently present in the Dev branch, and will be released in the next published version of the module

**Comment by aitayi1982** [comment]
Hi Team.
Good News for SAML auth.
Could you please advice when we can use this new function, or is there any beta version which we can use to test saml.
Thanks.
