### ISSUE TITLE
The cmdlet Unlock-PASAccount is confusing

### ISSUE THREAD

**Issue by jasonwbarnett** [pspete/psPAS#330]
**Describe the issue**

When looking to check-in a credential it took me a while to figure out that Unlock-PASAccount cmdlet was the check-in cmdlet I needed.

I think something like `Checkin-PASAccount` would be much clearer and more accurately describes the intent.

**Comment by pspete** [comment]
Hi @jasonwbarnett .
Unfortunately the suggestion is not listed in the powershell approved verbs list:
https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1

Some documentation has been recently added to the psPAS site to try and lessen any confusion around where specific api functionality exists in the module:  https://pspas.pspete.dev/commands/

An alternative would be to set up a local alias to the command.

**Comment by jasonwbarnett** [comment]
This is nice! 👍 

Thank you, Pete.

p.s. did you ask Microsoft to add a verb for us? 😉
