### ISSUE TITLE
Search Deleted Items/Restore Object

### ISSUE THREAD

**Issue by dokki767** [pspete/psPAS#332]
This is more of a question so sorry if not psPAS 'issue', is there a switch or special cmdlet to search 'deleted items' via the API and also restore them?  Native search functions seem to not 'see' those deleted items.

* PowerShell Version: 5.1
* psPAS Version: 4.4.80
* CyberArk Version: 11.4

**Comment by NathanielMaier** [comment]
This seems like a better question for CyberArk - I'd suggest you open a support case with them to ask if the REST API supports any actions for deleted account objects. My assumption is _no_, it does not, in which case you could submit an Enhancement Request with CyberArk. Only after that functionality exists within the REST API could psPAS then implement it with PowerShell.

As a (albeit painful) workaround, you should be able to use the PACLI [UNDELETEFILE](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PACLI/Folder-and-File-Functions.htm?tocpath=Developer%7CCommand%20Line%20Interface%20(PACLI)%7C_____6#UndeleteFile) command (even via [PoShPACLI](https://github.com/pspete/PoShPACLI) `Restore-PVFile`).

**Comment by dokki767** [comment]
That's kind of what I was thinking too.  I do have an active support case open, I can update this issue with their response for documenting the current approach in case other users have similar questions.

**Comment by pspete** [comment]
There is no documented method for the feature described - your usual support channels or an ER with the vendor is the way to go.
