### ISSUE TITLE
CyberArk 11.2.0 does not meet the minimum version requirement of 11.4 for Get-PASPlatform (using ParameterSet: targets)

### ISSUE THREAD

**Issue by jhonyczev** [pspete/psPAS#333]
**Describe the issue**
When I execute de Get-PASPlatform cmdlet it gives me an error: CyberArk 11.2.0 does not meet the minimum version requirement of 11.4 for Get-PASPlatform (using ParameterSet: targets)

I understand that this capability is enabled since version 9 of cyberark.

**To Reproduce**
1. Establish the PASession
2. execute the Get-PASPlatform cmdlet

**Expected behavior**
I expect the list of platforms and attributes for the version 11.2 of cyberark

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/76976163/103588124-8bb76b00-4eb6-11eb-8bb1-f96f7b15529b.png)

Console Output Code Block:
```powershell
![image](https://user-images.githubusercontent.com/76976163/103588179-9ffb6800-4eb6-11eb-99cc-f36fce634644.png)


```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version:4.5.90
* CyberArk Version: 11.2.0

**Additional context**

**Comment by pspete** [comment]
The function defaults to the latest supported API which requires at least 11.4.
For 11.2, the `platforms` ParameterSet can be used: https://pspas.pspete.dev/commands/Get-PASPlatform#platforms
The `PlatformType` and/or `Search` parameters will need to be specified.
