### ISSUE TITLE
Add-passafe API unbale to resolve parameter

### ISSUE THREAD

**Issue by amitgautam1990** [pspete/psPAS#335]
I am trying to execute Add-passafe API to create safe user executing the API has add safe access but upon execution I a  getting error:

Unable to resolve parameter from defined parameters

Add-passafe -SafeName abc -Description "test safe" -ManagingCPM Passwordmanager -NumberOfVersionsRetention 5 NumberOfDaysRetention 7

It gives an error:  

Add-passafe : parameter set cannot be resolved using specified named parameters.

**Comment by pspete** [comment]
Check the valid syntax here: https://pspas.pspete.dev/commands/Add-PASSafe#syntax
