### ISSUE TITLE
Is this possible to include Get-pasdirectoriesdetails?

### ISSUE THREAD

**Issue by engkeen-source** [pspete/psPAS#336]
This is possible and support by CyberArk but haven't implement in pspas

**Is your feature request related to a problem? Please describe.**

It's an enhancement request. Not a problem.

The objective is to fetch user from ldap and add to safe. This user is not exist in vault and haven't create in vault. 

**Describe the solution you'd like**
Able to fetch user from ldap by get-directory details.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**

**Comment by NathanielMaier** [comment]
Hi @engkeen-source, I'm not sure I understand this request completely. Are you trying to use [`Add-PASSafeMember`](https://pspas.pspete.dev/commands/Add-PASSafeMember) to add an LDAP/directory user or group with access to a Safe? The `-SearchIn` parameter can be used to find that user/group within a defined directory map even if that user/group does not currently exist in the Vault.

If that's not relevant to your situation, could you share some sample code or any errors you're seeing today?

**Comment by engkeen-source** [comment]
Thank you so much. It's working.
