### ISSUE TITLE
Radius menu formatting 

### ISSUE THREAD

**Issue by theOriginalKlaatu** [pspete/psPAS#338]
Using radius with multiple choices, it would be nice if the menu presented weren't all on one line:
![image](https://user-images.githubusercontent.com/81260235/112202962-ff2c6700-8bdf-11eb-8d1f-b11cf1bdb17b.png)

It would be nice to see each choice on a new line.

**Comment by pspete** [comment]
The string is received from the RADIUS server; not sure any provision to parse and format an unknown arbitrary string value can be developed easily.

**Comment by pspete** [comment]
As far as I can tell (through albeit limited research), even if the RADIUS challenge message _should_ be pre-formatted with line breaks, these appear to be removed before being returned as an exception message from the API.

Closing as the message format/options can change between implementations/solutions - current behaviour works in the same way for all.
