### ISSUE TITLE
Radius menu with multiple levels

### ISSUE THREAD

**Issue by theOriginalKlaatu** [pspete/psPAS#339]
Description
When presented with a radius authentication menu in new-passession, if you select an option with sub-options, the module exits

**To Reproduce**
1. New-PASSession -Credential $Creds -BaseURI https://$CorePAS -type RADIUS -OTPMode Challenge
2. Select option with sub-option

**Expected behavior**
To accept second menu option

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/81260235/112203847-f7b98d80-8be0-11eb-81b0-5fbc0c8adc71.png)

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1 and 7.1
* psPAS Version: 4.5.90
* CyberArk Version: 11.2.0.18

**Comment by pspete** [comment]
Hi @theOriginalKlaatu - is there a chance you can test the updated code currently published to the [issue-339](https://github.com/pspete/psPAS/tree/issue-339) branch, or the [psPAS-v5.0.1.zip](https://ci.appveyor.com/project/pspete/pspas/build/artifacts) build artefact available from Appveyor?

I do not have a RADIUS implementation available to me which produces sub-options in the way you highlight, but have mocked the behaviour in the module's unit tests and provide this update after some test driven development based on those unit tests.

Any presented RADIUS challenge sub-options should now be able to be responded to.

**Comment by theOriginalKlaatu** [comment]
That sure seems to work in both 5.1 and 7.1.3.   Thank you!  I'll keep testing

**Comment by pspete** [comment]
Update promoted into the `dev` branch - it will be part of the next module release.
Thanks for the report 👍
