### ISSUE TITLE
Issue in New-PASSession

### ISSUE THREAD

**Issue by kruhmann** [pspete/psPAS#34]
Hi,

it seems there is a small issue in New-PASSession.ps1 Line 139
$boundParameters = $PSBoundParameters | Get-PASParameter**s** -ParametersToRemove Credential

Get-PASParameter**s** -> Get-PASParameter

Kr Konstantin

**Comment by pspete** [comment]
Hi @kruhmann - good spot - you are right
I did go through and rename some function based on the recommendations of PSScriptAnalyzer ("use singular nouns").

An alias `[Alias("Get-PASParameters")]` was added to the `Get-PASParameter` function when it was renamed to allow the existing code to continue to work without requiring an update of all functions that call it.

Calls to `Get-PASParameters` do end up getting processed by `Get-PASParameter`

Do you experience an issue around this? I can perform a module wide update (find/replace) if required.

**Comment by kruhmann** [comment]
Hi @pspete 
well yes. I have downloaded the ps module as a zip and copied them to "C:\Windows\System32\WindowsPowerShell\v1.0\Modules" (WIN2K12). I have renamed the folder as mentioned in the readme. When i try to run the following script:

>Import-Module psPAS
>$Credential = Get-Credential
>$token = New-PASSession -Credential $Credential -BaseURI "https://ark.child.Forest.local" -PVWAAppName PasswordVault

Then I receive the following error messages:
>Get-PASParameters` : The term 'Get-PASParameters' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\psPAS\Functions\Authentication\New-PASSession.ps1:139 char:43

Sry, I have no experience in using aliases and I do not know why it doesn't work in this case. A find/replace would help me :).

Kr Konstantin

**Comment by pspete** [comment]
I do not know why that maybe, so will work on the update.
The Alias is exported, at least on my machine:
```powershell
> Get-Command Get-PASParameters -Module pspas

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Get-PASParameters                                  0.1.0      pspas
```
Thanks for the report.

Pete

**Comment by kruhmann** [comment]
Maybe this is our problem?
https://stackoverflow.com/questions/1978355/unable-to-create-a-powershell-alias-in-a-script-module

"By default, Windows PowerShell modules only export commands (functions or cmdletS), and not variables or aliases."
>Export-ModuleMember -Function * -Alias *

**Comment by pspete** [comment]
Hi @kruhmann - 
Thanks for logging the issue.

Fix deployed - tested as working/no impact this end (but I was not seeing what you reported....).
Let me know how you get on or if this needs reopening.

Pete

**Comment by kruhmann** [comment]
It is working now. Thank you and thanks for sharing these ps tools! :+1: 

Kind regards
Konstantin
