### ISSUE TITLE
abililty to get all properties from an account or vault

### ISSUE THREAD

**Issue by RedbeardBE** [pspete/psPAS#347]
**Is your feature request related to a problem? Please describe.**
when performing a lookup on an account or vault, only a subset of properties are available, instead of all properties. For example, at this moment the property description is not available.
when looking up all accounts in a safe, i only get these properties: AccountID, Safe, address, userName, name, platformId, secretType, platformAccountProperties, secretManagement, createdTime, categoryModificationTime

**Describe the solution you'd like**
get-pasaccount will give me all properties of the account, no matter the platformtype, like: description, applicationID, DirectoryID,...

**Describe alternatives you've considered**
none

**Additional context**

**Comment by pspete** [comment]
Hi @RedbeardBE 
`Get-PASAccount` just presents back nicely formatted objects containing date received from the API, there is no logic to exclude or include only certain data or properties.

As shown in the screenshot, there is no issue with psPAS displaying any properties/values (`AccountDescription`, `ApplicationID`, `DirectoryID`, `SomeOtherProperty`) for an account when they are returned by the API:

![image](https://user-images.githubusercontent.com/10600090/117059395-ad671880-ad17-11eb-9273-1ceefa6b6fcc.png)

If you are not getting expected data back from the API, please check your configuration.

**Comment by pspete** [comment]
Closing as there is no fix to be applied in the code of the module.
