### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by davekpatrick** [pspete/psPAS#357]
Any work or through of converting this great utility into a formal Terraform provider (https://registry.terraform.io). This would allow for a more direct and efficient way to interface with CyberArk PAS. currently you have to create null_resource with some provisioners that call poweshell (and use the psPAS module) but this functions somewhat less than idea. For example : proper  state management, passing/linking data between PAS entities and other terraform resources

**Comment by pspete** [comment]
Nice idea @dkp-01 .... no promises, but will look into it.

**Comment by pspete** [comment]
Closing for now - this currently isn't feasible for the project.
