### ISSUE TITLE
FEATURE REQUEST - DOCUMENTATION - LOW PRIORITY - https://pspas.pspete.dev/commands

### ISSUE THREAD

**Issue by AaronG1234** [pspete/psPAS#365]
Understandable if you determine cost of effort is to high for value.

On your website (https://pspas.pspete.dev) in the Get-Help Section (https://pspas.pspete.dev/commands/) which I personally love just for its readability and "hyperlink navigation" (thank you for taking the time)

**Current:**
When you choose a topic in the left "Navigation Pane", in order to view the contents of that topic in the right "Reading Pane", the left navigation always resets to the top.  So if I was reading about Get-PASUser (a topic near the bottom of the navigation), and then wanted to look at Set-PASUser (a topic right around Get-PASUser, at the bottom of the Navigation) then I have noticed I need to pull the navigation all the way back down.

TRIVIAL & Cosmetic! 

but ... if you have the time (perhaps you want change of pace :stuck_out_tongue_winking_eye:, perhaps you share the website responsibility with someone else who is up for the challenge ), 

**Preferred:**
I would love the behavior to instead be that when you select a topic in the Navigation Pane, that the Navigation Pane does not change, and the topic is shown in the Reading Pane (as a guess, I'm going to bet that the navigation pane is just part of every page and the link in the Navigation is just to an entire page, which is why the navigation is reset... 

AGAIN, if it isn't something you deem worth a venture, I get it.. and if it is too problematic to me, I could probably have a wack at it myself [though unfortunately I'm 10x the engineer I am the graphic designer, and it would be quite some googling :bowtie: ]

Aaron

**Comment by pspete** [comment]
Hi @AaronG1234 - thanks for the request & feedback, it's appreciated.
Agree the site is far from perfect, documentation updates are generally always on the list.
The site is generated using [a Jekyll theme](https://mmistakes.github.io/minimal-mistakes/) - short of finding a different template to use, I actually have no idea how to go about making the changes you describe a reality.
The configuration and markdown containing the content for the site all exists under the [docs folder](https://github.com/pspete/psPAS/tree/master/docs).
The [command pages](https://github.com/pspete/psPAS/tree/master/docs/collections/_commands) are also used to generate the modules help file.

As with the rest of the module, it's possible for anyone to submit a Pull Request for changes to these files too.....

**Comment by pnreddy91** [comment]
Hi
I need to operate CPM operation to bulk accounts by using CSV files and commands.
what are the parameters required in CSV file to do Reconcile or Change etc

i understand lot of thing from this,
https://github.com/cyberark/epv-api-scripts/tree/main/Account%20Onboard%20Utility
in this API scripts readme file and example CSV files also mentioned, 

Kindly help me on that above CSV files

**Comment by pspete** [comment]
@pnreddy91 - This issue is for the psPAS module and is not linked to these CSV files and unrelated to the developer/project for the URL provided.

Suggest you open a new issue in the appropriate repo: https://github.com/cyberark/epv-api-scripts/issues

**Comment by galaara98** [comment]
> Hi @AaronG1234 - thanks for the request & feedback, it's appreciated. Agree the site is far from perfect, documentation updates are generally always on the list. The site is generated using [a Jekyll theme](https://mmistakes.github.io/minimal-mistakes/) - short of finding a different template to use, I actually have no idea how to go about making the changes you describe a reality. The configuration and markdown containing the content for the site all exists under the [docs folder](https://github.com/pspete/psPAS/tree/master/docs). The [command pages](https://github.com/pspete/psPAS/tree/master/docs/collections/_commands) are also used to generate the modules help file.
> 
> As with the rest of the module, it's possible for anyone to submit a Pull Request for changes to these files too.....

Hey lets close this (your solution is elegant enough and the automation is by far more useful than my request)

Btw i switch to my other account to add a sponsor to you... I have use psPAS for probably 4 - 5 years, you deserve some help (though pizza money is all I can send)

**Comment by pspete** [comment]
@galaara98 @AaronG1234 🙏🏼 very kind of you and very much appreciated 😃
Code signing cert potential is increasing.  
Closing as per your comment, but will keep in mind if a documentation overhaul happens at any point.
