### ISSUE TITLE
New-PASSession.ps1 not working

### ISSUE THREAD

**Issue by amitgautam1990** [pspete/psPAS#369]
We have deployed pspas v5.1.21 which was working well earlier recently in order to perform bulk taks I was trying to use pspas initially we need to get token for running session so inised New-PASSession. ps1 but even after authenticaring sucessfully powershell throws an error(acreenanjit of error attached) 
![IMG_20210629_215759](https://user-images.githubusercontent.com/62834037/123834885-85fe8780-d925-11eb-97e9-299004ec9e2f.jpg)

**Comment by pspete** [comment]
@amitgautam1990 suggest providing details to show how you arrived at the error in the screenshot.
As stated, it was working previously, so either something changed in your environment, or you did something differently, like provided an incorrect parameter value.
The screenshot is not what authenticating successfully looks like.

You can always refer to the docs: https://pspas.pspete.dev/docs/authentication/

**Comment by amitgautam1990** [comment]
got it i used incorrect BaseURL with /PasswordVault instead of just IIS Server
