### ISSUE TITLE
Request-PASJustInTimeAccess missing from psPAS.psd1

### ISSUE THREAD

**Issue by markdias** [pspete/psPAS#379]
**Describe the issue**
Request-PASJustInTimeAccess isn't listed in FunctionsToExport in the psPAS.psd1

**To Reproduce**
1. Request-PASJustInTimeAccess isn't available

**Expected behavior**
Expect to be able to use Request-PASJustInTimeAccess function

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version:  5.2.52
* CyberArk Version: 11.4

**Comment by NathanielMaier** [comment]
See the [CHANGELOG](https://github.com/pspete/psPAS/blob/master/CHANGELOG.md#module-update-to-cover-all-cyberark-122-api-features):
> Breaking Changes
`Request-PASJustInTimeAccess`
Command renamed from `Request-PASAdHocAccess` in line with CyberArk feature

**Comment by markdias** [comment]
> See the [CHANGELOG](https://github.com/pspete/psPAS/blob/master/CHANGELOG.md#module-update-to-cover-all-cyberark-122-api-features):
> 
> > Breaking Changes
> > `Request-PASJustInTimeAccess`
> > Command renamed from `Request-PASAdHocAccess` in line with CyberArk feature

Yes its been changed to [`Request-PASJustInTimeAccess`](https://github.com/pspete/psPAS/blob/master/psPAS/Functions/Accounts/Request-PASJustInTimeAccess.ps1) however its missing from [psPAS.psd1](https://github.com/pspete/psPAS/blob/master/psPAS/psPAS.psd1) file. The [psPAS.psd1](https://github.com/pspete/psPAS/blob/master/psPAS/psPAS.psd1)  still contains `Request-PASAdHocAccess`,

**Comment by pspete** [comment]
Good spot @markdias - will fix
