### ISSUE TITLE
Set-PASSafe not working with Gen2 API 

### ISSUE THREAD

**Issue by alexR148** [pspete/psPAS#383]
**Describe the issue**
Missing Parameter SafeName in Body. Errorcode 400

**To Reproduce**
Just use the function Set-PASSafe Gen2 

**Expected behavior**
The safe should be updated

**Additional context**
The error can be fixed by replacing the line 101 of Set-PASSafe with the line
$BoundParameters = $PSBoundParameters | Get-PASParameter -ParametersToRemove NewSafeName

**Comment by engkeen-source** [comment]
I face this issue as well when using set-passafe gen2
