### ISSUE TITLE
Use SAMLInteractive authentication, but get [400] Authentication failure

### ISSUE THREAD

**Issue by aitayi1982** [pspete/psPAS#387]
**Describe the issue**
I work with SAML authentication, but get error : [400] Authentication failure

**To Reproduce**
1.  $loginURL = "https://pvwa-company/PasswordVault/"
2. $loginResponse = New-SAMLInteractive -LoginIDP $loginURL
3. $baseURL = "https://pvwa-company/"
4. New-PASSession -SAMLAuth -concurrentSession $true -BaseURI $baseURL -SAMLResponse $loginResponse

**Expected behavior**
I should get PASSession successfully. I can get SAML response, but can not pass authentication.

**Screenshots & Console Output**

```powershell

<--Console Output Goes Here-->
Invoke-PASRestMethod : [400] Authentication failure. Please contact your Administrator.
At line:445 char:19
+                 $PASSession = Invoke-PASRestMethod @LogonRequest
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"P...dministrator."}:ErrorRecord) [Invoke-PASRestMethod], Ex
   ception
    + FullyQualifiedErrorId : PASWS035E,Invoke-PASRestMethod
```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.5
* psPAS Version: psPAS-v5.2.59
* CyberArk Version: V10

**Additional context**

**Comment by pspete** [comment]
You should find additional detail behind the generic error message being returned in your pvwa logs.

**Comment by jessegri** [comment]
I'm seeing the same error with Powershell 5.1 and PSPas 5.2.52 and CyberArk v10

Category   : NotSpecified
Activity   : Invoke-PASRestMethod
Reason     : Exception
TargetName : {"ErrorCode":"PASWS035E","ErrorMessage":"Authentication failure. Please contact your Administrator."}
TargetType : ErrorRecord

**Comment by pspete** [comment]
@jessegri ,
Check pvwa logs to identify underlying cause.

**Comment by pspete** [comment]
@jessegri , @aitayi1982 - any further details in the logs which could help?
