### ISSUE TITLE
How to get login url for  New-SAMLInteractive cmd

### ISSUE THREAD

**Issue by aitayi1982** [pspete/psPAS#391]
**Describe the issue**
How to get login url for  New-SAMLInteractive cmd
eg:
$loginURL = "https://pvwa-mycompany/PasswordVault/"
$loginResponse = New-SAMLInteractive -LoginIDP $loginURL
After issue this command the popup window do not redirect to login page.
So I think the login url is not correct, but How to get correct login url for  New-SAMLInteractive cmd

**Comment by pspete** [comment]
That's a different project to psPAS.
It looks like you are trying to use your pvwa url instead of the idp initiated saml authentication url.

https://github.com/allynl93/PS-SAML-Interactive#usage
