### ISSUE TITLE
Convert Boolean parameters to [switch]

### ISSUE THREAD

**Issue by theramiyer** [pspete/psPAS#396]
**Is your feature request related to a problem? Please describe.**

Presently, the module contains cmdlets that take in a `[Boolean]` input. This makes calling cmdlets like:

```powershell
Get-PASUser [...] -ComponentUser $true
```

**Describe the solution you'd like**

Could these be converted to the `[switch]` type? This _will not_ affect functionality within the functions, or when splatting. Only when calling these parameters, we’d need to just name the parameter, and not pass a `$true` or a `$false` explicitly.

**Describe alternatives you've considered**

No alternatives considered. Just sticking to the PowerShell conventions.

I can do this and raise a PR. Please let me know.

**Comment by pspete** [comment]
Hi @theramiyer - initial thoughts are that this feature would likely not be considered for inclusion into this version of the project. Is it intended to fix any particular issue? To the best of my knowledge, the module already follows PowerShell conventions as well as community best practice.

The parameters of course could be changed into `switch` type, but based on the way the module uses the current parameter types to convert `$PSBoundParameters` into correctly formatted JSON for the API requests, this would require refactoring the internal logic of the module. 

Consider the following example, in essence this is how the functions are currently working:

```powershell
Function Some-Function{
    Param(
    [Boolean]$Boolean,
    [Switch]$Switch
    )

    $PSBoundParameters | ConvertTo-Json
}
```

Boolean parameters are able to are converted and declared correctly in JSON, along with parameters of other types contained in `PSBoundParameters`:

```powershell
Some-Function -Boolean $false

{
    "Boolean":  false
}


Some-Function -Boolean $true

{
    "Boolean":  true
}
``` 

Switch parameters would need to be converted back to boolean to ensure the JSON was in the format required by the api:

```powershell
Some-Function -Switch

{
    "Switch":  {
                   "IsPresent":  true
               }
}
```
To toggle a setting `off`, a different command syntax is required where a boolean value would have to be provided by a user, or in code, regardless:
```powershell
Some-Function -Switch:$false

{
    "Switch":  {
                   "IsPresent":  false
               }
}
```
Aside from the above, this is a major breaking change for any existing scripts, example code, test scripts, project documentation etc as well as a change in behaviour for all users; I think at least a strong reason (security, performance, stability) for the effort & disruption and/or support from other users is needed.

**Comment by pspete** [comment]
no additional detail on the need for this feature request, so closing.
