### ISSUE TITLE
Code Runs but does not reach out to PVWA server and does nothing

### ISSUE THREAD

**Issue by koushik2296** [pspete/psPAS#399]
**Describe the issue**
A concise summary of the issue
Code runs without error . Trying to remove account if its not on domain. NO error in Code but any psPas function doesnt work. What could be the issue ? The psPAS is run from powershell CPM machine and not able to reach out to PVWA server .
**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell

<--Console Output Goes Here-->

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.1776
* psPAS Version: 5.1.37
* CyberArk Version: 12.2 [ runnin
[pspas_script.txt](https://github.com/pspete/psPAS/files/8994043/pspas_script.txt)
g the script from CPM ]

**Additional context**

**Comment by koushik2296** [comment]
Yes that works

**Comment by koushik2296** [comment]
I am able to reconcile an account as well, but the original code doesnt work

**Comment by koushik2296** [comment]
If the account is disabled by CPM , does the -reconciletask work ?

**Comment by pspete** [comment]
Believe this provides a route to progressing from your reported issue and confirms the module works as expected.
No updates or fixes are required to be applied to the module code, but your original script does need some attention.

**Comment by koushik2296** [comment]
Got the Code working , Thank you ... The new module for the code needed modifications..
