### ISSUE TITLE
Add support for new Shared Services platform

### ISSUE THREAD

**Issue by hjbotha-cybr** [pspete/psPAS#402]
**Is your feature request related to a problem? Please describe.**
CyberArk have just released a new platform which changes the way users are managed in Privilege Cloud. It's not possible to log on to the platform with the existing methods.

I've added initial support for the new platform in a fork here which you can use as an example:
https://github.com/hjbotha-cybr/psPAS

This adds support for logging on using an OAuth confidential client.

**Describe the solution you'd like**
Support for the new platform! The changes are:
- Authentication process has changed
- There's no user management against Privilege Cloud in the new platform. User management is against Identity instead, and thus is probably out of scope for this library.

**Describe alternatives you've considered**
I tried to see if it was possible to authenticate another way but none of the existing methods seemed feasible.

**Additional context**
Since authentication is now provided by Identity instead of Privilege Cloud handling it itself, authentication is done against a different domain. Therefore I have added an argument - LogonBaseUri.
The response we get when authenticating is now a JSON object, like this:
```
 {
    "access_token": "<~1700 character token>",
    "token_type": "Bearer",
    "expires_in": 900
}
```
We use it by passing an Authorization header with content:
```
Bearer <access_token>
```

**Comment by hjbotha-cybr** [comment]
Hi Pete,

Thus far, this library has been working perfectly with Privilege Cloud as is, so I feel the latter option is viable (creates a session which can be imported using Use-PASSession).

There are a few additional differences apart from authentication. Would you be open to accounting for these in other cmdlets where possible?

For example, the MemberType value in [Add Safe Member](https://docs.cyberark.com/Product-Doc/OnlineHelp/PrivCloud-SS/Latest/en/Content/WebServices/Add%20Safe%20Member.htm) is now mandatory, so that would need to be added as a parameter in Add-PASSafeMember.

**Comment by pspete** [comment]
open to it yes of course.
will need some thought as to if or how to make parameters like this mandatory for PCloud, but not for Self-Hosted...

**Comment by hjbotha-cybr** [comment]
I think generally we can do without the distinction and leave it up to the user to add as required. Any alternative might require either a kludge to detect when it's the new platform (like checking the URL), or a change to the `psPAS.CyberArk.Vault.Session` object. This is further complicated by the fact that there are currently two flavours of Privilege Cloud.

In the meantime I've drafted a short script to create a session object that Use-PASSession can import: https://github.com/hjbotha-cybr/New-CyberarkPlatformSession

I'll let you know about any other changes I become aware of.

Thanks!

**Comment by walidhammad** [comment]
@hjbotha-cybr thank you that helped me

**Comment by nidhinckgithub** [comment]
@hjbotha-cybr Thanks a lot. Finally, I can authenticate :)

**Comment by pspete** [comment]
Added support for this now, see [Example 23](https://pspas.pspete.dev/commands/New-PASSession#example-23)
