### ISSUE TITLE
Support for PKI and PKIPN Authentication

### ISSUE THREAD

**Issue by pnewman364b** [pspete/psPAS#404]
**Is your feature request related to a problem? Please describe.**
We make use of YubiKey authentication and would like to use that through our scripts that use psPAS.

**Describe the solution you'd like**
The ability to authenticate using YubiKey(s).

**Describe alternatives you've considered**
Using the CyberArk RestAPI and updating scripts to use some or none of the code developed using psPAS.

**Additional context**
While we authenticate with YubiKey(s), it is only one part of our authentication. After authenticating through the YubiKey, the CyberArk logon page is configured then to ask for the end user's LDAP credentials.

**Comment by pspete** [comment]
Hi @pnewman364b - may have some time to start looking at this soon, can you provide some more context to better enable any development effort and configuration of the module's development environment?
- What authentication method is configured for an authenticating user in CyberArk? (Is it LDAP? or is it PKI? Other?) 
- When logging into PVWA:
  - IIS Prompts for a certificate which is stored on the YubiKey?
  - When choosing PKI PVWA authentication, The username of the LDAP user is auto-populated from the certificate? 

What behaviour do you see when attempting authentication using a command like, or similar to [EXAMPLE 16](https://pspas.pspete.dev/commands/New-PASSession#example-16) from the documentation?
`New-PASSession -Credential $cred -BaseURI https://PVWA -type LDAP -Certificate $Certificate`
Where `$certificate` references a certificate object enumerated from the YubiKey?

**Comment by pspete** [comment]
Initial iteration of this functionality now in the codebase under development for the next release.

if you are able to test, there is a [dev build available here](https://ci.appveyor.com/project/pspete/pspas/build/artifacts)

Also added this example, with which a certificate from a PIN protected YubiKey was able to be selected & used:

```powershell
Add-Type -AssemblyName System.Security
# Get Valid Certs
$MyCerts = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](Get-ChildItem Cert:\CurrentUser\My)
# Select Cert
$Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectFromCollection(
    $MyCerts,
    'Choose a certificate',
    'Choose a certificate',
    'SingleSelection'
) | select -First 1

New-PASSession -Credential $cred -BaseURI $url -type PKI -Certificate $Cert
```

All going well, will make it into the next release 👍

**Comment by pspete** [comment]
@pnewman364b - added this is the 5.4 release available via the usual channels now.
Enjoy :)

**Comment by pnewman364b** [comment]
Thank you!

Paul, Newman
Senior Systems Engineer (Security), Privileged Access Management (PAM)

***@***.***

480 Crosspoint Parkway, Getzville, NY 14068
Preferred Contact - Teams
Direct – 716-253-1895
***@***.******@***.***>  |  centene.com<http://www.centene.com/>

Transforming the health of the community, one person at a time
***@***.*** ***@***.***  ***@***.***

©2022 FORTUNE Media IP Limited. Used under license.
