### ISSUE TITLE
Set-PASUser - "GUI" is not included in ValidateSet, in unAuthorizedInterfaces parameter

### ISSUE THREAD

**Issue by KimChr** [pspete/psPAS#405]
In Set-PASUser, the parameter unAuthorizedInterfaces do not include "GUI" in ValidateSet.

**To Reproduce**
1. Get-PASUser -id <ID of user that do not have GUI in authorized interfaces> | Set-PASUser

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/32736377/183889034-6cd9f1c7-e65f-4f1b-a49b-190aa447c674.png)

```powershell
PS C:\Data> get-pasuser -id 519 | set-pasuser
Set-PASUser : Cannot validate argument on parameter 'unAuthorizedInterfaces'. The argument "GUI" does not belong to
the set
"PIMSU,PSM,PSMP,PVWA,WINCLIENT,PTA,PACLI,NAPI,XAPI,HTTPGW,EVD,PIMSu,AIMApp,CPM,PVWAApp,PSMApp,AppPrv,AIMApp,PSMPApp"
specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:23
+ get-pasuser -id 519 | set-pasuser
+                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (@{enableUser=Fa...[]; location=\}:PSObject) [Set-PASUser], ParameterBindin
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-PASUser
```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version: 5.2.59 (but also missing in 5.3.69)
* CyberArk Version: 12.2

**Comment by pspete** [comment]
Thanks for the report @KimChr 
The current code is based on the listed values in documentation [here](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/12.6/en/Content/WebServices/Users%20Web%20Services%20-%20Update%20User.htm#Bodyparameters), which does not include GUI.
GUI would be a valid value though, so no issue adding it in. We can get it into the next release 👍

**Comment by pspete** [comment]
`GUI` added to `New-PASUser` & `Set-PASUser`
