### ISSUE TITLE
Add-PASAccount : Invoke-PASRestMethod 400

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#406]
Hi,

I'm new to psPAS and need to add accounts to CyberArk via API.

After running Add-PASAccount cmdlet, I receive the following error:
 
ErrorRecord) [Invoke-PASRestMethod], Exception
  + FullyQualifiedErrorId : 400,Invoke-PASRestMethod
 
The cmdlet parameters seems to be good and I ran add-PASSafe and it worked good !!

I added -ErrorVariable to cmdlet to get more information and got:
The server encountered an error processing the request
 
Any suggestion here ?

**Comment by pspete** [comment]
@arkayali - refer to the troubleshooting steps here: https://pspas.pspete.dev/docs/troubleshooting/ 
and the command documentation here: https://pspas.pspete.dev/commands/Add-PASAccount

Consider providing the details requested in the issue template to better enable any assistance.
Feel free to close this issue and start a new one if that is easier.

**Comment by pspete** [comment]
See #407
