### ISSUE TITLE
Get-PasAccount : View all results when passing multiple keywords 

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#408]
**Describe the issue**
the cmdlet returns only the first result not all of them

**To Reproduce**
Get-PASAccount -keywords "unixcsrs, unixvl1399"

**Expected behavior**
There are 8 matching, but it displays one only
 
**Screenshots & Console Output**

![image](https://user-images.githubusercontent.com/44178884/184675320-94bbba11-ccee-424a-9d9b-88ed7cbfafc7.png)

The below screen shows that I can't pass multiple keywords unless I have then between " " 

![image](https://user-images.githubusercontent.com/44178884/184675545-1cf670ac-3774-480b-8180-bfb935376ce9.png)

<--Console Output Goes Here-->

WARNING: 8 matching accounts found. Only the first result will be returned 

**Your Environment**

* PowerShell Version: 5
* psPAS Version: 5.3.69
* CyberArk Version: 11.5

**Additional context**

**Comment by pspete** [comment]
Hi @arkayali - this is covered, in some depth, in various pages in the docs: https://pspas.pspete.dev/docs/search/#gen1-api
Hopefully most of your questions are already covered there

**Comment by pspete** [comment]
closing as this is expected/documented behaviour.
feel free to comment if you feel it should be reopened.
