### ISSUE TITLE
Having issue with adding ExtraPass3Name 

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#414]
**Describe the issue**
Not able to add ExtraPass3Name - ExtraPass3Safe to an account during onboarding or even after onboarding 
During onboarding using : Add-PASAccount 
returns a message that  ExtraPass3Name is not valid for the specific platform; however, this message comes with all platforms in CyberArk

After onboarding:

Using Set-PASAccount returns : Invoke-PASRestMethod : [400] Property 'ExtraPass3Name' cannot be updated

Using Set-PASLinkedAccount returns that requires 12.2 version 

**To Reproduce**
run Add-PASAccount  with -platformAccountProperties parameter
run Set-PASAccount 

**Expected behavior**
add a reconcile account to another account : ExtraPass3Name 

**Screenshots & Console Output**

![image](https://user-images.githubusercontent.com/44178884/185764124-17ef6e81-60eb-42a8-98c1-538ff995c3a2.png)
![image](https://user-images.githubusercontent.com/44178884/185764135-d1253418-23f7-42ac-8a36-8bea403019e2.png)
![image](https://user-images.githubusercontent.com/44178884/185764139-f28a5616-7285-4ef1-b64e-a9cbddc1b39d.png)
![image](https://user-images.githubusercontent.com/44178884/185764144-6d36c6c1-bd65-4759-b2f3-3574661618f8.png)

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5
* psPAS Version: 5.3.69
* CyberArk Version: 11.5

**Additional context**

**Comment by pspete** [comment]
See #314

**Comment by arkayali** [comment]
@pspete 
Thanks .. will give it a try
