### ISSUE TITLE
Set-PASLinkedAccount  alternative to add Linked Accounts in CyberArk ver 11.5

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#416]
**Describe the issue**
Set-PASLinkedAccount doesn't support version prior 12.2. I need to add a reconcile account in Bulk to existed accounts, and the cmdlet doesn't has a parameter -UseGen1API to work with version 11.5

**To Reproduce**
Set-PASLinkedAccount -AccountID 2109_139 -extraPasswordIndex 3 -name 'AD-Scheduled-CVR-epv.cpm.ad-adrec-ad.cibc.com' -safe CPM-ReconcileSafe-ER -folder root

**Expected behavior**
Need to add a Reconcile account to existed accounts in Bulk

**Screenshots & Console Output**

![image](https://user-images.githubusercontent.com/44178884/185941749-f2def0bb-690b-479d-8141-de2d74c41b47.png)

**Your Environment**
Include relevant details about your environment

PowerShell Version: 5
psPAS Version: 5.3.69
CyberArk Version: 11.5

**Comment by pspete** [comment]
Hi @arkayali - same reply on this as [yesterday](#414 )... see #314 👈🏼 
Vendor documentation for the process to achieve this in versions prior to 12.0 are here: https://cyberark-customers.force.com/s/article/Add-Reconcile-and-Login-Accounts-to-an-Account-using-V10-REST-API
There is no equivalent Gen1 API for `Set-PASLinkedAccount` - 12.2 is when this is documented as supported by the vendor: https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/Release%20Notes/RN-WhatsNew12-2.htm?tocpath=Get%20Started%7CWhat%E2%80%99s%20New%7CRelease%20Notes%7C_____17#LinkandunlinkaccountsinAccountDetailspage

**Comment by arkayali** [comment]
Thanks @pspete
