### ISSUE TITLE
Add-PASSafeMember - unable to add : Level 1 - Authorize Account Request

### ISSUE THREAD

**Issue by arkayali** [pspete/psPAS#417]
**Describe the issue**
Add-PASSafeMember - doesn't add : Level 1 - Authorize Account Request (or Level 2), however, it works fine with "Access Safe without confirmation"

**To Reproduce**

$SafeOwner2 = [PSCustomObject]@{
  UseAccounts                            = $true
  RetrieveAccounts                       = $true
  ListAccounts                           = $true
  AddAccounts                            = $true
  UpdateAccountContent                   = $true
  UpdateAccountProperties                = $true
  InitiateCPMAccountManagementOperations = $true
  SpecifyNextAccountContent              = $true
  RenameAccounts                         = $true
  DeleteAccounts                         = $true
  UnlockAccounts                         = $true
  ManageSafe                             = $true
  ManageSafeMembers                      = $true
  BackupSafe                             = $true
  ViewAuditLog                           = $true
  ViewSafeMembers                        = $true
  requestsAuthorizationLevel1            = $true
  AccessWithoutConfirmation              = $true
  CreateFolders                          = $true
  DeleteFolders                          = $true
  MoveAccountsAndFolders                 = $true
  } 

$SafeOwner2 |L -SafeName $safe.name -MemberName $safe.SafeOwner2 -UseGen1API 

**Expected behavior**
in Work Flow authorization, I need Level 1 to be added as a permission

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/44178884/185989337-b2e52546-d854-4f82-b137-efda535db6ca.png)

**Your Environment**
Include relevant details about your environment

PowerShell Version: 5
psPAS Version: 5.3.69
CyberArk Version: 11.5

**Comment by pspete** [comment]
`requestsAuthorizationLevel1` & `requestsAuthorizationLevel2` belong to the gen2 parameterset: https://pspas.pspete.dev/commands/Add-PASSafeMember#gen2-default

For gen1 use the `RequestsAuthorizationLevel` parameter per the documentation: https://pspas.pspete.dev/commands/Add-PASSafeMember#-requestsauthorizationlevel
