### ISSUE TITLE
Set-PASUser is not setting the password

### ISSUE THREAD

**Issue by DougGalan** [pspete/psPAS#419]
**Describe the issue**
When trying to use the Set-PASUser command to set a new password for an AppProvider user it doesn't work

**To Reproduce**
1.        $password = ConvertTo-SecureString -String "@PHmw*ArPEc" -AsPlainText -Force
2.         Set-PASUser -id 95 -username Prov_Test -NewPassword $password -userType AppProvider -Location \Application

The above lines are the ones that I'm running obviously after authenticating and then when I go to the server and reset the cred file by running the CreateCredFile.exe utility, the agent fails due to an authentication error. 

**Expected behavior**
I would expect the user to get in sync like when resetting the password manually through PrivateArk Client.

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.7763.2268
* psPAS Version: 5.2.59
* CyberArk Version: 12.6

**Additional context**

**Comment by pspete** [comment]
Hi @DougGalan 

Is this something that also occurs outside the module? 
You can confirm with the following example code:
```powershell
$ws = Get-PASSession
$url = "$($ws.BaseURI)/api/Users/95"
$body = [PSCustomObject]@{
    "NewPassword"="@PHmw*ArPEc"
    "username"="Prov_Test"
    "Location"="\Application"
    "userType"="AppProvider"
} | ConvertTo-Json

Invoke-RestMethod -Method PUT -Body $body -Uri $url -WebSession $($ws.WebSession) -ContentType "application/json"
```

Is the location specified correct? (i.e. you have the provider user in the **\Application** location and not the default **\Applications** location?).
Believe the when setting a new password like this, the user will also be set to "Must change password at next logon"; the `ChangePassOnNextLogon` parameter can be specified to control this:

```powershell
Set-PASUser -id 95 -username Prov_Test -NewPassword $password -userType AppProvider -Location \Applications -ChangePassOnNextLogon $false
```


The simplest option may just be to opt to use the `Set-PASUserPassword` command:

```powershell
Set-PASUserPassword -id 95 -NewPassword $password
```

Let us know how you get on.

**Comment by DougGalan** [comment]
Hi,

Thank you so much for your prompt reply.  The *Set-PASUserPassword -id 95
-NewPassword $password* worked.

I really appreciate your help.

Thank you,
Douglas Galan
