### ISSUE TITLE
DiscoveredAccounts Onboard API

### ISSUE THREAD

**Issue by Jayk423** [pspete/psPAS#420]
There is an API available in v12.6 that allows users to onboard discovered accounts. It's not documented but it can be found in the swagger UI.

Please add a function to interact with this API that will onboard accounts based on a keyword search and filter of discovered account properties.

**Additional context**

Method:
POST 

URI
/api/DiscoveredAccounts/{discoveredAccountId}/Onboard

Response Class (Status 200)
OK

Content Type 
application/json

Parameters
discoveredAccountId (required)

body	
{
  "platformId": "string",
  "safeName": "string",
  "shouldReconcileAccount": true,
  "defaultPassword": "string"
}

![Screenshot 2022-08-25 141717](https://user-images.githubusercontent.com/37341416/186739570-f3204bb9-0dfb-4445-8ee8-8db972f1cb2e.png)

**Comment by pspete** [comment]
@Jayk423  - added this is the 5.4 release available via the usual channels now.
Enjoy :)
