### ISSUE TITLE
How to tag logon account in powershell using Add-PASAccount command?

### ISSUE THREAD

**Issue by Kulan117** [pspete/psPAS#428]
**Describe the issue**
When I am using the below command I am getting the error below

**To Reproduce**
1. Add-PASAccount -address test -userName test -platformID test1234 -SafeName testsafe -password $Password -ExtraPass1Name "Network Device-test1234-test-admin" -ExtraPass1Safe testsafe

**Expected behavior**
The new account to be added along with the login account being tagged to the account.

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell

Add-PASAccount -address test -userName test -platformID test1234 -SafeName testsafe -password $Password -ExtraPass1Name "Network Device-test1234-test-admin" -ExtraPass1Safe testsafe

Invoke-PASRestMethod : Request Error BODY color 000000 background color white font family Verdana margin left 0px margin top 0px content margin left 30px font size 70em padding bottom 2em 
A link color 336699 font weight bold text decoration underline A visited color 6699cc font weight bold text decoration underline A active color 336699 font weight bold text decoration 
underline heading1 background color 003366 border bottom 336699 6px solid color ffffff font family Tahoma font size 26px font weight normal margin 0em 0em 10px 20px padding bottom 8px 
padding left 30px padding top 16px pre font size small background color e5e5cc padding 5px font family Courier New margin top 0px border 1px f0f0e0 solid white space pre wrap white space 
pre wrap word wrap break word table border collapse collapse border spacing 0px font family Verdana table th border right 2px white solid border bottom 2px white solid font weight bold 
background color cecf9c table td border right 2px white solid border bottom 2px white solid background color e5e5cc Request Error The server encountered an error processing the request See 
server logs for more details 
At line:323 char:13
+ ...  $result = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo     : NotSpecified: (
  R...ls.
:ErrorRecord) [Invoke-PASRestMethod], Exception

  + FullyQualifiedErrorId : 400,Invoke-PASRestMethod
```

**Your Environment**
Privileged Cloud v12.6

* PowerShell Version:
* psPAS Version: Version '5.2.59'
* CyberArk Version: Privileged Cloud v12.6

**Additional context**

**Comment by pspete** [comment]
Can you complete the form? 
Reasons: https://pspas.pspete.dev/docs/troubleshooting/#logging-an-issue

**Comment by pspete** [comment]
With no more details forthcoming..... maybe specify the `-ExtraPass1Folder` parameter

**Comment by Kulan117** [comment]
I have updated this tracker to the specified format, please let me know for any details.
I tried with -ExtraPass1Folder as root directory but still same

**Comment by pspete** [comment]
The project cannot test against Privilege Cloud, so no attempt to replicate the issue will be possible.
There may be fixes included in psPAS versions released since 5.2.59.
For 12.6, consider using the [Gen2 parameterset](https://pspas.pspete.dev/commands/Add-PASAccount#gen2) of `Add-PASAccount`, and link accounts using the [`Set-PASLinkedAccount`](https://pspas.pspete.dev/commands/Set-PASLinkedAccount) command

**Comment by Kulan117** [comment]
sure let me try that and post the update!
Thank you!

**Comment by Kulan117** [comment]
Hi @pspete 

I was successful using the Set-PasLinkedAccount command when adding the account ID and name manually.
 But if I am passing the Account ID and name as variable from the Add-PASAccount command as below I am getting the below error. Can you please help on this

#Add Account
$value1 = Add-PASAccount -secretType Password -secret $Password -SafeName "keyssafe" -PlatformID "keysplatform" `
-Username $uname -platformAccountProperties $platformAccountProperties
$value2 = Add-PASAccount -secretType Password -secret $Password -SafeName "rootsafe" -PlatformID "rootplatform" `
-Address "https://console.aws.amazon.com/console/home" -Username $uname -platformAccountProperties $platformAccountProperties 
$accid= $value1 | Select-Object id
$username = $value2 | Select-Object name
Set-PASLinkedAccount -AccountID $accid -safe "keyssafe" -extraPasswordIndex 1 -name $username -folder root



Error 1: When passing both -Account ID and -name as variable

Invoke-PASRestMethod : [400] Account id value is invalid.
At line:57 char:4
+             Invoke-PASRestMethod -Uri $URI -Method POST -Body $body - ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"C...e is invalid."}:ErrorRecord) [Invoke-PASRestMethod], Excepti 
   on
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod


Error 2: When passing -Account ID as actual ID and -name as variable

Invoke-PASRestMethod : [404] Linked account was not found.
At line:57 char:4
+             Invoke-PASRestMethod -Uri $URI -Method POST -Body $body - ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"P...as not found."}:ErrorRecord) [Invoke-PASRestMethod], Excepti 
   on
    + FullyQualifiedErrorId : PASWS307E,Invoke-PASRestMethod
 
It works when passing the below
**Set-PASLinkedAccount -AccountID 222222 -safe "keyssafe" -extraPasswordIndex 1 -name gotest6 -folder root

**

**Comment by pspete** [comment]
Take a look at the variable values... they look like they might be objects with property values rather than just the id/Name values

**Comment by pspete** [comment]
closing as nothing to fix.
believe you just need to fix your variables, or reference them differently (i.e. `Set-PASLinkedAccount -AccountID $accid.id -safe "keyssafe" -extraPasswordIndex 1 -name $username.name -folder root`)

**Comment by Kulan117** [comment]
Thank you for your help!
I fixed the variables and now it works as expected!
