### ISSUE TITLE
Get-PASAccount result issue

### ISSUE THREAD

**Issue by nawazsarwar124** [pspete/psPAS#429]
Good Morning,

i am using pspas and using get-pasaccount, it shows me result butwhen it sees duplicate is shows first result but not second. I tried it in all way but not able to both the result. I am using 12.2 version. 
Can you please let me know how I can proceed.

Thanks,
NS

**Comment by pspete** [comment]
Save us some time by providing the details requested in the new issue template please....
https://pspas.pspete.dev/docs/troubleshooting/#logging-an-issue

**Comment by pspete** [comment]
perhaps you are using the gen1 api?
https://pspas.pspete.dev/docs/search/#gen1-api

**Comment by pspete** [comment]
Closing, as no updates.
All answers for command can be found in the documentation: https://pspas.pspete.dev/commands/Get-PASAccount
