### ISSUE TITLE
Generate complex password using powershell

### ISSUE THREAD

**Issue by Kulan117** [pspete/psPAS#430]
Issue:
Using the GUI we have the option to change and generate a complex password using the generate tool and set the password only in the Vault.

Do we have the option in psPAS to generate a random complex password without inputting the password value but chosing the password parameters like uppercase, lowercase, etc?

Privileged Cloud v12.6

PowerShell Version:
psPAS Version: Version '5.2.59'
CyberArk Version: Privileged Cloud v12.6

**Comment by pspete** [comment]
https://pspas.pspete.dev/commands/New-PASAccountPassword

**Comment by Kulan117** [comment]
Great Thank you!
Now my script working fine 👍
