### ISSUE TITLE
Publish to PSGallery

### ISSUE THREAD

**Issue by mattmcnabb** [pspete/psPAS#44]
This utility looks incredibly useful - have you considered publishing it to the PowerShell Gallery for ease of installation?

**Comment by pspete** [comment]
Thanks @mattmcnabb - it is definitely something I would like to work towards - maybe when the module gets to version 1.0.0 - there are also a few best practices which are not yet in place which I think the module may benefit from (i.e. Pester tests...)

**Comment by f-bader** [comment]
Hi @pspete 
I understand that you don't want to publish to early. But your code is stable enough and the PSGallery supports even version numbers below 1.0.
It would not only make it easier to install, but much easier to find.

Great work on this. Thank you for saving me a lot of work.

**Comment by pspete** [comment]
Thanks @fbader - I am currently working on it... 
I am hoping to be in a position to publish in the next few weeks.
A general Pester test script for the module is in development, which has already shown me a few minor things I have missed in a few functions - once this is ready, and all initial tests pass I will publish.

**Comment by pspete** [comment]
@f-bader  [Here It Is](https://www.powershellgallery.com/packages/psPAS/1.0.16)

A slight typo in the deploy script I need to take care of - and an update to the readme is needed to clarify the new install instructions - but it is now in the gallery.

@mattmcnabb - thanks for logging this, it certainly bumped this task up my priority list.

**Comment by mattmcnabb** [comment]
Great work! Can't wait to try it out!
