### ISSUE TITLE
multiple users recieving error attempting to  run new-passession

### ISSUE THREAD

**Issue by tallyn** [pspete/psPAS#440]
**Describe the issue**
Invoke-PASRestMethod : The term 'Get-PASResponse' is not recognized as the name of a cmdlet, function, script file, or operable program.

**To Reproduce**
running the following:
$loginurl = azuresso url here
	$token = New-SAMLInteractive -LoginIDP $loginurl
	New-PASSession -BaseURI https://XXXXXX.privilegecloud.cyberark.com -samlauth -SAMLResponse $token

**Expected behavior**
a passession should build

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell

<--Console Output Goes Here-->

Invoke-PASRestMethod : The term 'Get-PASResponse' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At line:451 char:19
+                 $PASSession = Invoke-PASRestMethod @LogonRequest
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PASResponse:String) [Invoke-PASRestMethod], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Invoke-PASRestMethod

**Your Environment**
Include relevant details about your environment

* PowerShell Version:
* psPAS Version: 5.4.101
* CyberArk Version: cloud

**Additional context**
i haven't upgraded my pspas module in awhile, running 5.2.59 is still working.  but multiple folks in my company have started getting this exact error after fresh pspas installs

**Comment by tallyn** [comment]
spot-checking it seems all of the required functions are not being installed in the /private directory when installing from powershell gallery.

**Comment by pspete** [comment]
Closing - no response
