### ISSUE TITLE
AZURE SAML Authentication

### ISSUE THREAD

**Issue by msstefano** [pspete/psPAS#442]
Hi, on my cyberark implementation i use Azure as IDP, I try to use PSPAS with module PS-SAML-Interactive to autheticate against Azure, but Azure says "AADSTS750054: SAMLRequest or SAMLResponse must be present as query string parameters in HTTP request for SAML Redirect binding."

Seems like that in the request miss the SAMLRequest parameter.
I think this parameter should be generated by cybark

Is there an API (or another way) to ask cyberark to create these parameter to attach to che request ?

Thanks

**Comment by pspete** [comment]
Hi @msstefano - it is hard to say with the level of detail provided.
Consider providing more detail, perhaps completing the issue template.

**Comment by pspete** [comment]
Closing, no update.
