### ISSUE TITLE
Add-PASSafeMember: A parameter cannot be found that matches parameter name 'MemberType'

### ISSUE THREAD

**Issue by nidhinckgithub** [pspete/psPAS#443]
**Describe the issue**
While executing Add-PASSafeMember cmdlet, getting missing MemberType attribute.

**To Reproduce**
Execute below cmdlet
Add-PASSafeMember -SafeName TestSafe2 -MemberName member -SearchIn Vault -UseAccounts $true -RetrieveAccounts $true -ListAccounts $true

**Expected behavior**

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/36838408/210582137-f0ce66f6-d87d-434d-b39f-93ac05349f96.png)
 

```powershell

<--Invoke-PASRestMethod : [400] There are some invalid parameters: Property [MemberType] not found, Missing mandatory parameter [MemberType].
At line:276 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"Details":[{"E...id parameters"}:ErrorRecord) [Invoke-PASRestMethod], Exception
    + FullyQualifiedErrorId : PASWS167E,PASWS179E,PASWS011E,Invoke-PASRestMethod
 
-->

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.19041.2364
* psPAS Version: 5.4.101
* CyberArk Version: 12.2

**Additional context**

**Comment by pspete** [comment]
Hi @nidhinckgithub 

That doesn't sound right for 12.2.... and issue cannot be reproduced here in 12.6
![image](https://user-images.githubusercontent.com/10600090/210653211-926aa017-16fc-4672-a16b-96e4847b859a.png)

The vendor documentation here shows that `MemberType` is not a parameter for the API function at version 12.2: 
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/12.2/en/Content/WebServices/Add%20Safe%20Member.htm?tocpath=Developer%7CREST%20APIs%7CSafes%7CSafe%20members%7C_____1#Bodyparameters

**Comment by walidhammad** [comment]
@nidhinckgithub I saw you comment on the ISPSS issue which for that MemberType is required. @hjbotha-cybr
 has a fork where he added this in here https://github.com/hjbotha-cybr/psPAS/commit/aea05638f36a0efcf926396154c7ac5b33df40f9

**Comment by nidhinckgithub** [comment]
@walidhammad Thanks a lot. After making the change you have suggested now I'm able to pass the MemberType and make it work.
Thanks @hjbotha-cybr
@pspete  - Sorry for the confusion. I think i need to mention the cyberark version as cloud

**Comment by whip113** [comment]
Yes, the REST API for safe members has different required parameters for the Shared Services Platform Privilege Cloud than the one for self-hosted. I had a docs issue raised to clarify this, but it wouldn't have been applied to the 12.2 docs. Check the later version docs for this as they should have the updated requirements.

**Comment by pspete** [comment]
Will add an optional `MemberType` parameter to `Add-PASSafeMember` in the next module release.

**Comment by pspete** [comment]
Added [memberType](https://pspas.pspete.dev/commands/Add-PASSafeMember#-membertype) parameter
