### ISSUE TITLE
SSH Public Key cmdlets - Username validation issue when using UPN 

### ISSUE THREAD

**Issue by MarcGroot** [pspete/psPAS#445]
**Describe the issue**
In some cmdlets the absence of the dot is validated, which causes problems in environments where e.g. UPN is used and cmdlets have to be edited locally.

**To Reproduce**
1. In Get-PASPublicSSHKey, Add-PASPublicSSHKey or Remove-PASPublicSSHKey use username with "."

**Expected behavior**
Regular expression will allow to use a username of the form username@domain.com

**Screenshots & Console Output**
![image](https://user-images.githubusercontent.com/99815910/213375792-12014e92-51fa-4f30-ac32-bf051c2427cf.png)

![image](https://user-images.githubusercontent.com/99815910/213374349-7597c00a-c912-40ff-933a-1bdcdf6cb0ae.png)

```powershell



```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.19041.2364
* psPAS Version: 5.4.101
* CyberArk Version: 13.0

**Comment by pspete** [comment]
HI @MarcGroot 

Thanks for highlighting this - will investigate for the next module release.
