### ISSUE TITLE
New-PASSession:   Invoke-WebRequest : Specified value has invalid CRLF characters.

### ISSUE THREAD

**Issue by mkanet** [pspete/psPAS#448]
**Describe the issue**
I am unable to successfully authenticate using `OSUser` authentication when using `New-PASSession -UseDefaultCredentials`.  The result is an invalid/unusable session due to the API endpoint returning invalid characters for the respective session.

**To Reproduce**

1. `New-PASSession -UseDefaultCredentials -BaseURI https://cyberpass.ourorganization.com -PVWAAppName MyApp`
2.  Immediately afterwards, if I type `Get-PASLoggedOnUser` and press enter, I get the respective exception below:

```
Invoke-WebRequest : Specified value has invalid CRLF characters.
Parameter name: value
At line:216 char:19
+ ... $APIResponse = Invoke-WebRequest @PSBoundParameters -ErrorAction Stop
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

If I type `Get-PASSession`, I get the below result:
```
User BaseURI                                ExternalVersion WebSession
---- -------                                --------------- ----------
     https://cyberpass.ourorganization.com/MyApp 0.0             Microsoft.PowerShell.Commands.WebRequestSession
```

**NOTE:**
On the CyberArk web interface, my CyberArk app `MyApp` is configured for `OSUser` authentication _(Windows ActiveDirectory user)_.   The only thing I did was type my Windows ActiveDirectory username `myusername` in the field where I need to specify the user account.  Do I need to also specify my AD domain like `ADDomain\mysername`?  Do I need to surround the username with quotes?  I'm not sure what format to use for the user account since the interface doesn't even check/validate if the username I typed in.

I'm not sure why the server would return invalid CRLF characters.  I'm not sure what I should try next to resolve this issue.  I've spent days on this; and, not making any progress.   I'd really appreciate any help you can offer to get this to work.

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version:  5.4.94
* CyberArk Version: 10
* Windows 10 Desktop

**Comment by pspete** [comment]
Have you tried windows authentication without the use of the `-UseDefaultCredentials` switch, providing your windows credentials instead?
i.e.
```powershell
$cred = Get-Credential
New-PASSession -Credential $cred -BaseURI https://cyberpass.ourorganization.com -PVWAAppName MyApp -type Windows
```
specify the username for the credential object in the same format you would use to login to PVWA

**Comment by mkanet** [comment]
Thank you for responding!

We're currently looking for a fully automatic way to retreive passwords via psPASS since we already authenticate into AD every day when we login to our Windows desktops (using our smartcards + respective PIN).

Currently we have to use our web browser to visit our Cyberark webpage, then authenticate using our Smartcard + Smartcard PIN... which is very tedious to do every day.

Having said that, I did try to do what you asked $cred = Get-Credential; New-PASSession -Credential $cred....
However, it kept telling me that the username was wrong.  I tried both  DOMAIN\adusername as well as just adusername along with respective password. 

Im not sure if I'm doing something wrong or our Cyberark Admins just don't know how to configure authentication correctly on the backend for `-UseDefaultCredentials`.

**Comment by pspete** [comment]
> Currently we have to use our web browser to visit our Cyberark webpage, then authenticate using our Smartcard + Smartcard PIN... 

This appears different to the method you are attempting via the module?
There is an example for [pki auth](https://pspas.pspete.dev/commands/New-PASSession#example-12) in the docs.
Consider confirming with your CyberArk Admins which authentication method to use.

**Comment by mkanet** [comment]
Thanks.  I will talk to them.  They didn't have much experience with setting up authentication for us.

My understanding is that `-UseDefaultCredentials` doesn't require us to use a certificate (such as the one associated with our smartcards); instead, re-using only the existing authentcated Windows Desktop session.

Maybe I've been wrong all this time on how `-UseDefaultCredentials` should be used.  Anyway, thank you for your time.  I don't think theres more I can do until our Cyberark Admins figure out which authentication solution is fully automated... not requiring to manually type a Smartcard pin code.

**Comment by chrisdma** [comment]
@mkanet Did you ever work this out? Our agency switched to CyberArk for LAPS authentication and I need some way programatically to get the CyberArk generated password when we are required to sign in using a smartcard and PIN into CyberArk. 

Trying to figure out an authentication method here where I can pass in a smartcard credential and PIN or use Windows based authentication (as we sign in with a smartcard cert + PIN) and pass that auth into psPAS.

**Comment by mkanet** [comment]
@chrisdma yes, I finally have a working solution.  I was having trouble with PsPAS because it doesn't appear that PsPAS even has **Smartcard authentication + PIN** authentication.  Our CyberARK person provided me with a set of custom CyberARK PowerShell functions (unrelated to PsPAS module) that will authenticate via Smartcard +PIN, then retrieve the new password for an account.

Also, if you recently logged into your Windows PC with your Smartcard + PIN, you won't be prompted again for the smartcard PIN when the script retrieves the password...making it **fully automatic**.    

Send me an email:  mkanet at yahoo dot com

**Comment by mkanet** [comment]
@pspete What are the chances you could provide Smartcard+PIN authentication to `New-PASSession`?  If `New-PASSession` already has full support for Smartcard + PIN authentication, could you please give us an example code on how to do this?

**Comment by pspete** [comment]
@mkanet - are you able to share your working code for Smartcard + PIN authentication? chances of being able to include the functionality in the module would  increase significantly with a working example to refer to.

**Comment by mkanet** [comment]
> @mkanet - are you able to share your working code for Smartcard + PIN authentication? chances of being able to include the functionality in the module would increase significantly with a working example to refer to.

@pspete I would LOVE to share this piece of code to incorporate into psPAS.  However, unfortunately this code was not developed by me.  It was written by a Cyberark contractor at our organization.  I will talk to him on Monday and check with his boss to see if it's OK to share this code.  I've been testing it for a few weeks now... it seems to work very well.  I will let you know either way on Monday.

**Comment by pspete** [comment]
> He mentioned that he already spoke to you at a recent CyberArk conference about this.

In that case... Can you test the initial commit of the PKIPN authentication capability currently present in the [pkipn](https://github.com/pspete/psPAS/tree/pkipn) branch?

If it works for you, we can promote into dev and get it into the next psPAS release :)

**Comment by pspete** [comment]
Another user confirmed that it [appears to work](https://github.com/pspete/psPAS/issues/463#issuecomment-1591025136) - so hopefully appears the same way for you also?

**Comment by mkanet** [comment]
@pspete sorry I haven't had any time to do this in the last few days.  I will try to do this by tomorrow.

**Comment by mkanet** [comment]
@pspete I sorry I have been very busy the last few days.  I will try this ASAP.  I just downloaded the initial commit of the PKIPN branch.

Could you please give me an example command-line to use to test the new **pkipn** authentication capability?  I will be able to test this tomorrow at work.

**Comment by pspete** [comment]
PKIPN auth now added into the latest release: https://pspas.pspete.dev/docs/authentication/#pkipn-authentication-example

Troubleshooting or advising on the "Method Not Allowed" and "Unauthorised" status codes you see is tricky as we don't have PKIPN setup in any environment to replicate.

You can potentially test the process outside of the module to see if it occurs when not using psPAS: https://pspas.pspete.dev/docs/troubleshooting/#manual-api-command-testing 

This will confirm if it is due to code in the module or not.

If you do find additional information which points to a resolution let us know via a new issue.
