### ISSUE TITLE
Get-PASOnboardingRule not returning rule details

### ISSUE THREAD

**Issue by seswho** [pspete/psPAS#449]
**Describe the issue**
Get-PASOnboardingRule does not return details of any Onboarding Rules. It only returns the RuleID, RuleName, TargetPlatformId, and TargetSafeName.

According to CyberArk documentation, all information related to an Onboarding Rule should be displayed: https://docs.cyberark.com/Product-Doc/OnlineHelp/PrivCloud-SS/Latest/en/Content/WebServices/GetAutoOnboardingRules.htm

This occurs regardless of calling this function with or without parameters.

**To Reproduce**
1. $OnboardingRules = Get-PASOnboardingRule
2. $RuleDetails = Get-PASOnboardingRule -Names Rule1
3.

**Expected behavior**
All details related to Onboarding Rules regardless of how the function is called based on the results shown in the CyberArk documentation: https://docs.cyberark.com/Product-Doc/OnlineHelp/PrivCloud-SS/Latest/en/Content/WebServices/GetAutoOnboardingRules.htm#Result

**Screenshots & Console Output**
See the attached file 0505f1a6c048.png for results of the call to Get-PASOnboardingRule

```powershell

$Credentials = Get-Credential ([Environment]::UserName)
New-Passession -credential $Credentials -type RADIUS -baseuri https://custinfo.privilegecloud.cyberark.com
$LocalSession=Get-PASSession

# Checkout ajg_admin
$AdminCred = New-Object System.Management.Automation.PSCredential -ArgumentList ("admin", (Get-PASAccount -id 35_3 | Get-PASAccountPassword -Reason "Listing Onboarding Rules" ).ToSecureString())

# Create new session
New-PASSession -BaseURI https://ajg.privilegecloud.cyberark.com -Credential $AdminCred
$AdminSession = Get-PASSession

# Get list of Onboarding Rules


$OnboardingRules = Get-PASOnboardingRule 

        
ForEach($OnboardingRule in $OnboardingRules)
{
    Write-Output $OnboardingRule
}

# Close and unlock ajg_admin
Use-PASSession -Session $LocalSession

#Unlock-PASAccount -AccountID 35_3

$LocalSession = ""
$AdminSession = ""


Close-PASSession
```

**Your Environment**
Include relevant details about your environment

* PowerShell Version:
PSVersion                      5.1.19041.2364                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.19041.2364                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

* psPAS Version:
5.4.101

* CyberArk Version:
CyberArk Privilege Cloud
Version 12.7.0 (12.7.0.20)

**Additional context**
![Annotation 2023-01-27 120404](https://user-images.githubusercontent.com/7858871/215161332-63914cd7-078e-41d7-b44f-0505f1a6c048.png)

**Comment by pspete** [comment]
Hi @seswho,

Thanks for raising this - I don't think the output of this function ever got updated inline with the updates to the documentation/functionality.

While we look into making the output available in the next module release, you can potentially already see/access the information like this:

```powershell
$OnboardingRules | Select-Object *
```
