### ISSUE TITLE
Support -NumberOfRetentionDays 0

### ISSUE THREAD

**Issue by infamousjoeg** [pspete/psPAS#450]
**Is your feature request related to a problem? Please describe.**
Currently, the minimum value in the acceptable range of integers for the parameter `-NumberOfRetentionDays` is `1`.  A value of `0` is now supported which can be used for testing to immediately remove a test safe.

**Describe the solution you'd like**
Support for a range of intervals starting with `0`.

**Comment by pspete** [comment]
Hey @infamousjoeg ,

Thanks for this information - will make this available in the next module release.
