### ISSUE TITLE
Request to add PTA to Get-PASComponentDetail

### ISSUE THREAD

**Issue by rehmulus** [pspete/psPAS#453]
**Describe the issue**
I want to get the component details for PTA.

**To Reproduce**
```powershell
Get-PASComponentDetail -ComponentID 'PTA'
```

**Expected behavior**
PowerShell object of the PTA component(s) like the other components are returned.

**Console Output**
```
Cannot validate argument on parameter 'ComponentID'. The argument "PTA" does not belong to the set
 "PVWA,SessionManagement,CPM,AIM" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
```

**Your Environment**

* PowerShell Version: 7.1.3
* psPAS Version: 5.4.101
* CyberArk Version: 12.6

**Additional context**
The ComponentID parameter in CyberArk Rest API accepts 'PTA' since version 12.0: cf. System Details [12.0](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/12.0/en/Content/WebServices/SystemDetails.htm) and [11.7](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.7/en/Content/WebServices/SystemDetails.htm). 
The parameter in [Get-PASComponentDetail.ps1](https://github.com/pspete/psPAS/blob/8e425cc557f619f06731396930f8abf37c610a64/psPAS/Functions/SystemHealth/Get-PASComponentDetail.ps1#L10) does not accept 'PTA' probably because the script checks against version [10.1](https://github.com/pspete/psPAS/blob/8e425cc557f619f06731396930f8abf37c610a64/psPAS/Functions/SystemHealth/Get-PASComponentDetail.ps1#L16).

**Comment by pspete** [comment]
Hi @rehmulus ,

Thanks for raising this - had missed the inclusion of the parameter in the docs and should be able to make this available in the next module release.
