### ISSUE TITLE
Get-PASAccount Now requires 11.2 to use Gen2API.  Docs say 10.4+ is required

### ISSUE THREAD

**Issue by jbalcorn** [pspete/psPAS#455]
**Describe the issue**
Using Get-PASAccount with -search parameter against v11.1 vault results in "Gen2API requires 11.2". Docs at PSPas.pspete.dev and Cyberark both say Gen2 search should work with 11.1

**To Reproduce**
1. Run `Get-PASAccount -search xx` against 11.1 vault
2. Profit!
3.

**Expected behavior**
Should return result as search parameters is supported on 11.1

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell
PS > $VAAccounts = Get-PASAccount -Search "VA" -SearchType startswith

CyberArk 11.1.0 does not meet the minimum version requirement of 11.2 for Get-PASAccount (using ParameterSet: Gen2Query)
At line:73 char:6
+ ...             Throw "CyberArk $ExternalVersion does not meet the minimu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (CyberArk 11.1.0...Set: Gen2Query):String) [], RuntimeException
    + FullyQualifiedErrorId : CyberArk 11.1.0 does not meet the minimum version requirement of 11.2 for Get-PASAccount (using ParameterSet: Gen2Query)
 ```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1.19041.2364
* psPAS Version: 5.4.101
* CyberArk Version: v11.1

**Additional context**
![image](https://user-images.githubusercontent.com/7225956/222218739-d5e3bbdb-b492-4f7b-8688-d529f99b0a17.png)

**Comment by pspete** [comment]
Unfortunately, that's a mistake in the docs.
The `searchType` parameter is relevant for 11.2+, detailed here in the [CHANGELOG](https://github.com/pspete/psPAS/blob/master/CHANGELOG.md#34100-january-27th-2020) & [ReleaseNotes](https://pspas.pspete.dev/articles/pspas-release-3-4/).

Will correct the `Get-PASAccount` command documentation for the next release.

**Comment by jbalcorn** [comment]
Ah. I see. Even though the API has 'search', it's actually a list of keywords.

Well, we're doing our 12 upgrade in May :-)

**Comment by pspete** [comment]
you can use the `search` parameter in any version higher than 10.4

`searchtype` requires minimum version of 11.2
`modificationTime` requires minimum version of 11.4
`savedFilter` requires minimum version of 12.6
