### ISSUE TITLE
SAML Authentication -  [400] Authentication failure,  using new getSAMLResponce Executable

### ISSUE THREAD

**Issue by TimmyMahood** [pspete/psPAS#462]
Describe the issue
I work with SAML authentication, but get error : [400] Authentication failure

To Reproduce
Steps to reproduce the behaviour:

$loginURL = "https://pvwa-company/PasswordVault/"
$loginResponse = New-SAMLInteractive -LoginIDP $loginURL
$baseURL = "https://pvwa-company/"
New-PASSession -SAMLAuth -concurrentSession $true -BaseURI $baseURL -SAMLResponse $loginResponse
Expected behavior
I should get PASSession successfully. I can get SAML response using the new getSAMLResponse Executable.  The Variable has the token in it and Azure Logs show a sucess
, but can not pass authentication.

Screenshots & Console Output

<--Console Output Goes Here-->
Invoke-PASRestMethod : [400] Authentication failure. Please contact your Administrator.
At line:445 char:19
+                 $PASSession = Invoke-PASRestMethod @LogonRequest
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"P...dministrator."}:ErrorRecord) [Invoke-PASRestMethod], Ex
   ception
    + FullyQualifiedErrorId : PASWS035E,Invoke-PASRestMethod
Your Environment
Include relevant details about your environment

Tried with both 
PowerShell Version: 5.1.22621.963 (ISE) & Powershell 7.3.1
psPAS Version: psPAS-v5.2.59
CyberArk Version: V12.2
Additional context

Expanding the full error from PowerShell I get
PSMessageDetails      :
Exception             : System.Exception: [400] Authentication failure. Please contact your Administrator.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : {"ErrorCode":"PASWS035E","ErrorMessage":"Authentication failure. Please contact your Administrator."}
CategoryInfo          : NotSpecified: ({"ErrorCode":"P...dministrator."}:ErrorRecord) [Invoke-PASRestMethod], Exception
FullyQualifiedErrorId : PASWS035E,Invoke-PASRestMethod
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-PASRestMethod, : line 296
                        at New-PASSession, : line 451
                        at , : line 1
PipelineIterationInfo : {}

the PVWA log reports these lines

WARN  [39]   9eaea61a-6a73-4c09-a5e0-8bafab8bdaff Logon Response:: Code: 400. Content: {"ErrorCode":"PASWS035E","ErrorMessage":"Authentication failure. Please contact your Administrator."}  [AuthController]

DEBUG [39]   9eaea61a-6a73-4c09-a5e0-8bafab8bdaff EPVAN040D Disabling HTTP cache  []

INFO  [39]   9eaea61a-6a73-4c09-a5e0-8bafab8bdaff EndRequest /PasswordVault/api/auth/SAML/Logon | code: 400  [up]

**Comment by pspete** [comment]
Hi Timmy,

What is the result outside the module, using something like the below example?

```powershell

$LogonRequest = @{ }
$Uri = "https://pvwa-company/PasswordVault"
$SAMLResponse = New-SAMLInteractive -LoginIDP $Uri



$LogonRequest['Body'] = @{'SAMLResponse' = $SAMLResponse } | ConvertTo-Json
$LogonRequest['ContentType'] = 'application/x-www-form-urlencoded'
$LogonRequest['Uri'] = "$Uri/api/auth/SAML/Logon"
$LogonRequest
Invoke-RestMethod @LogonRequest

```

**Comment by TimmyMahood** [comment]
Hi Pete

when I get can output on the console with a

https://login.microsoftonline.com/9c9a30de-<MOREGUID>9600-4be7625ff6c5/saml2?SAMLRequest=<RemovedMyLoginToken>

Navigating to this URL in a web browser i gate the same error (after doing SAML MFA)
![image](https://user-images.githubusercontent.com/48093439/225633737-1b5cbb83-06d0-4215-8cc5-cfc81e261e60.png)

**Comment by pspete** [comment]
The expected authorization is not being returned - you will need to investigate and understand for your configuration.

Once the authentication process returns a successful logon result/authentication token when not using psPAS, it should function the same way if using the module.

**Comment by mguessan** [comment]
I had the same issue with a privilege cloud tenant not properly configured to idp initiated SAML authentication => user has to access CyberArk portal first, be redirected to SAML idp and getSAMLResponse.exe is then able to intercept SAML response.

However in SP initiated mode the SAMLResponse is not enough to obtain a valid token, we also need a valid CA88888 cookie and pass it to token REST endpoint.

Currently working on a patch of getSAMLResponse to retrieve cookie and pass it to token endpoint (exe returns a json structure):

```
$authresponse = .\getSAMLResponse.exe https://$domain/PasswordVault/v10/logon/saml CA88888 | convertfrom-json

$samlResponse=$authresponse.SAMLResponse
$cookievalue=$authresponse.CA88888 

$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$cookie = New-Object System.Net.Cookie
$cookie.Name = "CA88888"
$cookie.Value = $authresponse.CA88888
$cookie.Domain = $domain
$session.Cookies.Add($cookie); 


$url = "https://$domain/PasswordVault/api/auth/saml/logon" 

$body = @{
    concurrentSession='true'
    apiUse='true'
    SAMLResponse=$samlResponse
} 

$token = Invoke-RestMethod -Uri "https://$domain/PasswordVault/api/auth/saml/logon" -Method Post -body $body -ContentType 'application/x-www-form-urlencoded' -WebSession $session
```

**Comment by pspete** [comment]
Closing as no recent updates, and nothing to indicate any required update to the module.
