### ISSUE TITLE
Add -userActivityLogRetentionDays option for PAS User

### ISSUE THREAD

**Issue by hackedbyhackerman** [pspete/psPAS#473]
**Describe the solution you'd like**
Add User and Update User API has an option to change the "userActivityLogRetentionDays" attribute. I cant seem to find this option in
[New-PASUser](https://github.com/pspete/psPAS/blob/master/psPAS/Functions/User/New-PASUser.ps1) or [Set-PASUser](https://github.com/pspete/psPAS/blob/master/psPAS/Functions/User/Set-PASUser.ps1)

**Additional context**
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/API-AddUser-v10.htm?tocpath=Developer%7CREST%20APIs%7CUser%20management%7CUsers%7C_____5#Bodyparameters

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Users%20Web%20Services%20-%20Update%20User.htm?tocpath=Developer%7CREST%20APIs%7CUser%20management%7CUsers%7C_____6#Bodyparameters

**Comment by pspete** [comment]
Thanks for raising @hackedbyhackerman.
`userActivityLogRetentionDays` is only introduced at 13.2, the module update for 13.2 features and capabilities is being worked on. 
All going well, this should be included in the next module release.
