### ISSUE TITLE
Where to get ID to use in Copy-PASPlatform?

### ISSUE THREAD

**Issue by walidhammad** [pspete/psPAS#481]
**Describe the issue**
The Get-PASPlatform platforms parameter set does not return ID int32 of the platform in the details subobject required by *-PASPlatform commands such as Copy-PASPlatform. It is available on all other parameter sets

**To Reproduce**
1. Use Get-PASPlatform [-Active <Boolean>] [-PlatformType <String>] [-Search <String>] parameter set
2. ID int32 is not in the details subobject
**Expected behavior**
I expect ID to be there 

```powershell
Get-Module pspas

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.6.135               psPAS                               {Add-PASAccount, Add-PASAccountACL, Add-PASAccountGroupMember, Add-PASAllowedReferrer…}

Get-PASPlatform -PlatformID XYZ | Get-Member                                 

   TypeName: psPAS.CyberArk.Vault.Platform

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
Active      NoteProperty bool Active=True
Details     NoteProperty System.Management.Automation.PSCustomObject Details=@{PolicyID=XYZ; PolicyName=XYZ; PolicyType=Regular; ImmediateInterval=5; Interval=1440; MaxConcurrentConnections=3; AllowedSafes=XYZ*; MinValidityPeriod=60; ResetOveridesMinValidity=Yes…
PlatformID  NoteProperty string PlatformID=XYZ

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 7.36
* psPAS Version: 5.6.135
* CyberArk Version: 13.2

**Additional context**

**Comment by pspete** [comment]
From memory, think it's under the Details property

**Comment by pspete** [comment]
Closing as generally covered in the existing documentation: https://pspas.pspete.dev/commands/Get-PASPlatform#:~:text=The%20output%20contained%20under%20the%20%E2%80%9CDetails%E2%80%9D%20property%20differs%20depending%20on%20which%20method%20(9.10%2B%2C11.1%2B%20or%2011.4%2B)%20is%20used%2C%20and%20which%20platform%20type%20is%20queried.

You can comment to reopen if needed
