### ISSUE TITLE
Unable to change EPVUSER authentication

### ISSUE THREAD

**Issue by sabya646** [pspete/psPAS#482]
Hi pspete,

While trying to change the authentication method of EPVUSER (external users) using Set-PASUser command, I am getting below error:

Invoke-PASRestMethod : [500] Update of the requested user property is not allowed for an external user.
At line:467 char:14
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method PUT -Body $Body -W ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"ErrorCode":"I...xternal user."}:ErrorRecord) [Invoke-PASRestMethod], Excepti 
   on
    + FullyQualifiedErrorId : ITATS692E,Invoke-PASRestMethod

How can I update the authentication type then?

**Comment by pspete** [comment]
https://www.google.com/search?q=Update+of+the+requested+user+property+is+not+allowed+for+an+external+user&oq=Update+of+the+requested+user+property+is+not+allowed+for+an+external+user&aqs=edge..69i57j0i5i30.343j0j1&sourceid=chrome&ie=UTF-8

Check the top Google result

**Comment by pspete** [comment]
Closing as this is not something to fix in the module code

**Comment by sabya646** [comment]
Hi pspete, any possible reason why it is throwing that error? I am using the command with below parameters, not passing anything else. 

Set-PASUser -id 123 -username testuser -authenticationMethod AuthTypeRADIUS

I am unable to understand the cause of the error and possible fix via automation. I am going through the google searches. Meanwhile any guidance is highly appreciated.

**Comment by pspete** [comment]
The error is not generated by the module.
It is an error reported from the vault for the action being performed.

**Comment by sabya646** [comment]
Does this mean configuration issue with my vault environment? Or should I supply additional parameters mandatorily to fulfill the user update request? Let me check vault trace logs.

**Comment by pspete** [comment]
See the module troubleshooting guide here: https://pspas.pspete.dev/docs/troubleshooting/
