### ISSUE TITLE
Add-PASSafeMember MemberType validation set does not include Role

### ISSUE THREAD

**Issue by walidhammad** [pspete/psPAS#487]
**Describe the issue**
The validationset for parameter MemberType does not include Role. This is used by Privilege Cloud ISP as you cannot manage groups directly in ISP web interface.

https://docs.cyberark.com/PrivCloud-SS/Latest/en/Content/WebServices/Add%20Safe%20Member.htm

![CleanShot 2023-09-05 at 06 40 34@2x](https://github.com/pspete/psPAS/assets/93853945/a6694fb0-d694-4b7d-82b6-17946b80c85a)

Can't use value Group instead of role if the role hasn't been added to a safe already. It does not appear under Get-PASGroup.

Once it has been added to a safe once the backend syncs the role to a vault group with the same name and then value Group can be used. Until then Role is required.

**Expected behavior**

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell
Add-PASSafeMember -SafeName $safename -MemberName $rolename -memberType 'Role' -SearchIn Vault @permissions
Add-PASSafeMember: Cannot validate argument on parameter 'memberType'. The argument "Role" does not belong to the set "User,Group" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 7.3.6
* psPAS Version: 5.6.135
* CyberArk Version: 13.2.0

**Comment by pspete** [comment]
Thanks for raising 👍🏼
