### ISSUE TITLE
New-PASSession  fails on MacOS with -IdentityUser for ISS

### ISSUE THREAD

**Issue by walidhammad** [pspete/psPAS#490]
**Describe the issue**
After resolving the issue with temp on MacOS with IdentityCommand module [https://github.com/pspete/IdentityCommand/issues/5#issue-1919945562](url), I now get an error for New-PASSession

**Expected behavior**
I expect to be able to finish authenticating to identity services and login to the vault

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

```powershell

$ New-PASSession -Credential $pcloudlogin -IdentityTenantURL https://xyz.id.cyberark.cloud -PrivilegeCloudURL https://abc.privilegecloud.cyberark.cloud -IdentityUser -Verbose
VERBOSE: Performing the operation "Logon" on target "https://xyz.id.cyberark.cloud".

Challenge Mechanisms
Select Mechanism
[M] Mobile Authenticator  [E] Email...   [F] FIDO2 Security Key  [Q] QR Code  [?] Help (default is "M"): m
Sent Mobile Authenticator request to your device. Please follow the instructions to proceed with authentication or enter verification code here.
InvalidOperation:
Line |
 754 |  … et-Variable -Name WebSession -Value $($PSItem.GetWebSession()) -Scope …
     |                                          ~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [IdCmd.ID.Session] does not contain a method named 'GetWebSession'.
InvalidOperation:
Line |
 789 |  …             $Script:WebSession.Headers['Authorization'] = [string]$Cy …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received 95-byte response of content type text/html


```

**Your Environment**
Include relevant details about your environment

PowerShell Version: 7.3.6
psPAS Version: 6.0.4
IdentityCommand Version: 0.1.40
CyberArk Version: 13.2.0

**Comment by pspete** [comment]
Potentially still something specific to `IdentityCommand`: pspete/IdentityCommand#5
(the error in psPAS is due to something awry in the IdentityCommand output)

**Comment by pspete** [comment]
No update via pspete/IdentityCommand#5 . Assumed fixed.
