### ISSUE TITLE
Get-PASUser.ps1 - Feature request, add "lastSuccessfulLoginDate" to ExtendedDetails

### ISSUE THREAD

**Issue by dmetz12** [pspete/psPAS#494]
Would be helpful in order to do automated license cleanups, removing the least active users.

**Comment by pspete** [comment]
I don't follow @dmetz12 - it is not usable where it exists already?
![image](https://github.com/pspete/psPAS/assets/10600090/ae1038e4-6e1f-4c05-92ea-9a72a50122a2)

**Comment by dmetz12** [comment]
*doh* that's my mistake, I did a [ | select *] and didn't see that data. Thanks for the quick response. and thanks for all your efforts.

**Comment by pspete** [comment]
No problem @dmetz12 👍
