### ISSUE TITLE
Invoke-PASRestMethod : The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by GeethaSelvam** [pspete/psPAS#50]
_Your issue may already be reported. Please search existing `issues` before creating one._

## Your Environment

* PowerShell Version:5.0
* psPAS Version:master
* CyberArk Version:9.7.0

While calling the New-PASSession
$token = New-PASSession -Credential $VaultCredentials -BaseURI pvwa_url

facing the following issue:
At C:\Program Files\WindowsPowerShell\Modules\psPAS\Functions\Authentication\New-PASSession.ps1:166 char:18
+ ... ASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-PASRestMethod
 
Invoke-PASRestMethod : The request was aborted: Could not create SSL/TLS secure channel

**Comment by pspete** [comment]
Hi @GeethaSelvam - There is code in the  module which forces the use of TLS 1.2 if the client you are executing the module on supports it (implemented to fix #11).
Can you confirm that your PVWA server supports TLS 1.2 and that there are no certificate errors when accessing PVWA - unfortunately this is not something that can be remedied in the code of the module (without allowing for use of less secure protocols).

**Comment by pspete** [comment]
Hi @GeethaSelvam - any further information on TLS1.2 being supported on your webserver?
Or updates on any certificate errors?

**Comment by pspete** [comment]
It's been 4 weeks with no update - so closing this now.
@GeethaSelvam if you still need help let me know..
