### ISSUE TITLE
Remove-PASGroup is not working as expected

### ISSUE THREAD

**Issue by kchass** [pspete/psPAS#504]
**Describe the issue**
Remove-PASGroup is not working as expected, says some invalid parameters: Cannot add a member to directory group

**To Reproduce**
1.   Authenticated using new-passession -Credential $creds -BaseURI https://<pvwa url>
2.   Remove-pasgroup -GroupID <provided groupID>
3. 

**Expected behavior**
Should be success 200 response, group should be deleted

**Screenshots & Console Output**
![image](https://github.com/pspete/psPAS/assets/111726107/87904b2d-39e5-4c2d-9fd9-0dd7342e8375)

```powershell
On Powershell 7.3.9, psPAS 5.4.101 & 6.0.21

Invoke-PASRestMethod:
Line |
  26 |              Invoke-PASRestMethod -Uri $URI -Method DELETE -WebSession …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [400] There are some invalid parameters: Can not add a member to directory group [2345].

On Powershell 5.1, psPAS 5.2.24
Remove-PASGroup -GroupID 707
Invoke-PASRestMethod : [400] There are some invalid parameters: Can not add a member to directory group [707].
At line:26 char:4
+             Invoke-PASRestMethod -Uri $URI -Method DELETE -WebSession ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({"Details":[{"E...id parameters"}:ErrorRecord) [Invoke-PASRestMethod], Exception
    + FullyQualifiedErrorId : PASWS167E,PASWS214E,Invoke-PASRestMethod
```

**Your Environment**
Tried in both our PROD and TEST environment

* PowerShell Version:  5.1 & 7.3.9 
* psPAS Version: 5.2.54, 5.4.101 & 6.0.21
* CyberArk Version: 12.2

**Additional context**
Help documentation on https://pspas.pspete.dev/commands/Remove-PASGroup might have some typo in example instead of Remove-PASGroup it says Delete-PASGroup -GroupID 3

**Comment by pspete** [comment]
Thanks for spotting the error in the psPAS documentation - will get that corrected.

For the issue reported with `Remove-PASGroup`
Can you test outside the module using the below example code?
```powershell
#after New-PASSession
$ThisSession = Get-PASSession

$Method = "DELETE"
$UrlPath = "1234API/UserGroups/1234/"

$Request = @{
    "Method"      = $Method
    "Uri"         = "$($ThisSession.BaseUri)/$UrlPath"
    "WebSession"  = $ThisSession.WebSession
    "ContentType" = "application/json"
}

Invoke-RestMethod @Request
```

Looking at the API documentation, I think you will see the same issue and error reported
https://docs.cyberark.com/PAS/Latest/en/Content/SDK/Users%20Web%20Services%20-%20Delete%20User%20Group.htm

Only deletion of vault groups is mentioned, not directory groups.

**Comment by kchass** [comment]
You're right, API doesnt allow deleting directory groups, API error message is not very helpful.
poshPACLI works fine to delete such groups, I'll use it for this work. Thanks for quick response. :) 

Invoke-RestMethod: {"Details":[{"ErrorCode":"PASWS214E","ErrorMessage":"Can not add a member to directory group [12012].","ParameterName":"groupId"}],"ErrorCode":"PASWS167E","ErrorMessage":"There are some invalid parameters"}

@infamousjoeg is this feature in pipeline via APIs ?
