### ISSUE TITLE
Set-PASSafe SafeName not being passed

### ISSUE THREAD

**Issue by MichaelCoey** [pspete/psPAS#509]
**Describe the issue**
Upon calling the Set-PASSafe command we are seeing the error: Invoke-PASRestMethod : [400] There are some invalid parameters: Missing mandatory parameter [SafeName].

The issue is that the safe name is not missing and is being placed in the code. All other safe commands are working as expected except this call.

**To Reproduce**
1. Login with valid account with permissions
2. Attempt to update safe description using Set-PASSafe function
3. Call will fail due to SafeName error

**Expected behavior**
If completed successfully we expect to see the safe description updated on the target safe

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.

<--Console Output Goes Here-->

``` Invoke-PASRestMethod : [400] There are some invalid parameters: Missing mandatory parameter [SafeName]. At line 150 char:14

**Your Environment**
Include relevant details about your environment

* psPAS Version: 6.0.30
* CyberArk Version: 13

**Comment by pspete** [comment]
Hi @MichaelCoey 

Without sample code it is hard to comment further. Unfortunately we are unable to replicate the issue using the steps provided.
![image](https://github.com/pspete/psPAS/assets/10600090/f9187e28-25d8-44bc-bb16-f21a2e444bff)

Can you provide additional context, or test the api activity outside of psPAS to confirm if the same issue is observed or not?
See: https://pspas.pspete.dev/docs/troubleshooting/#manual-api-command-testing

**Comment by pspete** [comment]
Any update on this @MichaelCoey - ok if we close the issue?

**Comment by pspete** [comment]
Closing: no update
