### ISSUE TITLE
Get-PASSession Error, Property "Username" cannot be found

### ISSUE THREAD

**Issue by midiaxe** [pspete/psPAS#512]
**Describe the issue**
When running the command 'Get-PASSession' where current session has expired, the following error message comes up.

Select-Object : Property "Username" cannot be found.
At line:12 char:56
+ ... ggedOnUser -ErrorAction Stop | Select-Object -ExpandProperty Username
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Message=There...ExceptionType=}:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand

**To Reproduce**
1. Login to PAS
2. Wait until current session expires
3. Run the 'Get-PASession' command

**Expected behavior**
It seems that 'Username' property is not available on an expired session

* PowerShell Version: 5.1.19041.3693
* psPAS Version: 6.0.30
* CyberArk Version: 12.2.1

**Comment by pspete** [comment]
Thanks for reporting @midiaxe 
Username is obtained by running the `Get-PASLoggedOnUser` command, which requires an authenticated session.

Will look into handling this better for the scenario you highlight 👍

**Comment by pspete** [comment]
Update related to this is in development and will be coming soon
Temporary fix applied in the meantime.
