### ISSUE TITLE
Script is asking for sessionToken but I've used -Credential to logon

### ISSUE THREAD

**Issue by winslowohio** [pspete/psPAS#519]
**Describe the issue**
I have a script that is used to add subject names from certificates to CyberArk appIDs. However after supplying my credentials it comes back asking for sessionToken. I can't figure out why it is asking for this.
**To Reproduce**
Here is the script:

$global:url = 'https://myurl.com' # no app name
#$global:url = 'https://my.other.url.com' # no app name
$global:cred = get-credential
$global:pvwaappname = 'PasswordVault' # no change

import-module psPAS

New-PASSession -BaseURI $global:url -Credential $global:cred -PVWAAppName $global:PVWAAppName

$appid = 'myappID'  #Change to valid AppID
$app = Get-PASApplication -AppID $appid -ExactMatch

Write-Host "App data"
$app | select * | fl

Write-Host "Current authentication methods"
Get-PASApplicationAuthenticationMethod -AppID $appid 

$appSplat = @{
    #Issuer = @(
     #   "" 
    #)
    Subject = @(
        "CN=mycn.com"  #Change
          "E=mycn.email.com" #Change
    )
}

Add-PASApplicationAuthenticationMethod -AppID $appid @appSplat
#Remove-PASApplicationAuthenticationMethod -AppID $appid -AuthID 7
Get-PASApplicationAuthenticationMethod -AppID $appid 

**Expected behavior**
After logging on, it should run through without asking for sessionToken and add the subject name to the appID listed.

**Screenshots & Console Output**
![image](https://github.com/pspete/psPAS/assets/40031490/7f5a9f90-5217-4cfc-96f4-bcf837c2dcbd)

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 4
* psPAS Version: 4
* CyberArk Version: 11.2

**Comment by pspete** [comment]
Not sure @winslowohio psPAS Version 4 is four years old - the code base has moved on significantly since then.
