### ISSUE TITLE
After updating to psPAS v6.03 my script is stopping and asking UseGen1API:

### ISSUE THREAD

**Issue by winslowohio** [pspete/psPAS#520]
I updated to version 6.03 and now one of my scripts is stopping and asking for input: 

Supply values for the following parameters:
UseGen1API:

How can I modify my code to avoid this or else what is the input I need to supply?

This is the code where it is stopping to ask for input:
Write-Host "INFO: Logging on to the $VaultEnv Vault [$baseURI]..."
$token = New-PASSession -Credential (Get-Credential -username $username -Message "Please enter your $VaultENV Vault credentials.`r`n`r`nUsername: <standard username>`r`nPassword: <NT Password+Token>`r`n`r`nNote: Do not include `"+`"") -BaseURI $baseURI -connectionNumber (Get-Random -Maximum 101 -Minimum 1) -ErrorAction Stop -useRadiusAuthentication $true
Write-Output "$(Get-TimeStamp) || INFO || User [$username] is logging in to the $VaultEnv Vault [$baseURI]..." | Out-file $LogFile -Append 

**Expected behavior**
The script logs on to the vault and adds the nodes provided to the requested appID and then creates provider accounts and adds the providers to the safe. 

```

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version: 6.03
* CyberArk Version: 11.2

**Comment by winslowohio** [comment]
![image](https://github.com/pspete/psPAS/assets/40031490/8955f829-a83b-491c-9f13-5b9e8c9bd484)

**Comment by pspete** [comment]
https://pspas.pspete.dev/commands/New-PASSession#gen1radius
`useRadiusAuthentication` is a legacy parameter from the `gen1radius` parameterset.

either specify `UseGen1API $true`, or switch to Gen2 API authentication.
https://pspas.pspete.dev/commands/New-PASSession#gen2radius

Review the documented examples in the help documentation, most authentication scenarios are covered

**Comment by pspete** [comment]
based on the old code base your script was written for, there will have been numerous breaking changes over time.

**Comment by winslowohio** [comment]
We went through and added -UseGen1API as needed. This gets us running for now but will definitely need to rework the scripts to use the current commands and Gen2. Thanks for the assist.
