### ISSUE TITLE
Get-PASPlatform does not return the ID field

### ISSUE THREAD

**Issue by begunrom** [pspete/psPAS#522]
Get-PASPlatform -Search "test" does not return the ID field, it returns only the PlatformID. This PlatformID cannot be used in the Copy-Platform function.

The ID field is needed as a source to the Copy-Platform function.
Copy-PASPlatform -ID 'Test' -name "Test2 "

* psPAS Version: 6.1.50

**Comment by pspete** [comment]
Thanks @begunrom - fix will be included in next release

**Comment by begunrom** [comment]
Hi pspete,

I tried the new version but id is supposed to be a number and is a string.
In the functions related to platform operations you see the ID field and the PlatformID field. ID is numeric and only visible via the API. PlatformID is string and visible via the UI and API. Some of the functions use ID and others PlatformID.

**Comment by pspete** [comment]
You can see `ID` is now returned in the screenshot:
![image](https://github.com/pspete/psPAS/assets/10600090/f7b1d36c-2841-44fb-9f04-f606de0e698e)
