### ISSUE TITLE
Get-PASPSMRecording (-FromTime ) type conversion error 

### ISSUE THREAD

**Issue by ckinasch** [pspete/psPAS#526]
**Describe the issue**
Attempting to run the `Get-PASPSMRecording` command with the `-FromTime` flag set as per the documentation.
Receiving error: `Cannot process argument transformation on parameter 'FromTime'. Cannot convert value to type "System.Int32". Error: "Input string was not in a correct format."`

**To Reproduce**
1. execute the `Get-PASPSMRecording -FromTime (Get-Date).AddDays(-7)` command as per documentation

**Expected behavior**
Expect to receive a list of recording information within the last 7 days

* PowerShell Version: 5.1
* psPAS Version: 6.0.30
* CyberArk Version: 13.2

**Comment by pspete** [comment]
The psPAS version you are using is not recent enough.

See the details for psPAS 6.1.62 here
https://github.com/pspete/psPAS/blob/master/CHANGELOG.md#6162

**Comment by pspete** [comment]
Did updating the module work for you @ckinasch ?

**Comment by pspete** [comment]
The command works as documented in 6.1.62:
![image](https://github.com/pspete/psPAS/assets/10600090/8a657ba0-0251-4bdb-ac5e-52b6a7158bbd)
we may add a formatting helper to output a friendly datetime in a future release

**Comment by ckinasch** [comment]
yes apologies for the delay in response.
all works as expected in latest version, thanks for that
