### ISSUE TITLE
Get-PASAccountDetail -id $Acc.id takes forever

### ISSUE THREAD

**Issue by JCallPut** [pspete/psPAS#538]
Getting account details using following snippet:
$testAccDetails=Get-PASAccountDetail -id $Acc.id

$Acc is actual account object.

Problem is, each run of this code takes between 1 and 6 minutes, even though similar actions via PVWA are in seconds.

Pinpointed this issue to the following psPAS code section:
$APIResponse = Invoke-WebRequest @PSBoundParameters -ErrorAction Stop

Tried to add
$ProgressPreference = 'SilentlyContinue'
right before invoke-webrequest to no avail.

Code works, but unacceptably slow. Unrelated to backend performance.

**Expected behavior**
Performance matching or exceeding PVWA.

**Your Environment**
* PowerShell Version: 7.4.2 using VS Code
* psPAS Version: latest, 6.4.80
* CyberArk Version: 12.6

**Comment by pspete** [comment]
https://pspas.pspete.dev/docs/troubleshooting/#manual-api-command-testing
Follow the troubleshooting guide to confirm if this persists outside the module.

**Comment by JCallPut** [comment]
Running same code against DEV environment returned result in sub-second, so not a code issue.

**Comment by pspete** [comment]
So sounds like an environment issue / not related to the module

**Comment by pspete** [comment]
No recent update, closing as does not appear related to the module code
