### ISSUE TITLE
Unable able to use Add-PASSafeMember

### ISSUE THREAD

**Issue by LostPoE** [pspete/psPAS#540]
**Describe the issue**
A concise summary of the issue
I'm able to query safes, users, and accounts.
The safe has appropriate permissions since its the account that created the safe is trying to add a member. (Also double checked in web gui)
Been messing with the command for a while. Just want to make sure that Add-PASSafeMember still works.

**To Reproduce**
1. Add-PASSafeMember -SafeName "stagingTestSafe" -MemberName "testuser" -SearchIn "xytras.com" -UseAccounts $true -RetrieveAccounts $true -ListAccounts $true 

**Expected behavior**
Add member to safe with permissions in command.

**Screenshots & Console Output**
If applicable, add screenshots and/or console output to help explain your problem.
![image](https://github.com/pspete/psPAS/assets/3904973/f9cb3fec-d0fd-47ee-8aae-782a226bbacb)

```powershell

<--Console Output Goes Here-->
Invoke-PASRestMethod: 
Line |
 292 |  …     $result = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | There are some invalid parameters
```

**Your Environment**
Include relevant details about your environment
CyberArk Cloud services only. No On-prem is being used.

* PowerShell Version: 5.x
* psPAS Version: 6.4.80
* CyberArk Version: 14+

**Comment by pspete** [comment]
Think you are just missing the `membertype` parameter which is required for this operation against Privilege Cloud

**Comment by LostPoE** [comment]
Works. Thanks @pspete !!
