### ISSUE TITLE
Bulk upload of ssh keys using Add-PASAccount function

### ISSUE THREAD

**Issue by selvamcog** [pspete/psPAS#60]
I can bulk upload accounts using passwords but bit confused to create accounts with ssh keys.
Please help me with this,,,

**Comment by pspete** [comment]
Hi @selvamcog.
The process is the same, just specify the ssh key as the password.

**Comment by selvamcog** [comment]
Thank u @pspete it is working fine :)

**Comment by pspete** [comment]
Good to hear - thanks for the update @selvamcog
