### ISSUE TITLE
Function to create cyberark groups using rest-api

### ISSUE THREAD

**Issue by selvamcog** [pspete/psPAS#61]
Tried using New-PASUser for the creation of Cyberark groups also but it did not get created as group instead as a user.Is there any other function to do this?

**Comment by pspete** [comment]
... the "_user_" functions will only work with users - as you now know.
As of CyberArk 10.2, the REST API only supports addition of users to groups, nothing else in terms of group management. 

The only PowerShell alternative I can offer is [`New-PVGroup`](https://github.com/pspete/PoShPACLI/blob/master/Functions/UserMangement/New-PVGroup.ps1) from the [PoShPACLI](https://github.com/pspete/PoShPACLI) module

**Comment by selvamcog** [comment]
Thank u @pspete ..will try that
