### ISSUE TITLE
Cannot get token session

### ISSUE THREAD

**Issue by manelmolina** [pspete/psPAS#62]
Hello,

I'm using Cyberark PAS on version 9.9 and I cannot get a valid session token, I'm following these steps:

Install-Module -Name psPAS -Scope CurrentUser
Import-Module psPAS
$username = "domain\user"
$password = ConvertTo-SecureString -String "myPassword" -AsPlainText -Force
$credentials = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $username, $password
$token = New-PASSession -Credential $credentials -BaseURI "https://pvwaurl" -Verbose

![error](https://user-images.githubusercontent.com/19361884/38779518-ea33c532-40c9-11e8-93c0-4a6e07147635.PNG)

Do you know what could be happening?

Thanks

**Comment by pspete** [comment]
Hi @manelmolina - hopefully i can help - can you try a few things?

When I use a domain/LDAP user to authenticate, I do not specify the domain - do you usually include the domain when logging onto the web portal in your environment?
can you try:
  - `$username = "user"` instead of `$username = "domain\user"`?
    - When testing the code you gave as an example I see that the "`\`" gets escaped as "`\\`" in the JSON being sent - so am not sure if this is causing an issue at the server or not.
  - or can you test with a local CyberArk user?

Do you know if the web.config on PVWA server has been updated to configure the PAS REST API to work with https? i think this raises a 404 error though, not the 500 you are seeing.

**Comment by manelmolina** [comment]
Thank you for your reply

By default PVWA is configured to login using domain accounts (without write the domain name) but also is available local users login, I tried to write just my username and domain||username but still not working.

Tomorrow I will try a local account and I will check web.config file (which is the path?)

A lot of thanks

**Comment by pspete** [comment]
The path is `<Drive>:\inetpub\wwwroot\PasswordVault\web.config`
In the `<services>` section, you change `bindingConfiguration="httpBinding"` to `bindingConfiguration="httpsBinding"` for the follwoing:
`CyberArk.WSAuthentication.Cyberark.CyberArkAuthenticationService`
`CyberArk.PasswordVault.WebServices.WF.PIMServices`
`CyberArk.WSAuthentication.Shared.RestfulAuthenticationService`
`CyberArk.WSAuthentication.SAML.SAMLAuthenticationService`

but I am 90% certain this is not the issue , as I mentioned - this usually shows itself as a 404... but, if `CyberArk.WSAuthentication.Shared.AuthenticationService` has been changed from `bindingConfiguration="defaultBinding"` to `bindingConfiguration="httpsBinding"`, then this would result in a 500 Server Error being returned - so if this one is set to `httpsBinding`, setting back to `defaultBinding` may help.

Out of interest - try `Get-PASServerWebService -BaseURI https://pvwa_url` - this is the only function which requires no authentication - does this return a 500 error, or does it return output similar to the below:
![image](https://user-images.githubusercontent.com/10600090/38782069-08b87d56-40e6-11e8-8787-df284ca7fbdb.png)

Let me know how you get on.

**Comment by pspete** [comment]
Any progress @manelmolina ?
Does `Get-PASServerWebService` also return a 500 status code error?

**Comment by manelmolina** [comment]
Hello,

Applying the right configuration on web.conf works properly, thank you so much,

You can close the issue

**Comment by pspete** [comment]
Good to hear @manelmolina - thanks for the update
