### ISSUE TITLE
Specifying an account DN with add-pasaccount

### ISSUE THREAD

**Issue by tsherwin** [pspete/psPAS#67]
Our SunOne LDAP platform (PAS 9.7) requires userDN as an account attribute before it can be vaulted.  I'm able to add optional parameters to other platforms with the -Properties switch, but not quite sure how to tackle this.

$token | Add-PASAccount -safe ${safeName} -platformID ${platformName} -address ${address} -username ${accountName} -password ${secureStringPassword} 

Invoke-PASRestMethod : [400] Cannot add account; reason: Missing mandatory parameter in Platform SunOneDirectorySSL. (parameter: UserDN)
At C:\software\powershell\psPAS\psPAS\Functions\Accounts\Add-PASAccount.ps1:322 char:3
+         Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body -Headers $sessionToken ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod

**Comment by pspete** [comment]
Good Question @tsherwin - I can't say this is something I have tested before - so will have to do some testing.
  
  
Out of interest - what is the behavior if you  do specify the UserDN using the properties switch?
`$token | Add-PASAccount -safe ${safeName} -platformID ${platformName} -address ${address} -username ${accountName} -password ${secureStringPassword} -properties @{"UserDN"=$UserDN}`

**Comment by tsherwin** [comment]
Add-PASAccount : A parameter cannot be found that matches parameter name 'properties'.
At line:1 char:150
+ ... tringPassword} -properties @{"UserDN"="uid=ts226-sa;ou=people"}
+                    ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-PASAccount], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Add-PASAccount

**Comment by pspete** [comment]
My bad - gave you the wrong parameter name :pensive:

It's actually called _DynamicProperties_:
`$token | Add-PASAccount -safe ${safeName} -platformID ${platformName} -address ${address} -username ${accountName} -password ${secureStringPassword} -DynamicProperties @{"UserDN"=$UserDN}`

**Comment by tsherwin** [comment]
That seemed to do it.   Thank you so much!

**Comment by pspete** [comment]
:thumbsup: Perfect - good to hear!
