### ISSUE TITLE
Add-PASAccount - Missing mandatory parameter

### ISSUE THREAD

**Issue by tsherwin** [pspete/psPAS#68]
EPV v9.7 platform does not require address in PVWA (used for non-system type accounts), and get-help indicates address is optional, but running following results in below error. Also fails in Postman.

$token | Add-PASAccount -safe ${safeName} -platformID ${platformName} -username ${accountName} -password ${secureStringPassword} -disableAutoMgmt $true -disableAutoMgmtReason "GenericID"
    
Invoke-PASRestMethod : [400] Cannot add account; reason: Missing mandatory parameter. (parameter: Address)
At C:\software\powershell\psPAS\psPAS\Functions\Accounts\Add-PASAccount.ps1:322 char:3
+         Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body -Headers $sessionToken ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : CAWS00001E,Invoke-PASRestMethod

**Comment by tsherwin** [comment]
I'm so sorry, you're of course correct.  Thank you.

**Comment by pspete** [comment]
So suspected bug/documentation error - I really should get around to documenting all occurrences of these .....

**Comment by 27560** [comment]
I am getting the following error:
Invoke-PASRestMethod : [400] Missing Mandatory parameter: [DeviceType]. When attempting Add-PASAccount. Any thoughts?

**Comment by 27560** [comment]
PS C:\Windows\system32> $token | Add-PASAccount -safe SAFENAME -PlatformID PLATFORMNAME -Address ADDRESSNAME -username USERNAME -Verbose
VERBOSE: Version Requirement Not Checked
VERBOSE: POST https://SERVERNAME/PasswordVault/api/Accounts with -1-byte payload
Invoke-PASRestMethod : [400] Missing Mandatory parameter: [DeviceType].
At C:\Program Files\WindowsPowerShell\Modules\pspas\Functions\Accounts\Add-PASAccount.ps1:518 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : PASWS017E,Invoke-PASRestMethod

**Comment by 27560** [comment]
it was due to me not passing a password parameter, once I added that, it worked
