### ISSUE TITLE
LDAP authentication not working in CyberArk 10.3

### ISSUE THREAD

**Issue by pspete** [pspete/psPAS#71]
## Your Environment

* PowerShell Version: Core
* psPAS Branch & Version: Master/1.3.0
* CyberArk Version: 10.3

## Expected Behaviour

When using LDAP credentials, authentication should work

## Current Behaviour

When using LDAP credentials, authentication does not work

## Possible Solution

Update URL from `..../WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon`
To `..../api/Auth/LDAP/Logon`

Relates to #70 and requires a substantial update to the module

## Steps to Reproduce (for bug reports)

1 . `New-PASSession -Credential $LDAPCreds -BaseURI https://cyberark`

## Sample Output

`Invoke-PASRestMethod : [403] Authentication failure.`

**Comment by oliverolli** [comment]
Hi
We are experiencing this error. When can a workaround or solution be expected?

**Comment by pspete** [comment]
Hi @oliverolli  - you are welcome to try fix currently implemented in the [psPAS Version 2 Branch](https://github.com/pspete/psPAS/tree/psPAS_2_0).
I still have a few more updates to make until merging into master - but the LDAP process auth will not change.

**Note**: there is a new parameter required at logon; specify "__`-type LDAP`__" when logging on with `New-PASSession`

**Comment by oliverolli** [comment]
Hi! adding -type LDAP in version 2.0 fixed the problem. Looking forward to the release of 2.0

**Comment by pspete** [comment]
Now merged into master branch
