### ISSUE TITLE
Help file typo

### ISSUE THREAD

**Issue by JohnnyLeuthard** [pspete/psPAS#8]
1st off just looking at these I think they are great. I have been struggling to get some wrappers around the API's and getting very frustrated. I have several and they work awesome but yours are much cleaner and professional. It kind of makes me feel like an beginner. 

On thing I notices when I was trying to figure out the flow of things is your function Get-EscapedString.
In your help example you have the name as Get-PASEscapedString
. 

I just thought I'd point that out. The functions I looked at where it is used are calling the actual function name.

**Comment by pspete** [comment]
Hi @JohnnyLeuthard - good spot! 

That function was renamed at some point. Typo is now fixed.
Thanks for the input - very much appreciated!
