### ISSUE TITLE
Export-PASPlatform Set-Content Issue

### ISSUE THREAD

**Issue by jmk-foofus** [pspete/psPAS#86]
Hi,

## Your Environment

* PowerShell Version: 4.0
* psPAS Branch & Version: master/b41073b
* CyberArk Version: 10.4

## Current Behaviour

I'm attempting to export platforms using the following:

$CAToken | Export-PASPlatform -PlatformID "TestPlatform" -Path test.zip

This results in test.zip being created with the following text in it, rather than an actual ZIP:

@{Path=test.zip; Value=System.Object[]; Encoding=Byte}

## Possible Solution

The line "$output | set-content" doesn't appear to parse the parameters in the object. I'm not sure if this is the ideal fix, but it works for me:

```
@@ -117,7 +117,7 @@ function Export-PASPlatform {

                                try {

-                                       $output = [PSCustomObject]@{
+                                       $output = @{
                                                Path     = $path
                                                Value    = $result
                                                Encoding = "Byte"
 @@ -131,7 +131,7 @@ function Export-PASPlatform {
                                        }

                                        #write it to a file
-                                       $output | Set-Content -ErrorAction Stop
+                                       Set-Content @output -ErrorAction Stop

                                } catch {throw "Error Saving $path"}
```

**Comment by pspete** [comment]
@jmk-foofus - your suggested fix did the job, so added you as co-author on the commit (all credit should be to you though).
Now merged into master which will update the PowerShell Gallery.

Thank You for contributing!
