### ISSUE TITLE
Errors handling

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#88]
Hello
Are you planning to implement any additional error handling?
For example in New-PASSession if Invoke-PASRestMethod fails it just returns an output to the screen. Without possibility to use try/catch and get error info to the variable. 
Sample output 
Invoke-PASRestMethod : [403] Authentication failure.
At C:\Users\yyy\Documents\WindowsPowerShell\Modules\psPAS\Functions\Authentication\New-PASSession.ps1:234 char:18
+             $PASSession = Invoke-PASRestMethod -Uri $URI -Method POST -Body $Body -Sessio ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : ITATS004E,Invoke-PASRestMethod

**Comment by pspete** [comment]
Hi @olegasdo 

If you specify `-erroraction stop` when calling `Invoke-PASRestMethod` (or any of the other module functions) you can catch any reported errors:

```powershell
try{
    New-PASSession -credential $credentials -baseURI https://cyberark.local -ErrorAction Stop
}
catch{
    #your error handling here
}
```

Any encountered errors are currently reported using `Write-Error` in the `Invoke-PASRestMethod` function, so are not terminating; the error handling must be done in your code.

I agree that any error reported during authentication should be a terminating one, so will add this to my to do list and see what is possible.

**Comment by olegasdo** [comment]
Hi.
Yes it's were I ended. But with that Powershell... Different message locations in different versions. Version 4 returns ArrayList of 2 elements in -ErrorVariable, Version 10 element list :)
With Error message located in different elements.

**Comment by pspete** [comment]
CyberArk version 10?

**Comment by olegasdo** [comment]
10.2

**Comment by olegasdo** [comment]
Powershell Version 4
![image](https://user-images.githubusercontent.com/28575457/43507338-876a4948-9575-11e8-95db-658063ec7c2d.png)

Powershell Version 5.1
![image](https://user-images.githubusercontent.com/28575457/43507349-92e521d0-9575-11e8-95e3-a60a2737dbef.png)

**Comment by olegasdo** [comment]
Thanks for info
ended up using exception object ($_) in catch.
