### ISSUE TITLE
Error - Add account

### ISSUE THREAD

**Issue by manelmolina** [pspete/psPAS#89]
## Your Environment

* PowerShell Version: Major: 5 Minor 1 Build 17134 Revision 165
* psPAS Branch & Version: 1.2.0
* CyberArk Version: 9.9.0 (9.90.0.18) 

## Expected Behaviour

Creation of account

## Current Behaviour

Using the following command

$token | Add-PASAccount -AccountName $accountName -ExtraPass1Name "test" -ExtraPass3Name "Password_Reset" -address "test.ad" -Username $newUsername -platformID $platformID -SafeName $newSafe -Password $SecurePassword

(test.ad is the active directory domain name)

PowerShell show the following message error: Invoke-PASRestMethod : [400] Cannot add account; reason: specified linked account missing required information. Make
sure Safe name and Object name are specified. Linked account type: Logon

Does anyone know what could be wrong?

Thanks
Best regards

**Comment by olegasdo** [comment]
Hi
Try adding to you line 
-DynamicProperties @{LogonDomain="$LogonToValue"}
$LogonToValue for local account will be ServerName/IP
For domain account - domain name

Regards
Olegas

**Comment by manelmolina** [comment]
Same error :(

**Comment by pspete** [comment]
Hi @manelmolina, as per the error message, you'll need to specify the ExtraPass1Name, ExtraPass1Safe & ExtraPass1Folder parameters.

**Comment by manelmolina** [comment]
Thanks for the replies,

Now I have a different error message:

Invoke-PASRestMethod : [400] Cannot add account; reason: specified linked account not found. Make sure the object exists and can be accessed. Linked account type: Logon, Safe: mySafeName, Folder: Root, Name: domainName

I tried adding -DynamicProperties @{LogonDomain="$LogonToValue"} but I don't know if I'm using this parameter correctly, I understand that should be:

-DynamicProperties @{LogonDomain="myDomainName"}   right?

**Comment by pspete** [comment]
Ok, so check the values you are providing.
Is the logon account named "test"? (That's the name in the safe, not in the directory)

**Comment by manelmolina** [comment]
![config](https://user-images.githubusercontent.com/19361884/43949437-c74bc82e-9c8d-11e8-9019-7727f97d16c4.png)

This is how I understand that I have to get the information to build the command line, it's oK?

Thank you again

**Comment by olegasdo** [comment]
Hi
I think, that logon to is the setting I was talking about.
You set it via dinamyc property
Extrapass1 is one of special accounts. Just like extrapass3 is
reconciliation account. I was not setting extrapass1 and 2 settings when
creating accounts, only extrapass3

Regards
Olegas

**Comment by pspete** [comment]
Hi @manelmolina - I've been away, are you still having issues?

Have you tried setting up an account as you need it manually and validating the required parameters on the account?

![image](https://user-images.githubusercontent.com/10600090/45046606-88a1db00-b06e-11e8-93c8-368f459b1bdf.png)

I think it will help clear up the confusion of which values you need to pass.

**Comment by pspete** [comment]
@manelmolina - As no update, I assume you worked past the issue.
Closing the issue, but please comment if you still face difficulty.
