### ISSUE TITLE
Request : allow Set-PASSafeMember to check 'Validate Safe Content'

### ISSUE THREAD

**Issue by oliverolli** [pspete/psPAS#91]
Hi.
What I want to do:
I want to add an administrator account with the same privileges as the safe owner/creator. I am currently trying to do so with the following powershell command:
$token | Add-PASSafeMember -SafeName $safename -MemberName Administrator @admin_rights_hash

Where admin_Rights_hash is defined as:
$admin_Rigths_hash=@{
UseAccounts = $True; 
RetrieveAccounts = $True; 
ListAccounts = $True; 
AddAccounts = $true; 
UpdateAccountContent = $true; 
UpdateAccountProperties = $true; 
InitiateCPMAccountManagementOperations = $true; 
SpecifyNextAccountContent = $True; `
RenameAccounts = $true; 
DeleteAccounts = $true; 
UnlockAccounts = $true; 
ManageSafe = $True; 
ManageSafeMembers = $True; 
BackupSafe = $True; 
ViewSafeMembers = $true; 
ViewAuditLog = $true; 
RequestsAuthorizationLevel = 1; 
AccessWithoutConfirmation = $true; 
CreateFolders = $True; 
DeleteFolders = $True; 
MoveAccountsAndFolders = $True
}

This gives me all the Authorizations i want except for 'Validate Safe Content'.
Is it possible to add a feature to the Set/Add-PASSafeMember function such that this right can also be given, or is there another method I should use to add additional owners to a safe

Thank you for a great PowerShell module, helping a great deal when streamlining the management of CyberARK.

Regards oliverolli

**Comment by pspete** [comment]
Hi @oliverolli - Apologies for the delay - 

I don't believe it is possible via the REST API - reason being is that ValidateSafeContent is only visible in PrivateArk Client, not PVWA; PVWA has no matching permission category for ValidateSafeContent, therefore it is not exposed by the API.

I think the only option is to manually set via PrivateArk, or use PACLI (my PoShPACLI [Set-PVSafeOwner](https://github.com/pspete/PoShPACLI/blob/master/Functions/Safes/Set-PVSafeOwner.ps1) function may help)

**Comment by oliverolli** [comment]
Okay 
Thank you for your reply.
I will probably resort to leaving it unchecked, and check it manually when required.
