### ISSUE TITLE
Get-PASAccountPassword not working with v9.9.5

### ISSUE THREAD

**Issue by kostja1979** [pspete/psPAS#92]
## Your Environment

* PowerShell Version: 5.1
* psPAS Branch & Version: 2.2.0
* CyberArk Version: 9.9.5

## Expected Behaviour
$token | Get-PASAccount -Keywords $a_fqdn -WarningAction Stop | Get-PASAccountPassword
should output the password value

## Current Behaviour
$token | Get-PASAccount -Keywords $a_fqdn -WarningAction Stop | Get-PASAccountPassword
{112, 120, 99, 111...}

## Possible Solution

Please note that with psPAS 0.8.7 it works fine

## Steps to Reproduce (for bug reports)

1 . $token = New-PASSession -UseV9API -Credential $credential -BaseURI $VaultURL
2 . $token | Get-PASAccount -Keywords $a_fqdn -WarningAction Stop | Get-PASAccountPassword

## Sample Output
{112, 120, 99, 111...}

**Comment by Onkl** [comment]
I do have the exact same problem. According to the documentation it should return a string with the password but it returns an array with ASCII byte values...

**Comment by pspete** [comment]
I've been off on holiday - apologies for the late response.
Issue reproduced - looks like I introduced a bug on [this commit](https://github.com/pspete/psPAS/commit/1efc3b22e8fd030d4b7bf1f8d2fa66f1e1afb116)

Will work on a resolution

**Comment by kostja1979** [comment]
It works fine! Thanks @pspete!
