### ISSUE TITLE
To get/list all the account for CyberArk Version: Version 9.8.0 (9.80.0.7)

### ISSUE THREAD

**Issue by Lincux** [pspete/psPAS#93]
## Your Environment

* PowerShell Version: 4.0
* psPAS Branch & Version: Get-PASAccount
* CyberArk Version: Version 9.8.0 (9.80.0.7)

## Expected Behaviour
To get/list all the account.

## Current Behaviour
Version 9.3 - 10.3:
Returns information about an account. If more than one account meets the search criteria,
only the first account will be returned (the Count output parameter will display the number
of accounts that were found).

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
Hi @Lincux - what you want to achieve simply is not possible before CyberArk 10.4; the help text you pasted specifically states the limitation and affected versions.
`Get-PASAccount` has already been updated to return lists of results found when searching for accounts in CyberArk 10.4+

**Comment by pspete** [comment]
@Lincux - I'm closing this as there is nothing to do where an option is not supported by the API - the functionality you want is only available through the API from CyberArk 10.4 onwards.
