### ISSUE TITLE
error api doc, Get-PASUser points toNew-PASSession

### ISSUE THREAD

**Issue by kbcxmrln** [pspete/psPAS#95]
Error
Get-PASUser points toNew-PASSession
https://github.com/pspete/psPAS/blob/master/psPAS/Functions/Authentication/New-PASSession.ps1

## Your Environment

* PowerShell Version:
* psPAS Branch & Version:
* CyberArk Version:

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
Good spot! Will get it fixed. Thanks for reporting it.

**Comment by kbcxmrln** [comment]
Public

You're welcome

Would like some examples storing/retrieving credentials, i am quite new to this, to get me started.

Also do I need to AES encrypt own generated passwords or not before storing them, if so I would need to store a key

Any info welcome to get me started with this
