### ISSUE TITLE
Feature Request - MFA Support

### ISSUE THREAD

**Issue by aleksbor** [pspete/psPAS#96]
## Your Environment

* PowerShell Version: 5.1
* psPAS Branch & Version: 2.2.2
* CyberArk Version:  9.10.0 (9.99.0.12)

## Expected Behaviour

I need to be able to specify a user name and RSA token

## Current Behaviour

User credentials only

## Possible Solution

Add MFA support

## Context

Trying to authenticate using MFA.

**Comment by pspete** [comment]
Hi @aleksbor - I think you need to raise an enhancement request with CyberArk - This module is limited to documented capabilities of the API, unless you have technical documentation which shows how this can be achieved?

**Comment by pspete** [comment]
@aleksbor - I have reviewed the documentation available and have not found any mention of support for MFA when authenticating to the API in any current version of CyberArk. Therefore I am closing this as I cannot include in the module anything which is not made possible in the product.
If the feature gets released in a future version, it will be incorporated into the module as all other new API features are.

Best,

pspete
