### ISSUE TITLE
Get-PASAccount new functionality 

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#99]
Hello
Is it some limitation of the new API, that it's not possible to get account using new search option from specific safe? 

Regards
Olegas

**Comment by pspete** [comment]
It is still possible, but the way to do it has changed.

Now the parameter "filter" must be specified with a query like below:
`Get-PASAccount -filter "safename eq SafeName"`

**Comment by pspete** [comment]
Unfortunately the documentation is not clear on this. 
I only recently found out how the filter parameter works, and I only have this example.
The help text will be updated with this example soon.

**Comment by olegasdo** [comment]
Thank you again :)
